coreos/ignition

- log/stdout.go
Println already adds a space between each parameter.
> log: remove extra space

- doc/config.md
The wipe-table directive can be used to effectively "force" the partition
create to succeed by first clearing any existing partition table.
It may also be used to simply clear the partition table of the respective
disk if no partitions are defined.
Without first wiping, a partition create may fail if it collides with
existing partitions, which should cause ignition to fail.
> doc: introduce wipe-table for disks

- doc/config.md
Also correct by-label paths to be by-partlabel, and introduce format-options.
> doc: convert device references to always be paths

- main.go
- oem/oem.go
Setting the OEM is a shortcut for setting additional flags. The service
which starts Ignition will typically set "OEM_NAME=pxe" in the
Environment clause and then source /usr/share/oem/environment (or
similar). If the OEM provides a name, it will override the default. The
name is then used when running ignition: `ignition --oem=${OEM_NAME}`.
> oem: add ability to set OEM

- exec/stages/prepivot/prepivot.go
- exec/util/destdir.go
- exec/util/file.go
- exec/util/unit.go
Introduces a type to represent the root path diversion to prefix in
file/directory creates which we can hang such methods off of rather
than passing a root string all over the place and having some pieces
construct paths with the root prefixed while others don't.
>     exec/util: introduce DestDir type for influencing file/dir creates

- src/exec/engine.go
- src/main.go
It's unsafe to assume the provider won't alter a configuration between
invocations.  Since we will be invoked multiple times between the various
stages in a single ignition sequence, we must cache and reuse the initially
fetched config to completion.
> config: locally cache provided config for reuse across stages

- doc/config.md
- src/config/filesystem.go
- src/exec/stages/storage/storage.go
One must explicitly enable intialization of a filesystem, if omitted or
set to false then no mkfs will be performed, but the Files section of the
filesystem may still be populated and applied to a preexisting filesystem
on the named device.
> config: Introduce Filesystem.Initialize toggle

- doc/config.md
- src/config/raid.go
- src/exec/stages/storage/storage.go
mdadm --create doesn't accept spares as explicit devices, this tweaks
the config to better fit mdadm and changes the mdadm integration
accordingly.
> config/storage: specify raid spares as an integer

- Makefile
This also eliminates the need for two invocations of gofmt, and passes
src instead of the discrete packages as gofmt is recursive.
> Makefile: put gofmt in diff mode for fmt target

- src/config/partition.go
From:
http://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_entries
56 (0x38) 	72 bytes 	Partition name (36 UTF-16LE code units)
sgdisk silently truncates excessively long names, but we'll fail with an
error now for for both JSON and YAML.
> config: limit partition label length to 36 characters

- doc/config.md
- src/config/partition.go
- src/exec/storage.go
- src/sgdisk/sgdisk.go
JSON and YAML both now support "type-guid" in the partition specification.
> storage: support partition type GUID

- src/config/networkd.go
- src/config/systemd.go
- src/config/unit.go
- src/config/unit_test.go
- src/exec/engine_test.go
- src/exec/storage.go
- src/exec/util/unit.go
systemd and networkd units are fundamentally different structures. It
doesn't make much sense for them to share the same representation during
parsing.
> config: seperate systemd and network units

- third_party.manifest
For now this is a simple list of the vendored packages and their versions.
We'll manually update this list to reflect what's in third_party.
> third_party: add third_party.manifest file.

- third_party.manifest
The version column was shifted with the addition of update-ssh-keys, but the
header wasn't updated accordingly.
> third_party: fix header alignment of version in manifest

- doc/config.md
- src/config/filesystem.go
- src/exec/stages/disks/disks.go
changes from:
filesystems:
- device: "/dev/disk/by-partlabel/ROOT"
format: btrfs
initialize: true
options:
- "--label=ROOT"
to:
filesystems:
- device: "/dev/disk/by-partlabel/ROOT"
format: btrfs
create:
force: true
options:
- "--label=ROOT"
Previously the force flag was always added to the mkfs options, now
it's only added when `force: true`.
The mkfs.$format is only performed if a `create` section is present,
instead of using the `initialize` boolean.
Also some minor cleanups to the config.md example/doc.
> config: rearrange config.Filesystem for optional forcing

- Makefile
So they're included in vet/fmt/fix/test.
> Makefile: add ec2 and files providers to PACKAGES

- src/config/config.go
- src/config/config_test.go
- src/exec/engine.go
When an empty config is encountered, Ignition needs to recognize it and
ignore it. Otherwise, cloud environments with an empty userdata, will
trigger an Ignition failure.
> config: handle empty config

- src/providers/ec2/ec2.go
On EC2, the metadata service returns a 404 when there is no userdata.
Treat this as a successful fetch.
> providers/ec2: properly handle a lack of userdata

- src/providers/ec2/ec2.go
Was short-circuiting the fetching of ssh keys when the config parsed
successfully.
Now ssh keys will be fetched if the config is empty or valid, but not
when the config is a cloud-config, script, or other error.
> providers/ec2: fix handling of configs to always fetch ssh keys.

- src/providers/cmdline/cmdline.go
Fix bug introduced when inverting the fall-through return path in
oem:// addition.
> providers/cmdline: add missing return in http failed fetch path

- src/systemd/systemd.go
They interfere with coreos.ignition.force in particular, this seems to
fix the deadlocks observed @ ignition-disks when forced with a config
reformatting /dev/disk/by-label/ROOT.
> ignition: DefaultDependencies=false in WaitOnDevices transient unit

- src/oem/oem.go
There are still some unresolved issues around networking. Disable ec2
for now.
> oem: disable ec2

- src/exec/util/passwd.go
This is a temporary hack until update-ssh-keys is updated to validate
keys and add newlines.
> exec/util: ensure keys supplied to authorized_keys_d.Add() end with newline

- doc/configuration.md
- doc/getting-started.md
Express optional fields in configuration.md using italics, other
small corrections.
> docs: minor cleanups

- src/oem/oem.go
We've seen cases if AWS taking 66 seconds to offer a DHCP lease. Rather
than playing cat and mouse with them, just remove the timeout
altogether. The emergency shell doesn't buy us anything anyway, given
that the console is not interactive.
> oem: remove timeout for EC2

- src/providers/azure/azure.go
If no userdata is provided, CustomData.bin does not exist on the OVF
DVD. This would result in the following error:
failed to fetch config: failed to read config: open
/tmp/ignition-azure525503356/CustomData.bin: no such file or directory
> providers/azure: handle missing userdata correctly

- src/main.go
Early enough in the boot process /tmp isn't a tmpfs, it's prudent to
use /run instead.
> main: use /run/ignition.json instead of /tmp

- src/exec/util/user_lookup.c
Silence implicit declaration warning for waitpid.
> exec/util: add missing import header

- src/config/config.go
- third_party.manifest
- third_party/github.com/camlistore/camlistore/pkg/errorutil/highlight.go
Use a library from camlistore to help pinpoint exactly where the problem
is if invalid JSON is supplied to Ignition.
> config: be more specific on JSON unmarshal failure

- src/providers/cmdline/cmdline.go
/mnt/oem was created by a systemd mount before. Now that it's been
removed, we need to create the directory ourselves.
> providers/cmdline: create the mount point

- src/systemd/systemd.go
The absolute paths were prefixed with a leading '-', which is incorrect.
Using UnitNamePathEscape() correctly escapes these absolute paths.
> system: properly escape device paths

- CONTRIBUTING.md
- README.md
- ROADMAP.md
- doc/configuration.md
- doc/getting-started.md
- doc/supported-platforms.md
Per CoreOS documentation standards, use one line per block of text rather than
wrapping at 80 columns.
/cc @joshix
> docs: remove line-wrapping

- src/config/filesystem.go
- src/config/filesystem_test.go
Fixes https://github.com/coreos/bugs/issues/1071
Given the following config:
```json
{
"ignitionVersion": 1,
"storage": {
"filesystems": [
{
"device": "/dev/disk/by-label/ROOT",
"files": [
{
"path": "/alex",
"contents": "HELLO\n",
"mode": 444
}
]
}
]
}
}
```
Ignition now fails with:
```
Jan 11 19:12:16 localhost ignition[222]: Ignition v0.2.4-7-g6159283-dirty
Jan 11 19:12:16 localhost ignition[222]: parsed url from cmdline: "oem:///ignition.json"
Jan 11 19:12:16 localhost ignition[222]: oem config not found in "/usr/share/oem", trying "/mnt/oem"
Jan 11 19:12:17 localhost ignition[222]: op(1): [started]  mounting "/dev/disk/by-label/OEM" at "/mnt/oem"
Jan 11 19:12:17 localhost ignition[222]: op(1): [finished] mounting "/dev/disk/by-label/OEM" at "/mnt/oem"
Jan 11 19:12:17 localhost …
```
> config: assert validity of filesystems

- src/sgdisk/sgdisk.go
sgdisk is a bit weird and will exit with code 2 if there is trouble with the GPT
headers, even it successfully zaps them. Retrying the zap operation will allow
us to be sure that the operation completed successfully.
> sgdisk: retry zap-all operation on failure

- doc/configuration.md
This also moves the version number from:
```json
"ignitionVersion":
```
to
```json
"ignition": {
"version":
}
```
> docs: use semantic versioning for the spec

- src/providers/vmware/vmware.go
- src/providers/vmware/vmware_amd64.go
- src/providers/vmware/vmware_unsupported.go
When built on unsupported architectures, the datasource will permanently report that it is offline.
> providers/vmware: allow building on non-amd64

- src/providers/cmdline/cmdline.go
The behavior changed in 2285d6, but the comment wasn't updated.
> providers/cmdline: fix comment about OEM root path

- doc/supported-platforms.md
- src/config/cloudinit.go
- src/config/config.go
- src/providers/vmware/vmware.go
- src/providers/vmware/vmware_amd64.go
This is needed to properly decode cloud-configs, which this needs to recognize
and ignore. While we are at it, we might as well add encoding support for
Ignition configs as well.
Fixes https://github.com/coreos/bugs/issues/1170
> providers/vmware: add support for config encoding

- src/config/types/filesystem_test.go
- test
Additionally, enable tests on the config/types package. There must be a better
way to keep up with code restructuring.
> config/types: fix filesystem tests

- doc/getting-started.md
- src/exec/engine.go
This will be appended by all configs and provides a definition for the "root"
filesystem mounted at "/sysroot". This way, users don't need to worry about the
implementation details of the initramfs and Ignition.
> {docs,exec}: add a base configuration

- src/util/http.go
The body should only be returned if the response status code is a 200.
Otherwise, if the response status code is on the list of acceptable codes, an
empty body is returned. This will prevent EC2's 404 documents from being
interpretted as a valid config. Instead an empty document will be used.
> util: fix http client's handling of status codes

- config/config.go
- config/config_test.go
The check for major version was causing Parse() to bail too early. The test was
also mistakenly updated to only test ParseFromLatest() instead of Parse(), so it
didn't pick up on this regression.
> config: properly handle non-ignition configs

- internal/exec/stages/files/files.go
If the files are created before the user, the home directory might not
have the correct permissions. When we try to add SSH keys, it fails due
to insufficient permissions.
Fixes https://github.com/coreos/bugs/issues/1241.
> exec/stages: write files after users are created

- internal/exec/engine.go
- internal/main.go
- internal/oem/oem.go
- internal/providers/ec2/ec2.go
Key injection is going to be handled by a different utility. Keys added via the
Ignition config will still work.
> providers/ec2: strip support for SSH keys

- internal/exec/engine.go
- internal/exec/stages/disks/disks.go
Executing even if the user config is empty allows us to always execute
the OEM config. If both the user config and the OEM config are empty,
this is a no-op.
> exec: execute empty user configs

- internal/exec/engine.go
- internal/exec/stages/files/files.go
- internal/exec/util/file.go
- internal/providers/cmdline/cmdline.go
- internal/util/url.go
This will allow the cmdline provider to accept data URLs, files to
reference contents on the OEM partition, and configs to reference remote
configs on the OEM partition.
> *: refactor resource fetching into one location

- internal/exec/stages/disks/disks.go
Fixes problem where ignition overwrites other partitions reguardless of what
filesystems.mount.create.force is set to
> stages/disks: adds -p flag to mkfs.ext4

- config/types/config.go
- config/types/config_test.go
The old code assumed all pointers pointed to structs.
> config: properly dereference pointers

- internal/exec/util/file.go
- internal/exec/util/unit.go
- internal/util/http.go
- internal/util/url.go
- internal/util/verification.go
- internal/util/verification_test.go
Use io.Reader instead of reading whole files into memory. Prevent
ignition from using large amounts of memory when writing large files.
Also make default http timeout for connection, not the entire transfer
> Add support writing large files/empty files

- config/types/url.go
If the URL fails to parse, we shouldn't try to dereference a nil.
> config/types: fix url parsing

- config/types/node.go
- config/types/node_test.go
This was lost in 14ae594fa6e31b67a6756cfd57296f5687b76f96.
> config/types: add validity assertion for node

- internal/util/http.go
The original intention of this code was to retry requests if the remote
server didn't return content. This caused issues for the HTTP-based
providers because they will return a 404 when there is no userdata.
Since the underlying purpose of this retry is to handle transient
errors, it makes sense to only retry if there is a network error or if
the remote system returned a 5xx error.
> util/http: unconditionally return HTTP result

- internal/oem/oem.go
- internal/providers/qemu/qemu.go
The config can be passed to QEMU by using the following:
-fw_cfg name=opt/com.coreos/config,file=config.ignition
> providers: add support for qemu firmware config

- internal/oem/oem.go
- internal/providers/file/file.go
Useful for ad-hoc tests using a local config.json.
> providers: restore the file provider, add file oem

- internal/exec/stages/disks/disks.go
- internal/exec/util/device_alias.go
Because ignition and the utilities it invokes may race with udev
manipulating symlinks in response to actions performed on the devices,
create stable aliases for the user-provided device paths which are
derived from the supplied paths for convenient correlation within the
logs.
We could simply resolve the symlinks to the bare device paths and use
those, but we execute external utilities against the devices and it's
preferable to have the potential errors printed by those utilities
include device paths resembling what the user provided.
The aliases are logged when created, producing logs like:
Aug 24 17:40:03 localhost ignition[9655]: disks: createFilesystems: created device alias for "/dev/disk/by-partlabel/FOO": "/dev_aliases/dev/disk/by-partlabel/FOO" -> "/dev/sdb1"
> exec/util: create and use stable device path aliases

- internal/systemd/systemd.go
When waiting on multiple devices multiple result channels are supplied
to go-systemd.  These channels are then consumed from serially in the
order they were submitted.  If we get unlucky and
systemd/dbus/go-systemd come back with results in a different order,
then go-systemd will get deadlocked in jobComplete() because the channel
is unbuffered and we're not receiving on the other end.
This change simply makes the result channels buffered so jobComplete()
doesn't block on us while we wait on a different channel.
> systemd: fix potential deadlock in WaitOnDevices

- internal/oem/oem.go
As part of coreos/bugs#1468, this should only be bumped in coreos-overlay with a bunch of other changes so this new service makes sense.
> oem: unify GCE services as one rkt service

- doc/examples.md
- Describe how to modify existing services using a systemd unit drop-in
- Set syntax-highlighting for systemd unit examples to `INI`
> Add systemd unit drop-in example

- doc/getting-started.md
- internal/exec/engine.go
- internal/oem/oem.go
- internal/providers/cmdline/cmdline.go
- internal/providers/digitalocean/digitalocean.go
- internal/providers/ec2/ec2.go
- internal/providers/gce/gce.go
- internal/providers/openstack/openstack.go
- internal/providers/packet/packet.go
- internal/resource/url.go
This allows the `coreos.config.url` command-line option to override the
specified provider.
> exec/engine: allow commandline options to override

- internal/providers/file/file.go
The 'ign' extension should be used for Ignition configs, per the IANA
registration.
> providers/file: rename config file

- internal/providers/file/file.go
This PR adds ```vanilla oem```  which is created by @mikedanese [here](https://github.com/mikedanese/ignition/tree/vanilla) and adapts it to new ```providers``` interface.
//cc @mikedanese
> Add vanilla oem

- config/types/unit.go
- config/types/unit_test.go
- config/validate/validate_test.go
- config/vendor.manifest
- config/vendor/github.com/coreos/go-systemd/LICENSE
- config/vendor/github.com/coreos/go-systemd/unit/deserialize.go
- config/vendor/github.com/coreos/go-systemd/unit/deserialize_test.go
- config/vendor/github.com/coreos/go-systemd/unit/end_to_end_test.go
- config/vendor/github.com/coreos/go-systemd/unit/escape.go
- config/vendor/github.com/coreos/go-systemd/unit/escape_test.go
- config/vendor/github.com/coreos/go-systemd/unit/option.go
- config/vendor/github.com/coreos/go-systemd/unit/option_test.go
- config/vendor/github.com/coreos/go-systemd/unit/serialize.go
- config/vendor/github.com/coreos/go-systemd/unit/serialize_test.go
After use cloud-config during a long time and now with ignition, I really know that one of the most common pains working with, is the malformed units. 
So I think that could be a good idea validate the content, al least the format. The names are being validated so I don't see wait not the content.
I am using `coreos/go-systemd` deserializer, so this check just that the format is correct, is not checking the systax of the units, something that is very inserting too. 
BTW A good improvement can be also do the validator in a pattern that be extended by third-parties, now is totally imposible do this without modding the ignition code base, or create a complete different algorithm
> types: unit validator

- config/config_test.go
- config/types/config.go
The intent is to expose this version to end users to allow for testing.
Ignition will continue to only advertise tagged versions, but will
optionally accept experimental pre-releases as well.
> config: rename dev prelease to experimental

- internal/providers/openstack/openstack.go
Currently the dispatcher func always performs fetching from config
drive, but never from a metadata service.
This fixes it.
> openstack: fix dispatcher

- build
- internal/providers/openstack/openstack.go
- test
It's been observed that the config drive has the label "CONFIG-2"
instead of "config-2". This checks for both locations since we don't
know which one will be used.
Tested on VEXXHOST with the network metadata service:
```
$ journalctl -t ignition
-- Logs begin at Thu 2017-02-23 03:12:09 UTC, end at Thu 2017-02-23 03:12:37 UTC. --
Feb 23 03:12:11 localhost ignition[357]: Ignition v0.12.1-46-gb197bbe-dirty
Feb 23 03:12:11 localhost ignition[357]: parsed url from cmdline: ""
Feb 23 03:12:11 localhost ignition[357]: no config URL provided
Feb 23 03:12:11 localhost ignition[357]: GET http://169.254.169.254/openstack/latest/user_data: attempt #1
Feb 23 03:12:11 localhost ignition[357]: config drive ("/dev/disk/by-label/config-2") not found. Waiting...
Feb 23 03:12:11 localhost ignition[357]: …
```
> providers/openstack: check upper and lower case

- internal/oem/oem.go
The newest versions of google/cloud-sdk require the docker binary to be
mounted into the container from the host.
Fixes https://github.com/coreos/bugs/issues/1770.
> oem: fix gce gcloud alias

- config/types/unit.go
- config/types/unit_test.go
- config/v2_0/types/unit.go
- config/v2_0/types/unit_test.go
- config/validate/validate_test.go
It is valid for a unit to be empty.
> config/*: correct unit validation logic

- config/validate/validate.go
- config/validate/validate_test.go
Ensure getFields() will correctly unbox an embedded interface{} that
actually contains a struct type. This is used in the config transpiler.
> valdiate: ensure getfields works with interface{}

- doc/examples.md
Refs https://github.com/coreos/bugs/issues/1846 and https://groups.google.com/forum/#!topic/coreos-user/WCxQSPuBJvE
CC: @crawford @joshix 
Examples were not tested, but can be upon request.
> docs: add multiple user configuration example

- internal/oem/oem.go
This service needs to be installed from the OEM partition.
> oem: fix configuration for packet

- config/types/path.go
filepath's isAbs() is platform-specific and reports paths like '/opt/local' as not absolute when run on Windows. The path package behaves the same on all platforms.
Fixes the root cause of https://github.com/coreos/bugs/issues/1876 and https://github.com/coreos/tectonic-forum/issues/81
> type/path: Fix isAbs() validation on Windows.

- config/types/partition.go
- config/types/partition_test.go
- config/types/schema.go
- doc/configuration-v2_1-experimental.md
- internal/exec/stages/disks/disks.go
- internal/sgdisk/sgdisk.go
- schema/ignition.json
(This PR is based on https://github.com/coreos/ignition/pull/325, so ignore all but the final commit. Will rebase once that PR is merged)
This commit allows ignition configs to now also specify a "guid" field
for a partition, which will dictate what the unique GUID for that
partition will be set to when it is created.
Fixes https://github.com/coreos/bugs/issues/1603
Tested with [this config](https://gist.github.com/dgonyeo/e0e18bb9d306a7a479db8e768b78e053), which broke the machine in a way that prevented it from booting, but was able to run `blkid` in the initramfs prompt and see that the one partition's GUID was set properly.
> config/types/partition: added GUID field

- config/types/filesystem.go
- doc/configuration-v2_1-experimental.md
- internal/exec/stages/disks/disks.go
This commit adds support for creating swap devices. Here's an example config that now works with this commit:
```
{
"ignition": {
"version": "2.1.0-experimental"
},
"storage": {
"filesystems": [
{
"mount": {
"device": "/dev/vda6",
"format": "swap",
"create": {
"options": [
"--label=SWAP"
]
}
}
}
]
}
}
```
Fixes https://github.com/coreos/bugs/issues/1407
> stages/disks: added support for filesystems of type "swap"

- internal/oem/oem.go
The initial support was implemented in 51b7f16, but neglected to update
the fetch function.
> oem: fix oem definition for brightbox

- internal/vendor.manifest
- internal/vendor/github.com/coreos/update-ssh-keys/.gitignore
- internal/vendor/github.com/coreos/update-ssh-keys/.travis.yml
- internal/vendor/github.com/coreos/update-ssh-keys/CONTRIBUTING.md
- internal/vendor/github.com/coreos/update-ssh-keys/DCO
- internal/vendor/github.com/coreos/update-ssh-keys/LICENSE
- internal/vendor/github.com/coreos/update-ssh-keys/NOTICE
- internal/vendor/github.com/coreos/update-ssh-keys/build
- internal/vendor/github.com/coreos/update-ssh-keys/src/authorized_keys_d/as_user/as_user.c
- internal/vendor/github.com/coreos/update-ssh-keys/src/authorized_keys_d/authorized_keys_d.go
- internal/vendor/github.com/coreos/update-ssh-keys/src/authorized_keys_d/authorized_keys_d_test.go
- internal/vendor/github.com/coreos/update-ssh-keys/src/main.go
- internal/vendor/github.com/coreos/update-ssh-keys/src/main_test.go
- internal/vendor/github.com/coreos/update-ssh-keys/test
@bgilbert had an issue where some C header files were not being imported in the update-ssh-keys vendored dependency. This dependency had been fixed some time ago, this commit updates the vendored copy here to include the fixes.
> internal/vendor: bump update-ssh-keys to latest master

- config/types/passwd.go
- config/types/schema.go
- doc/configuration-v2_1-experimental.md
- internal/exec/stages/disks/disks.go
- internal/exec/stages/files/files.go
- internal/exec/util/passwd.go
- internal/log/log.go
- internal/providers/openstack/openstack.go
- internal/providers/qemu/qemu.go
- internal/sgdisk/sgdisk.go
- schema/ignition.json
This commit moves all fields in the user create object up one level
directly into the user object. Using the create object and any of these
copied fields is an error. Using the create object generates a
deprecation warning.
When running the files stage, now ignition will first determine if the
described user exists. If the user exists, `usermod` will be used to
change the user to the desired state, and if the user does not exist
`useradd` will be used to create the user.
Dependent on https://github.com/coreos/bootengine/pull/113
> config/type/passwd: deprecate user create object

- .travis.yml
- config/translate.go
- config/translate_test.go
- config/types/node.go
- config/types/node_test.go
- config/types/schema.go
- doc/configuration-v2_1-experimental.md
- internal/exec/stages/files/files.go
- internal/exec/stages/files/files_test.go
- internal/exec/util/file.go
- internal/exec/util/user_group_lookup.c
- internal/exec/util/user_group_lookup.go
- internal/exec/util/user_group_lookup.h
- internal/exec/util/user_group_lookup_test.go
- schema/ignition.json
This commit adds support for referencing a user or group by name instead of ID when creating a node (as in, a directory or file). The uid/gid is resolved using the `os/user` package.
This will be unable to reference users added by `systemd-sysusers`, as is described here: https://github.com/coreos/bugs/issues/1267
Fixes https://github.com/coreos/bugs/issues/1104
Dependent on https://github.com/coreos/bootengine/pull/113
> User group names

- doc/configuration-v2_1-experimental.md
- doc/supported-platforms.md
- internal/resource/url.go
- internal/vendor.manifest
- internal/vendor/github.com/pin/tftp/.gitignore
- internal/vendor/github.com/pin/tftp/.travis.yml
- internal/vendor/github.com/pin/tftp/CONTRIBUTORS
- internal/vendor/github.com/pin/tftp/LICENSE
- internal/vendor/github.com/pin/tftp/README.md
- internal/vendor/github.com/pin/tftp/backoff.go
- internal/vendor/github.com/pin/tftp/client.go
- internal/vendor/github.com/pin/tftp/netascii/netascii.go
- internal/vendor/github.com/pin/tftp/netascii/netascii_test.go
- internal/vendor/github.com/pin/tftp/packet.go
- internal/vendor/github.com/pin/tftp/receiver.go
- internal/vendor/github.com/pin/tftp/sender.go
- internal/vendor/github.com/pin/tftp/server.go
- internal/vendor/github.com/pin/tftp/tftp_test.go
This commit adds support for the tftp schema in the coreos.config.url
command line argument.
Fixes https://github.com/coreos/bugs/issues/1857
This feature is currently entirely untested, as I don't have access to a PXE booting environment currently. I can either work with the infra team to try this out when I get back to SF, or alternatively maybe one of the people who asked for this would have the time to test it out and lete me know if it works (cc @racurrie @glevand)
> internal/resource/url: added support for tftp URLs

- config/translate.go
- config/translate_test.go
- config/types/schema.go
- internal/exec/util/passwd.go
- schema/ignition.json
The password for an existing user shouldn't be touched if it isn't
specified in the config. An empty but specified password results in
password login for the user being disabled (the hash is set to "*").
The `coreos.ignition.v2.users` kola test fails without this fix.
> config/type/passwd: support unspecified passwords

- doc/examples.md
The create object was deprecated. This commit changes the example
dealing with user accounts to not use it.
> doc/examples.md: remove create object from users example

- .travis.yml
- config/translate.go
- config/translate_test.go
- config/types/filesystem.go
- config/types/schema.go
- doc/configuration-v2_1-experimental.md
- doc/examples.md
- doc/filesystems.md
- internal/exec/stages/disks/disks.go
- internal/exec/util/blkid.c
- internal/exec/util/blkid.go
- internal/exec/util/blkid.h
- internal/exec/util/passwd.go
- schema/ignition.json
This PR has three commits. In order:
- the first commit moves the fields inside of the `create` object in the filesystem's mount section one level up, into the `mount` object itself. The `create` object is left in for backwards compatibility reasons, and will generate a warning when used. If the create object exists and the new `force` or `options` fields in the mount object are used, an error is generated
- the second commit adds a new field in the filesystem's mount object called `wipeFilesystem`. If this field is false, and a filesystem of the expected type exists on the device, the filesystem is reused. If this field is true any preexisting filesystem will be removed.
- the third commit adds the libblkid stub for arm64 builds
I can split this up into two PRs if desired.
I tested this …
> deprecate create object, create wipeFilesystem flag

- internal/exec/engine.go
- internal/exec/util/file.go
- internal/main.go
- internal/providers/cmdline/cmdline.go
- internal/providers/digitalocean/digitalocean.go
- internal/providers/ec2/ec2.go
- internal/providers/gce/gce.go
- internal/providers/openstack/openstack.go
- internal/providers/packet/packet.go
- internal/resource/http.go
- internal/resource/url.go
This functionality was lost in d34c2246. This commit reintroduces it as
well as exposing the initial timeout as a flag and removing the
restriction on the maximum number of attempts. The timeouts will control
the number of attempts that can be made.
> *: re-introduce timeouts

- config/types/url.go
- config/types/url_test.go
- internal/resource/url.go
The earlier commit that added support for TFTP urls never added tftp to
the list of supported schemas when validating URLs. This means that
Ignition configs were able to be fetched from TFTP sources, but any TFTP
URLs in the config would cause an error.
> config/types/url: allow tftp urls during validation

- internal/exec/stages/files/files.go
- internal/util/util.go
Recent changes allowing file owners to be referenced by user/group names
changed the id field for the user and group to be a pointer, so that it
could be detected when it was left empty vs when it was specified to be
0. The simple example given to justify this was when a user provided a
config saying that the file should be owned by user "core" and uid "0",
if the id was not a pointer it would appear to Ignition as if they had
not provided a uid.
The logic dealing with setting the UID failed to properly handle nil
values here, and can cause nil pointer dereferences. This commit adds a
check and an assignment to fix this for both of these fields.
If a file's owner is unspecified, it will default to the root user and
group.
> internal/exec/util/file: fix nil pointer dereference

- config/types/filesystem.go
- config/types/filesystem_test.go
- doc/configuration-v2_1-experimental.md
- internal/exec/stages/disks/disks.go
This PR does two things:
- adds validation for filesystem label length, to ensure user entered filesystem labels will not be too long to be accepted by the relevant `mkfs` utility
- adds support for vfat filesystems
Tested in a QEMU instance with this config: https://gist.github.com/dgonyeo/f7ad90bcb845dfa02ce52f661be1ce82
Fixes https://github.com/coreos/bugs/issues/1990
These PRs are needed for this to work:
- https://github.com/coreos/bootengine/pull/115
- https://github.com/coreos/coreos-overlay/pull/2597
> Validate filesystem label length and add vfat support

- config/types/raid.go
Device path validation for raid arrays was accidentally checking the
index of the device's location in the list, and not the device's path
itself, for path validation. This commit fixes that.
> config/types/raid: fix device validation

- config/vendor.manifest
- doc/supported-platforms.md
- internal/providers/vmware/vmware.go
- internal/providers/vmware/vmware_amd64.go
- internal/vendor.manifest
- internal/vendor/github.com/vmware/vmw-ovflib/LICENSE
- internal/vendor/github.com/vmware/vmw-ovflib/README
- internal/vendor/github.com/vmware/vmw-ovflib/ovf.go
- internal/vendor/github.com/vmware/vmw-ovflib/ovf_test.go
When using VMware's OVF, an environment can optionally be provided
(sometimes done interactively when using tools like vSphere). When this
environment is provided, the guest variables are included in an XML
document at `guestinfo.ovfenv` instead of each of the keys being
directly added to the guest variables.
Still needs docs and testing.
> providers/vmware: add support for ovf environments

- doc/development.md
Discussion about which `schematyper` to use when generating `schema.go`. https://github.com/coreos/ignition/pull/382#discussion_r122324601
> doc/development: add schematyper to development tools

- internal/oem/oem.go
Fixes https://github.com/coreos/bugs/issues/2017
> internal/oem: mask user-configdrive.service on brightbox and openstack

- internal/exec/engine.go
- internal/exec/util/file.go
- internal/util/util.go
If a value is passed to root other than the default of '/' then
the baseConfig will be updated to point to the given value rather
than '/sysroot'.
Also updates the RenderFile function from
'internal/exec/util/file.go' to be a member function of Util to
allow the given root parameter to be used rather than always using
'/sysroot'.
> exec: propogate root parameter to baseconfig

- doc/examples.md
All examples, when checked with the CoreOS [ignition validator](https://coreos.com/validate), show a valid status except for the `Add Users` JSON. This PR fixes the JSON as to pass the validation and look similar to the other examples.
> Ensure that adding user example has a valid ignition file

- internal/oem/oem.go
The vagrant-virtualbox oem will now have its own id instead of
using the virtualbox id, which will allow some expanded functionality.
This commit allows Ignition to recognize that new id.
> oem: add vagrant-virtualbox oem-id

- config/config.go
- config/config_test.go
Before this commit Ignition would parse any config with an unrecognized
version as the latest version of the spec. This commit changes this
behavior to instead return an error.
> config: don't parse as latest version when version isn't recognized

- internal/providers/ec2/ec2.go
- internal/providers/gce/gce.go
EC2 and GCE return an HTTP 404 error when Ignition attempts to fetch
its config and the user has not provided any user data. The recent
refactor of the fetching logic had a regression where this is no longer
handled, and the 404 would cause Ignition to fail. This commit makes
these providers ignore any 404 errors.
Fixes https://github.com/coreos/bugs/issues/2043
> internal/providers/{gce,ec2}: ignore 404 errors

- internal/exec/stages/files/files.go
- internal/exec/util/file.go
This was broken by 8f6e802753404e. We need to create a new Util object
which has the desired filesystem-root for this specific file instead of
using the root.
Fixes https://github.com/coreos/bugs/issues/2059.
> stages/files: fix regression affecting file paths

- internal/exec/stages/disks/disks.go
This was broken by bb701519b. Both the new WipeFilesystems flag and the
legacy Force flag need to be checked.
This should fix https://github.com/coreos/bugs/issues/2061, but I haven't tested it yet.
> stages/disks: fix handling of legacy force flag

- internal/exec/stages/disks/disks.go
The previous implementation relied on mkfs utilities properly detecting
existing filesystems and refusing to overwrite them unless the force
flag was set. This didn't work in practice because different utilities
behave differently. As an example, mkfs.ext4 looks at stdin to determine
whether to prompt the user when an existing filesystem was found or to
just blindly overwrite it. Similarly, mkfs.vfat always blindly
overwrites existing filesystems.
This new implementation uses the results of blkid to determine whether
or not an existing filesystem exists. If the filesystem is correct,
Ignition continues to exit early without modification. If the filesystem
is incorrect but the force flag is set, the mkfs utilities will
forcefully create the filesystem. And now, if the filesystem is …
> stages/disks: use blkid results instead of mkfs

- internal/oem/oem.go
Fixes warning:
files: the enable field has been deprecated in favor of enabled
> oem: avoid deprecated field when enabling systemd units

- internal/exec/util/file.go
The target path for a hard link must have the context path for the
filesystem prepended, or the hard link creation will fail. This commit
fixes that.
> internal/exec/util: hard link targets must have context path prepended

- internal/exec/stages/disks/disks.go
Treat upper-case and lower-case letters as equivalent for comparisons.  Allow FAT volume IDs to include a dash, or, for compatibility with previous versions, to omit it. Previously, FAT UUID comparisons would always fail.
Fixes https://github.com/coreos/bugs/issues/2064.
> stages/disks: canonicalize filesystem UUIDs

- internal/exec/stages/files/files.go
- internal/exec/util/file.go
The commit to introduce a new utility function to determine the
user and group caused an issue where if the user wasn't determined
by ignition the runtime would segfault for directories & links and
files wouldn't error out properly. This has been changed to now
properly error out.
> internal/exec/stages/files: fix node creation to properly error

- internal/exec/util/file.go
This commit switches the logic for creating a link to call `os.Lchown` instead of `os.Chown`, since we want to change the owner of the symlink and not the symlink's target
> internal/exec/util/file: use lchown chown when working with links

- doc/supported-platforms.md
- internal/providers/vmware/vmware_amd64.go
This allows guest variables to override values specified in the OVF
environment. This is useful for Terraform in particular because it
does yet understand how to set vApp options instead of guest variables.
This also subtly changes the behavior when an OVF environment cannot be
parsed. Before this change, Ignition would fail with an error message.
Now, a warning is logged and execution continues.
> providers/vmware: guest variables override ovfenv

- internal/exec/stages/disks/disks.go
To prevent inconsistent /dev/md device labels, create raid arrays with
the --homehost any flag which will prevent the system hostname from
being prepended to device labels.
Fixes https://github.com/coreos/bugs/issues/2104
cc @bgilbert
> internal/exec/stages/disks: add --homehost any to mdadm creation

- internal/exec/stages/disks/disks.go
RAID devices are no longer autostarted when ignition is running. This
comment no longer applies.
> internal/exec/stages/disks: remove old comment

- internal/oem/oem.go
Fix a small typo in the name of the socket. Because of it we were facing an error 
```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
```
dgellow@my-vm ~ $ alias gcloud="(docker images google/cloud-sdk || docker pull google/cloud-sdk) > /dev/null;docker run -t -i --net="host" -v $HOME/.config:/.config -v /var/run/docker.sock:/var/run/doker.sock -v /usr/bin/docker:/usr/bin/docker google/cloud-sdk gcloud"
dgellow@my-vm ~ $ gcloud docker -- pull eu.gcr.io/my-org/alpine:latest
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
dgellow@my-vm ~ $ alias gcloud="(docker images google/cloud-sdk || docker pull google/cloud-sdk) > /dev/null;docker run -t -i --net="host" -v $HOME/.config:/.config -v …
```
> Fix typo in gcloud alias

- config/types/disk.go
- config/v2_0/types/disk.go
- config/v2_1/types/disk.go
The spec allows specifying number 0 for "next available partition
number", so it should be valid for multiple partitions on the same disk
to specify it. Fix validation to not consider number 0 when checking for
collisions.
> config/types: fix partition number validation

- internal/oem/oem.go
- internal/providers/cloudstack/cloudstack.go
CloudStack config-drive support
Co-Authored-By: Sigert Goeminne <sigert.goeminne@nuagenetworks.net>
Upstream PR: https://github.com/apache/cloudstack/pull/2097
Design document: https://cwiki.apache.org/confluence/display/CLOUDSTACK/Using+ConfigDrive+for+Metadata%2C+Userdata+and+Password
> providers: add support for cloudstack config-drive

- internal/oem/oem.go
Bind-mounting the `docker` binary doesn't work with the torcx docker package, and `google/cloud-sdk` may ship its own docker binary in future.
For https://github.com/coreos/bugs/issues/2112.
> oem: don't bind-mount docker into Google Cloud SDK container

- internal/providers/cloudstack/cloudstack.go
The original implementation for CloudStack left out support for network
metadata. This adds it. Note that the DHCP server's IP address is being
read from the networkd leases file (which we aren't supposed to parse).
This is safe for now, but should eventually migrate to a public API.
> providers/cloudstack: support for network metadata

- internal/exec/util/passwd.go
I haven't tested this yet, but it looks obvious.  Was there a reason for this behavior?
> internal/exec/util/passwd: Drop GECOS quotes

- doc/development.md
- tests/blackbox_test.go
- tests/filesystem.go
- tests/positive/storage/creation.go
- tests/types/types.go
> tests: use partitioned loop devices instead of kpartx

- tests/blackbox_test.go
- tests/filesystem.go
- tests/positive/storage/creation.go
- tests/positive/storage/reuse_filesystem.go
- tests/types/types.go
Respect `TMPDIR` if supplied, but create a subdirectory under it. This allows the rest of the codebase to create files with fixed names and not have to clean them up.
cc @arithx
> tests: always use private TMPDIR subdirectory

- config/types/config.go
- config/v2_1/types/config.go
Generate warnings when directories or links reference a non-existant filesystem.
> config/types: add fs check for directories / links

- config/validate/astjson/node.go
- config/validate/astnode/astnode.go
- config/validate/validate.go
- config/validate/validate_test.go
When Ignition switched to using a json schema the validation logic
changed slightly to allow Validate<FieldName>() functions to be called
as well. Ignition did not try to get the corrosponding ast node for that
field. This lets Ignition try to get the corrosponding ast node.
> config/validate: report better line/col info

- config/config.go
- config/config_test.go
Fix an issue with config parsing where if a config's version was
indeterminable, it wasn't a cloud config, it wasn't empty, and it wasn't
a script, a generic "invalid version" message was emitted. The solution
is to run the unknown thing through ParseFromLatest to generate parse
errors.
cc @bgilbert 
Fixes https://github.com/coreos/bugs/issues/2115
> config/config.go: parse unknown configs to generate json errors

- NEWS
Two bug fixes were omitted from the v0.19.0 release notes by mistake. Add them to the v0.19.0 NEWS entry.
> news: update v0.19.0 news to included missed fixes

- internal/exec/validate.go
- internal/main.go
Add flag to just validate Ignition configs then exist. Developing
validation logic has either been time consuming (as new images need to
be built) or dangerous due to running ignition locally.
I'm not married to the location `internal/exec/validate.go` but it seemed like the best place considering its an execution path but not a stage.
> main: add validate flag

- .github/tailor.yaml
There isn't any functional change to the rules. This just takes
advantage of new functions to clean up the regex a bit.
> test: update tailor rules

- doc/examples.md
- doc/migrating-configs.md
These examples would result in warnings (and an error in the last one) when they were validated.
> doc: Drop deprecated "create" usage

- config/translate.go
- config/translate_test.go
- config/types/schema.go
- internal/exec/util/passwd.go
schemaTyper had a bug where it would non-deterministically pick names
for types. This is fixed as of schemaTyper commit
`4ea028d9a4060b67eda07b64cf865d567b73df88`. Use the deteministic type
names.
Unfortunately the new names are not as descriptive. Keep the old
function names for the conversion functions because they are more
descriptive.
> config/types: rename PasswdUserGroups to Groups

- doc/development.md
This was missed initially. shadow-utils is needed for commands like useradd.
> doc/development: update dependencies

- doc/development.md
This reverts commit 6b3ba69e66ada8d2c504545287bad89bfa2a2c6c.
tests/stubs/ has stubbed out commands supplied by shadow-utils, it is
not in fact a requirement for testing.
> Revert "doc/development: update dependencies"

- doc/development.md
- internal/distro/distro.go
- internal/exec/engine.go
- internal/oem/oem.go
- internal/providers/system/system.go
- tests/blackbox_test.go
- tests/positive/general/preemption.go
- tests/types/types.go
Add a new "system config dir" (defaulting to `/usr/lib/ignition` in the initramfs) which contains `base.ign` and `default.ign`. Both files are optional. Read `base.ign` instead of `oem.BaseConfig()` and `default.ign` instead of `oem.DefaultUserConfig()`; no longer ship those configs in `oem.go`. This improves the distro-independence of the codebase and allows the OEM configs to be updated independently of an Ignition release.
Also add an optional `user.ign` in the system config dir, which is lower priority than `coreos.config.url` but higher priority than the regular config provider. This allows tools like `coreos-install` to write a user config to disk without also modifying `grub.cfg`.
The idea is for bootengine to mount the OEM partition, copy the three Ignition config files into …
> Stop hardcoding base and default configs in Ignition binary

- .travis.yml
- internal/resource/http.go
The default implementation of the HTTP library in Go doesn't play nicely
with the libc resolver. When resolving a record with multiple records
(round robin DNS), the resolver returns a list of IPs to the HTTP
library, in the order that was returned by libc. This order is defined
by [RFC 6724]. The HTTP library, however, doesn't attempt to use all of
those IPs in the event of a connection error - it only ever uses the
first.
Generally speaking, the order of addresses returned by libc appears to
be random but in reality, [RFC 6724] defines the order. This is
problematic because if a particular address is always first in that
list, it will result in that address receiving an unbalanced amount of
traffic. Ignition should actually use a random resolver to ensure that
the traffic is actually …
> resource/http: prefer the go resolver over libc

- doc/configuration-v2_0.md
- doc/configuration-v2_1.md
- doc/configuration-v2_2-experimental.md
- tests/blackbox_test.go
- tests/filesystem.go
- tests/positive/storage/creation.go
- tests/positive/storage/reuse_filesystem.go
- tests/types/types.go
- tests/validator.go
Update the docs on `storage.disks.partitions.size` and `storage.disks.partitions.start` to be accurate.
Add blackbox test for specifying start and size 0.
Update blackbox test logic to handle exact disk/partition sizes.
> Update start/size docs, add tests

- .travis.yml
- build
- test
- tests/filesystem.go
Minor quality of life fixes: don't compile things we don't need to and log Ignition's PID when running in a BB test so you can look at the logs more easily.
Depends on https://github.com/coreos/ignition/pull/481
> Improve tests

- config/translate.go
- config/translate_test.go
- config/types/schema.go
- config/types/unit.go
- config/types/unit_test.go
- doc/configuration-v2_2-experimental.md
- internal/exec/stages/files/files.go
- internal/exec/util/path.go
- internal/exec/util/unit.go
- schema/ignition.json
Systemd v232 [added networkd drop-ins](https://github.com/systemd/systemd/blob/5e0aff564c86838e08c4b1bdd8df182d233a36b8/NEWS#L1204-L1205).
This PR adds a "dropins" section to networkd, and includes relevant renaming for the systemd dropins (since they're not the only dropins any more).
Tested with the following config:
```json
{
"ignition": {
"version": "2.2.0-experimental",
"config": {}
},
"storage": {},
"systemd": {},
"networkd": {
"units": [
{
"name": "zz-default.network",
"dropins": [
{
"name": "disable-dhcp.conf",
"contents": "[Network]\nDHCP=no"
}
]
}
]
},
"passwd": {}
}
```
Fixes https://github.com/coreos/bugs/issues/2250
> Network dropins

- .travis.yml
- build
- build_blackbox_tests
- doc/development.md
- test
Add a script to configure the helper programs paths to those found on
the host system. Source this script when running build with
HELPERS=HOST.
> tests: make running bb tests locally easier

- .github/tailor.yaml
Sometimes a scope is a single file, allow periods in scope so filenames
can be used as a scope.
> .github/tailor.yaml: allow periods in scope

- config/append.go
- config/append_test.go
- internal/exec/engine.go
- tests/negative/timeouts/timeouts.go
Changes Ignition to apply config timeouts while resolving config chains, instead of after the config chains are resolved.
Changes the append logic to keep old values when the new value is nil (the motivator being that one config's timeouts could be overriden by a new config that didn't set any timeouts).
Adds a few blackbox tests to make sure this all works as expected.
> Apply config timeouts when resolving config chains

- config/types/partition.go
- config/types/partition_test.go
- config/v2_0/types/partition.go
- config/v2_1/types/partition.go
- config/v2_1/types/partition_test.go
`sgdisk` does not support creating labels with colons; it silently truncates the label to only the characters before the colon. Disallow trying to create labels with colons.
> Disallow colons in partition labels

- internal/providers/ec2/ec2.go
- internal/resource/url.go
This is an (untested) attempt to add support for autodetecting the current machine region when using the s3 protocol for replacing ignition config. Hence adding support for all aws partitions, this is needed by the tectonic installer in order to deploy into GovCloud/China partitions (aws-us-gov, aws-cn)
Fix https://github.com/coreos/bugs/issues/2216
> add support for s3 all aws partitions

- tests/negative/networkd/dropins.go
- tests/positive/networkd/dropins.go
- tests/registry/registry.go
Add tests around networkd drop-ins after support was added in #482.
Fixes https://github.com/coreos/bugs/issues/2309
> tests/networkd: add tests for drop-ins

- config/translate.go
- config/translate_test.go
- config/types/directory.go
- config/types/file.go
- config/types/mode.go
- config/types/mode_test.go
- config/types/schema.go
- internal/exec/stages/files/files.go
- internal/exec/util/file.go
- schema/ignition.json
Emit warnings if a config doesn't specify file modes.
Related to https://github.com/coreos/container-linux-config-transpiler/pull/134.
Based on a pre-holiday conversation with @ajeddeloh and @bgilbert
> default file mode warnings

- internal/resource/http.go
Info level logs show up in the console, so change logs related to http
fetching retries info level instead of debug. If these messages don't
appear in the console, Ignition may appear to hang.
Fixes https://github.com/coreos/bugs/issues/2206
> internal/resource/http.go: make retry logging info level

- config/types/schema.go
- doc/configuration-v2_2-experimental.md
- internal/exec/stages/files/files.go
- internal/exec/util/file.go
- schema/ignition.json
- tests/negative/files/preexisting_nodes.go
- tests/positive/files/directory.go
- tests/positive/files/file.go
When creating a filesystem node (i.e. file/dir/link) sometimes a preexisting node will cause this to fail. This PR adds a `force` flag to the `node` object to delete preexisting nodes when set.
This PR was prompted by @ethernetdan who wanted to set the timezone via:
```
{
"ignition": { "version": "2.1.0" },
"storage": {
"links": [{
"filesystem": "root",
"path": "/etc/localtime",
"target": "/usr/share/zoneinfo/US/Pacific"
}]
}
}
```
which failed via:
```
[    9.364136] ignition[416]: files: createFilesystemsFiles: createFiles: op(a): [failed]   writing link "/etc/localtime" -> "/usr/share/zoneinfo/US/Arizona": symlink /usr/share/zoneinfo/US/Arizona /sysroot/etc/localtime: file exists
```
Fixes https://github.com/coreos/bugs/issues/2311
> Add force flag to node creation

- NEWS
I made a new branch on the main repo, `v0.20.1`, to represent the patch release. It contains one commit on top of `v0.20.0`, which is the cherry-picked commit that fixes S3 object retrieval when running in non-default AWS partitions.
This PR is the update to the NEWS file on that branch for the patch release.
> news: add news for v0.20.1

- tests/blackbox_test.go
- tests/negative/general/config.go
- tests/negative/general/invalid_version.go
- tests/negative/networkd/dropins.go
- tests/negative/regression/filesystem.go
- tests/negative/storage/no_device.go
- tests/negative/storage/no_filesystem_type.go
- tests/negative/timeouts/timeouts.go
- tests/positive/general/general.go
- tests/positive/general/preemption.go
- tests/types/types.go
There was a class of negative tests in the blackbox tests that had invalid configs, but passed because we were expecting Ignition to fail. This adds a check to manually validate configs we expect to be correct before running Ignition.
> blackbox: validate configs that we expect to be valid

- .github/tailor.yaml
- tests/filesystem.go
- tests/negative/files/preexisting_nodes.go
- tests/positive/files/directory.go
- tests/types/types.go
- tests/validator.go
Fixes a few things I noticed in the blackbox tests:
- do a `strings.Contains` on Ignition's output for `panic`, fail if it's found. Negative tests are expecting Ignition to exit with a non-zero exit code, so panics were unnoticed.
- create directories and links specified in the input disks of the tests
- store the mode of files and directories as an int
These fixes are required for the blackbox tests in the append flag PR to pass.
> Blackbox test improvements

- .github/tailor.yaml
- config/v2_1/append.go
- config/v2_1/append_test.go
The config/v2_1 package should only work with 2.1.0 configs, so change
the import from config/types to config/v2_1/types.
Ignition-the-binary translates all configs to 2.2.0-experimental before appending them, so this change is only for the benefit of Ignition-the-library consumers.
Noticed by @dghubble.
> config/v2_1: use config/v2_1/types in append.go

- config/translate.go
- config/translate_test.go
- config/types/file.go
- config/types/schema.go
- doc/configuration-v2_2-experimental.md
- internal/exec/stages/files/files.go
- internal/exec/util/file.go
- internal/exec/util/unit.go
- schema/ignition.json
- tests/negative/files/append.go
- tests/positive/files/file.go
Adds an append flag to the file object. When set to true, the contents referenced will be appended to the given file, instead of replacing it. If the file doesn't exist, it will be created. If the mode or ownership is unspecified in the Ignition config, the mode and ownership on the file being appended to will not be changed.
What this looks like:
```
{
"ignition": { "version": "2.2.0-experimental" },
"storage": {
"files": [{
"filesystem": "root",
"path": "/foo/bar",
"contents": { "source": "data:,hello%20world%0A" },
"append": true
}]
}
}
```
Fixes https://github.com/coreos/bugs/issues/1997
> Append to files

- config/types/schema.go
- doc/configuration-v2_2-experimental.md
- internal/exec/stages/disks/disks.go
- schema/ignition.json
Allows users to provide additional arguments to `mdadm`. Not sure if there's any validation we can do on the options field.
Still needs to be tested.
> Add field for user-provided raid options

- doc/supported-platforms.md
@dghubble noticed that our list of supported schemes isn't complete on one of our docs pages.
> doc/supported-platforms: add supported schemes for `coreos.config.url`

- glide.lock
- glide.yaml
- vendor/github.com/coreos/go-systemd/NOTICE
- vendor/github.com/coreos/go-systemd/dbus/dbus.go
- vendor/github.com/coreos/go-systemd/dbus/methods.go
- vendor/github.com/coreos/go-systemd/dbus/subscription.go
The new go-systemd release includes fixes for a few crashes and other
such nasty behavior, so update the version vendored by Ignition to the
new release.
> vendor: update go-systemd to v16

- tests/negative/security/tls.go
The Golang HTTP server automatically logs to stdout if no error logger is
present. This causes TLS handshake errors to be spewed out during negative test
runs. Adds a custom logger to the negative tests HTTPServer which uses an
`ioutil.Discard` writer.
> tests/negative/security/tls: disable tls handshake error logging

- NEWS
v0.22.0 marks the `2.2.0` spec as stable, and creates a new `2.3.0-experimental` spec. `2.2.0-experimental` specs will no longer be accepted.
This PR also fixes a typo in the release notes for v0.21.0.
> news: add news for v0.22.0

- README.md
Since we're now releasing binaries for ignition-validate, I think we should probably tell users in the README that they're available. I tossed in a mention of the online validator while I was there.
> README: add sentence about ignition-validate and coreos.com/validate

- NEWS
This release shouldn't have any user-facing impacts, so the release notes are only calling out the changes that impact consumers of Ignition as a library.
> news: add news for v0.23.0

- Makefile
- config/v2_0/types/unit.go
- config/v2_1/types/unit.go
- config/v2_2/types/unit.go
- config/v2_3_experimental/types/unit.go
strings.NewReader just uses a couple ints to keep track of where it's
reading whereas the bytes variant copies all of the contents of the
string.
This is a microoptimization, but I think it's also mildly cleaner code.
I double checked my understanding that strings.NewReader doesn't allocate so much in the [playground](https://play.golang.org/p/ncF4-yYei0h). In reality, units are pretty small so the difference will be minuscule.
>  config: avoid some buffer allocs

- build
- build_releases
Currently a source checkout requires extra work to build the artifacts. Example:
```
[steve@qward ignition-0.23.0] $ ./build
Using version from git...
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
Overriding doesn't work out of the box:
```
[steve@qward ignition-0.23.0]$ VERSION=1 ./build
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
This change allows for ``VERSION`` to be overridden in both ``build`` and ``build_releases`` via:
```
[steve@qward ignition-0.23.0] $ VERSION=0.23.0 ./build
```
If ``VERSION`` is not set then ``VERSION`` defaults to what it is able to get via ``git`` (or fails as it …
> build and build_releases VERSION override

- build_blackbox_tests
- tests/filesystem.go
The `build_blackbox_tests` script started failing to put the helper stubs in `bin/${ARCH}` (it would put them in `./gopath/bin/id-stub`), which would cause the blackbox tests to fail if run on a machine they hadn't run on before. This PR fixes that, and changes a thing in the tests to emit more useful errors.
Based on some non-exhaustive investigation this regression may have been introduced in [this commit](https://github.com/coreos/ignition/commit/ff6985977ab14565e715a4cb33d3cbc866061083), but I didn't figure out why that commit caused this.
> Fix blackbox tests

- config/validate/validate.go
Highlights weren't being added to reports that came from `Validate` functions:
```
error at line 5, column 37
invalid systemd unit extension
``` 
This makes it so that they are added:
```
error at line 5, column 37
4:     "units": [{
5:       "name": "systemd-networkd.foo"
^
invalid systemd unit extension
```
Depends on https://github.com/coreos/ignition/pull/526, will rebase on that once it merges.
> add highlights to reports coming from Validate and ValidateFoo functions

- config/shared/errors/errors.go
- config/v1/config.go
- config/v1/config_test.go
- config/v2_0/config_test.go
- config/v2_1/config_test.go
- config/v2_2/config_test.go
- config/v2_3_experimental/config_test.go
It returned `ErrVersion` until 530602f, when it started returning `ErrInvalid`.  The latter makes it impossible to distinguish unrecognized versions from other errors, which is important when trying to locate the oldest parser that can read a config.  Switch to `ErrUnknownVersion` for consistency with the other parsers.
> config: have Parse return ErrUnknownVersion if version is bad

- doc/configuration-v2_0.md
- doc/configuration-v2_1.md
- doc/configuration-v2_2.md
- doc/configuration-v2_3-experimental.md
I just noticed there's an option in Ignition for user groups that was entire undocumented. Language copied from the same flag under the user object.
> doc: document system option in groups

- tests/blackbox_test.go
A programming error resulted in a value that was nil being returned
instead of the correct value when the files stage failed in a blackbox
test.
> tests: return correct error value for failed files stage

- internal/resource/url.go
- tests/blackbox_test.go
- tests/filesystem.go
- tests/positive/storage/reformat_filesystem.go
This modifies the black box tests so that they run in parallel. The default amount of parallelism is 4 tests at once. This can be changed with the `-test.parallel` flag. The default settings result in a roughly 3x speedup on my laptop.
> tests: run tests in parallel, fixes for parallel tests

- internal/exec/util/file.go
- internal/resource/url.go
A programming error resulted in an extraneous temporary file being left
on disk when a file is appended to.
Also add a comment in internal/resource which hopefully justifies why a
temporary file is used during file appending.
Fixes https://github.com/coreos/bugs/issues/2420
I manually tested this, the bb tests aren't currently expressive enough to write a test for "there shouldn't be extra files with unknown names here".
> internal: don't leave a temporary file when appending

- tests/positive/filesystems/reformat_filesystem.go
Distinguishes the version that the reformat filesystem tests use to
remove duplicate test names.
> tests: rename duplicate tests

- internal/resource/http.go
- internal/resource/url.go
Contexts for HTTP requests should not be cancelled until after the HTTP
body has been successfully read, or errors can be encountered.
Fixes https://github.com/coreos/bugs/issues/2435
I think
> internal: don't cancel http contexts until the body has been read

- internal/exec/engine.go
- internal/main.go
It's cleaner to store the fetcher instance in the Engine struct instead
of passing it around everywhere.
> internal: store the fetcher in the Engine struct

- internal/exec/engine.go
- internal/exec/util/passwd.go
- internal/log/log.go
This resolves issue [#2441](https://github.com/coreos/bugs/issues/2441):
For tests `Preemption_with_default_config` and `Empty_Userdata`: 
`Crit()` was changed to `Warning()` in `engine.go`
As for the `Adding_users` test:
Please look at commit [6820...](https://github.com/coreos/ignition/pull/558/commits/68204430d9125bb87fb023327a182e4969210264) and do let me know how I can improve this statement.
> Critical level logs

- tests/filesystem.go
Adds detection for `CRITICAL` log messages emitted by Ignition.
Blocked by https://github.com/coreos/bugs/issues/2441
> tests: fail when Ignition emits CRITICAL logs

- NEWS
Add news for branched releases
Add news for 0.26.0
> Add news for 0.26.0, 0.25.1, 0.24.1

- tests/positive/filesystems/reuse_filesystem.go
There appears to be some btrfs bug which causes this test to flake.
Ignition is doing the right thing in that case, so switch to xfs so we
still test the functionality but don't encounter the flake.
> tests/reuse-existing-fs: use xfs not btrfs

- build
When building the Ignition binary, produce a position independent executable as per recommendations from the [Fedora packaging guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines#PIE).
I also attempted to produce PIE binaries for the `ignition-validate` binary, but this caused [compilation issues](https://gist.github.com/dgonyeo/5e2bae336541446b8dc4b4f499a1eaf4) and as per the guidelines I believe PIE is only recommended for `ignition-validate`, not required.
cc @ashcrow and @dustymabe, since this relates to https://github.com/ashcrow/ignition-specs
> build: produce position independent executable for ignition

- tests/filesystem.go
The suggested `udevadm settle` to wait for loop devices is better than
a sleep statement.
Fixes #2450
> tests/filesystems: use proper device waits

- .github/tailor.yaml
We already allow single quotes, adds double quotes.
> tailor: allow ``(") & (`)`` in titles

- internal/exec/util/user_group_lookup.c
rpmlint finds this: `E: missing-call-to-chdir-with-chroot /usr/bin/ignition`
and in our case I don't think it'll matter as nothing is reading from the
current working directory, but it's definitely best practice.
(Although I would say this code should be replaced by forking a container
process off in the target (e.g. via bwrap) and talking to it over IPC)
> user-group: Add chdir("/") after chroot()

- internal/exec/stages/disks/disks.go
- tests/blackbox_test.go
- tests/types/types.go
Refactored the code that identifies and replaces UUID variables so that:
1) It is not unnecessarily ran on each loop of test.In in outer()
2) outer() is not as long
Jira card: https://projects.engineering.redhat.com/browse/COREOS-253
> tests: refactor uuid replacement code

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
This will cause GitHub's "New issue" button to redirect to a template chooser.  For a sense of the UX, see [here](https://github.com/bgilbert/bugs/issues).
> github: add issue reporting templates

- README.md
This change updates the bug report location to point at [this repositories issues](https://github.com/coreos/ignition/issues).
> README.md: Update bug tracking location

- doc/configuration-v2_0.md
- doc/configuration-v2_1.md
The previous note in the v2.0 spec pointed at v2.1.  That made sense when it landed in 94d4a60f (#400).  But since 4e88b931 (#510) cut v2.2, we should be pointing at v2.2 instead.
> doc: Mention spec v2.2 as the latest stable version

- config/shared/errors/errors.go
- internal/exec/engine.go
- internal/exec/stages/disks/disks.go
- internal/exec/stages/files/files.go
- internal/exec/stages/stages.go
- internal/main.go
- internal/oem/oem.go
- internal/providers/packet/packet.go
- internal/providers/providers.go
- internal/resource/url.go
This references issue [#2444](https://github.com/coreos/bugs/issues/2444).
The ./ignition build works when it is sent to a Packet instance. 
However, has trouble logging via ssh when an image with the changes in igntion is booted onto an instance. I roughly know what is causing this problem. 
The commits in the PR are numerous but I will eventually squash it into one commit after removing the debug prints some from logger.Info() and fmt.Println(). So I'm ignoring the tailor check for now, until I 
have one squashed commit.
> Status Report for Packet Instance

- internal/exec/stages/files/filesystemEntries.go
Use a stable sort so directories from appended configs are always
created after directories from the appendee.
> stages/files: use stable sort for directories

- build_blackbox_tests
- internal/distro/distro.go
- internal/exec/stages/files/files.go
- internal/exec/stages/files/filesystemEntries.go
- internal/exec/stages/files/passwd.go
- internal/exec/stages/files/units.go
- internal/exec/util/file.go
- internal/exec/util/path.go
- internal/exec/util/unit.go
This makes the files stage immediately load the SELinux policy from the
target sysroot to ensure that files it creates will be properly labeled.
(Marking as WIP because this is untested on CL). Would be nice if someone already set up could try this (without [the workaround](https://github.com/coreos/ignition/blob/a611d96e5c1179e7b93b93afe53548ae7d1d1b87/doc/operator-notes.md#selinux)) and confirm that files are labeled correctly.
> stages/files: relabel files for SELinux after boot

- NEWS
Shout out to @arithx for helping drafting these notes.
> Add news for 0.27.0

- tests/negative/files/missing_file.go
- tests/negative/files/preexisting_nodes.go
- tests/negative/filesystems/no_device.go
- tests/negative/filesystems/no_filesystem_type.go
- tests/negative/general/config.go
- tests/negative/partitions/simple.go
- tests/negative/partitions/zeroes.go
- tests/negative/security/tls.go
- tests/positive/files/file.go
- tests/positive/files/remote.go
- tests/positive/general/general.go
- tests/positive/networkd/create_unit.go
- tests/positive/oem/oem.go
- tests/positive/partitions/zeros.go
- tests/positive/security/tls.go
- tests/positive/timeouts/timeouts.go
Updates the configMinVersion to reflect the lowest compatible config version.
** Opened this PR so I can run the BB test on jenkins since my system has mounting/unmounting issues
> tests/bb: update configMinVersion to reflect lowest compatible config version

- internal/exec/stages/files/passwd.go
For the same reasons that `/home` is in that list. The difference is
that the "root" user will always exist, but we might be touching and
creating files there. For example, we might be adding an
`.ssh/authorized_keys`, which will need to be relabeled.
---
Marking as WIP for now until I sanity check this solves all issues we've been seeing.
> stages/files: also relabel /root home dir

- internal/exec/stages/disks/filesystems.go
Do not construct string slices only to immediately destruct them.
> stages/filesystems: simplify code

- .travis.yml
- internal/exec/util/blkid.c
- internal/exec/util/blkid.go
- internal/exec/util/blkid.h
libblkid always assumes sectors are 512 bytes, regardless of actual
size. Add detection for otherly sized sectors (e.g. 4k) and translate
the 512 byte values to logical-sector-sized values.
> exec/util: handle 4k sectors correctly

- build_blackbox_tests
- tests/blackbox_test.go
- tests/filesystem.go
- tests/validator.go
This uses a global context as the root of all the individual test contexts that gets canceled on ^C. All Ignition processes and setup processes use this context. All cleanup code does not. This means cleanup code still runs when you ^C the tests.
> Cleanup tests and make them killable

- doc/development.md
The default value for test.parallel in the go test runner is dependent
on the number of cores of the host system. The Ignition blackbox tests
are still currently racey with higher parallelism, so default it to a
lower, safer number.
> doc/development: update blackbox test instructions to low parallelism

- doc/development.md
- tests/blackbox_test.go
- tests/filesystem.go
umount sometimes returns exit status 32 even when successful. Detect and
work around this case.
Increase the timeout to 60 seconds since running in parallel can cause
the tests to slow down and time out.
> tests: workaround umount issues

- glide.lock
- glide.yaml
- tests/blackbox_test.go
We use glide-vc anyway, so there's not really any point in using
subpackages. We never specify different versions for different
subpackages so they're just there to be confusing.
> glide.*: remove subpackages

- internal/exec/stages/files/files.go
- internal/exec/stages/files/passwd.go
The behaviour of how `restorecon` handles symlinks changed between RHCOS
and FCOS. More specifically, `restorecon` will follow symlinks that are
part of a given path, but not if the target path is a symlink itself.
On OSTree-based systems, `/home` and `/root` are just symlinks, so the
newer `restorecon` wasn't actually relabeling anything under there.
Add the real paths to the list of dirs to relabel and add `-i` so that
it's not a fatal error on non-OSTree-based systems.
Closes: coreos/fedora-coreos-config#2
> stages/files: relabel /var/home and /var/roothome

- .travis.yml
- build
- internal/exec/util/passwd.go
- internal/main.go
- internal/resource/url.go
Go's caching (on by default with 1.11, enforced in 1.12) does not handle
cgo at all. Update build to always clean so it will always pick up
changes to cgo code.
> build: clean before building

- Makefile
- glide.lock
- glide.yaml
Switch from using raw commit hashes to tags. This makes it much more
human readable. Also drop a transient dep that did not need to be in the
glide.yaml file. This does not update any of the dependencies.
> glide: switch to tags where we can

- internal/exec/stages/disks/disks.go
There is no need to settle when there was nothing in the disks stage.
The old check did not take into account that the disks stage has an
implicit filesystem in the base config so there is at minimum 1
filesystem.
> stages/disks: fix extraneous udevadm settle

- internal/exec/stages/files/files.go
This is a workaround for an inherent issue with the current relabeling
approach (see #635). `systemd-sysctl.service` is definitely one of those
early services that have a high probability of reading files from `/etc`
before it's relabeled.
They're both pulled in by `sysinit.target`, but
`ignition-relabel.service` has an additional `After=local-fs.target`
which makes it likelier to run later (also see #635 about that). So for
now, let's just hack around this by making sure `systemd-sysctl` runs
after us.
> stages/files: relabel files before systemd-sysctl

- .github/ISSUE_TEMPLATE/release-checklist.md
Avoid the extra top-level directory by moving the release checklist into `.github/ISSUE_TEMPLATE/`.  Drop YAML front matter so the checklist won't show up in the issue template chooser.
> release-checklist: move to .github and drop front matter

- doc/configuration-v2_2.md
Some people might reasonably expect them to apply system-wide.
> config: Clarify semantics around certs

- internal/providers/packet/packet.go
Right now we're reporting successful provisioning in Ignition after each
stage. This can cause issues where the disks stage might pass sending a
successful configuration followed by the files stage failing. Instead
send a running status and allow the [phone-home service](https://github.com/coreos/coreos-overlay/blob/master/coreos-base/oem-packet/files/units/packet-phone-home.service) to report
success.
Closes #651
> internal/providers/packet: don't send success to packet from Ignition

- internal/earlyrand/earlyrand.go
- internal/resource/http.go
- internal/resource/url.go
This introduces a plain `/dev/urandom` reader as a non-secure
early-boot source of entropy for TLS client.
Closes: #645
> internal/resource: use /dev/urandom for early-boot TLS

- tests/positive/partitions/complex-mb.go
Do not hardcode 2.3.0 in the config. Set minversion to 2.3.0 like the
other tests do.
> tests/partitioning: add minversion to complex mb

- tests/blackbox_test.go
- tests/register/register.go
- tests/types/types.go
Don't replace version numbers when running with -test.short. This cuts
the test case down from 505 -> 137 as of this commit.
> test: skip backward compat tests with -test.short

- internal/exec/stages/disks/filesystems.go
- tests/filesystem.go
- tests/positive/filesystems/creation.go
Fixes #681. It caps the concurrency at GOMAXPROCS.
There are a couple smaller changes in here too, one necessary and one useful:
* I added a flag to allow passing a pattern specifying which blackbox tests will be run, since `test.run` only sees the overall single test method.
* I ensured that In partitions always have a Device and MountPath set, even if they're blank. That way you can take a blank partition and format it.
> Parallel filesystem creation

- tests/positive/timeouts/timeouts.go
Fixes error:
fatal error: concurrent map writes
goroutine 17546 [running]:
runtime.throw(0x98c3c4, 0x15)
/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc001222c60 sp=0xc001222c30 pc=0x42eee2
runtime.mapassign_faststr(0x8f0540, 0xc0001e91d0, 0xc000df6584, 0x13, 0xfc3800)
/usr/local/go/src/runtime/map_faststr.go:199 +0x3da fp=0xc001222cc8 sp=0xc001222c60 pc=0x41550a
github.com/coreos/ignition/tests/positive/timeouts.glob..func2(0xa3c820, 0xc0005da0e0, 0xc000334200)
/usr/src/myapp/gopath/src/github.com/coreos/ignition/tests/positive/timeouts/timeouts.go:48 +0xd3 fp=0xc001222d20 sp=0xc001222cc8 pc=0x873713
net/http.HandlerFunc.ServeHTTP(0x9af250, 0xa3c820, 0xc0005da0e0, 0xc000334200)
/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc001222d48 sp=0xc001222d20 pc=0x6d78e4
[...]
> tests/timeouts: fix concurrency panic

- tests/positive/timeouts/timeouts.go
Fixes error:
fatal error: concurrent map writes
goroutine 17546 [running]:
runtime.throw(0x98c3c4, 0x15)
/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc001222c60 sp=0xc001222c30 pc=0x42eee2
runtime.mapassign_faststr(0x8f0540, 0xc0001e91d0, 0xc000df6584, 0x13, 0xfc3800)
/usr/local/go/src/runtime/map_faststr.go:199 +0x3da fp=0xc001222cc8 sp=0xc001222c60 pc=0x41550a
github.com/coreos/ignition/tests/positive/timeouts.glob..func2(0xa3c820, 0xc0005da0e0, 0xc000334200)
/usr/src/myapp/gopath/src/github.com/coreos/ignition/tests/positive/timeouts/timeouts.go:48 +0xd3 fp=0xc001222d20 sp=0xc001222cc8 pc=0x873713
net/http.HandlerFunc.ServeHTTP(0x9af250, 0xa3c820, 0xc0005da0e0, 0xc000334200)
/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc001222d48 sp=0xc001222d20 pc=0x6d78e4
[...]
(cherry …
> tests/timeouts: fix concurrency panic for spec2x

- .travis.yml
The previous min version was 1.8.x because we weren't sure what would be
available for use in building RHCOS. Turns out 1.10.x is fine, so lets
bump this.
see https://github.com/coreos/ignition/pull/626#discussion_r214266901 for old discussion
> travis: bump min go version to 1.10.x

- tests/types/types.go
Initially, it took some time to understand these (was clear after
reading `tests/blackbox_tests.go`). Adding a few comments as hints,
which may be useful when first reading the code.
> tests/types: add comments on some members of Test

- internal/exec/engine.go
- internal/providers/system/system.go
- tests/positive/general/preemption.go
Removes functionality that checks for a file at
/usr/lib/ignition/default.ign. This was used to enable coreos-cloudinit,
which is no longer supported with Ignition 3.0.0.
Closes: #668
---
Manually tested with a CL image on QEMU.  Running `journalctl --identifier=ignition --all` indicates `default.ign` is no longer looked for.
WIP - still updating blackbox tests that fail due to this change (`tests/positive/general/preemption.go`).
> internal/*: Drop support for default.ign config files

- internal/exec/engine.go
- internal/providers/util/config.go
Do not log configs; instead log a hash of them. This ensures if a config
contains secrets, it does not log them to the journal.
Will PR a backport to `spec2x` after this merges
> internal/exec: log hashes of configs not configs

- doc/development.md
- tests/types/types.go
This functionality was removed in #734 but the type definition itself
was missed.
> tests: drop OEMLookaside type

- config/shared/errors/errors.go
- config/v3_0_experimental/types/directory.go
- config/v3_0_experimental/types/file.go
- doc/configuration-v3_0-experimental.md
- internal/exec/stages/files/filesystemEntries.go
- internal/exec/util/file.go
- tests/positive/files/directory.go
- tests/positive/files/file.go
- tests/validator.go
Creates files and directories with default permissions 0644 and 0755
respectively, when "mode" is not specified in the Ignition config for
the file/directory. This also updates the warning message printed when
the default permissions are applied.
Closes: #582
---
Blackbox tests should work. Did not get to verifying with a full `kola run` with this yet.
When trying to verify the changes, I was having problems running `./coreos_production_qemu.sh -i cfg.ign -- -nographic` (Ignition logs showed the error `not a config(empty)`). This was before I rebased onto a more recent master, so I need to check if the same problem occurs on this branch.
> internal/exec: use nonzero default file permissions 

- internal/exec/engine.go
- internal/main.go
- internal/platform/name.go
- internal/platform/platform.go
- internal/providers/noop/noop.go
- tests/filesystem.go
Switches from using the OEM terminology (a remnant of ChromiumOS) to
platform.
Fixes #684
> *: drop OEM terminology

- internal/platform/platform.go
Add oem for use by bare metal. It does nothing. This allows setting the
oem-id to "metal" for other projects and having Ignition not fail.
> oem: add metal oem

- build_blackbox_tests
- doc/development.md
- internal/distro/distro.go
- tests/filesystem.go
Switch to relative paths for the binaries defined in the `distro`
package while still allowing them to be overridden via build flags.
Fixes #648
> internal/distro: use relative paths

- internal/exec/util/passwd.go
Renames the written fragment in ~/.ssh/authorized_keys.d/ from
"coreos-ignition" to "ignition". This is to have a more
distro-independent identifier.
Fixes: #710 
---
Tested this change in FCOS, and confirmed the `ignition` fragment gets written with the keys given in the Ignition config `"sshAuthorizedKeys"`.
```
$ ls ~/.ssh/authorized_keys.d/ignition -l
-rw-------. 1 core core 424 Feb 26 19:48 /var/home/core/.ssh/authorized_keys.d/ignition
```
> exec/util/passwd: rename authorized_keys.d fragment to "ignition"

- internal/exec/stages/mount/mount.go
- internal/exec/util/util.go
- tests/negative/filesystems/symlinks.go
We can't determine the correct order to mount if we allow this. Also systemd mount units also disallow this, so there's some precedent.
> Disallow mounting filesystem entries via symlinks

- internal/exec/util/passwd.go
- tests/types/types.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- internal/providers/cmdline/cmdline.go
- internal/providers/vmware/vmware_amd64.go
This is backwards compatibility work for spec2x following the changes
made in #663 to make options more distribution neutral.
ref: https://github.com/coreos/ignition/pull/663
> spec2x: support coreos.config.* and ignition.config.*

- doc/configuration-v3_0-experimental.md
- internal/exec/util/file.go
- tests/negative/files/preexisting_nodes.go
- tests/positive/files/file.go
- tests/positive/files/link.go
- tests/positive/general/preemption.go
Need to verify the changes after passing the Ignition config to an OS image. Blackbox tests should work.
Code should be ready for a look - the main change was making `Node.Overwrite` a `bool` instead of `*bool` to use the zero Go value as the `false` default. An alternative could be allocating/setting `*n.Overwrite = false` when `n.Overwrite == nil`, but it doesn't seem like the "unset" case where `n.Overwrite == nil` needs handling now.
Resolves: #604
> Default file.overwrite config option to false 

- internal/exec/stages/files/passwd.go
Those get touched by `useradd` and so we need relabeling if we added any
users or groups.
Closes: #762
> stages/files: Also relabel subuid/subgid files

- doc/operator-notes.md
- doc/supported-platforms.md
- internal/platform/platform.go
- internal/providers/aws/aws.go
- internal/providers/gcp/gcp.go
- internal/resource/url.go
Consistently use the name of the cloud platform rather than of its compute service.
Temporarily accept `ec2` as a compatibility alias for `aws` to ease migration.
Not for backport to `spec2x`.
https://github.com/coreos/fedora-coreos-tracker/issues/162
> *: rename ec2 -> aws and gce -> gcp

- internal/exec/stages/files/passwd.go
Those get touched by `useradd` and so we need relabeling if we added any
users or groups.
Closes: #762 
(Backport of #764. Needed for `coreos-useradd-core.service` to work.)
> spec2x: stages/files: Also relabel subuid/subgid files

- internal/exec/stages/files/filesystemEntries.go
Minor regression from the recent creation ordering rework. We were
feeding `/sysroot/...` paths to `restorecon`. Let's make sure that (1)
the prefix is there on all the paths we create, and (2) we trim off the
prefix of the final path we queue for relabeling.
> stages/files: fix relabel path to be relative to sysroot

- NEWS
Depends on https://github.com/coreos/ignition/pull/772
> News 2.0.0

- doc/getting-started.md
Just a small change to fix a link to a file that was recently renamed
> Fix configspec link to remove `-experimental` in docs

- config/shared/errors/errors.go
- config/util/helpers.go
- config/v3_0/types/file.go
- config/v3_0/types/file_test.go
- doc/configuration-v3_0.md
- internal/exec/stages/files/filesystemEntries.go
- internal/exec/util/blkid.go
- internal/exec/util/file.go
- tests/positive/files/link.go
Disallow setting storage.files.overwrite = true when
storage.files.contents.source is unspecified (nil). If a user wants to
force an file to be empty they should set source to empty string.
> config/v3_0: disallow overwrite and nil source

- internal/platform/platform.go
Probably hold for a bit and then merge before 2.0.0 final.
> platform: drop compat alias for "ec2" platform ID

- doc/supported-platforms.md
- internal/platform/platform.go
PXE is a boot mechanism, not a platform; for example, VMware instances can be PXE-booted.  We now have a `metal` platform ID which behaves the same as PXE (i.e., it's a no-op) and should be used in the common case.
> platform: drop "pxe"

- internal/oem/oem.go
Add oem for use by bare metal. It does nothing. This allows setting the
oem-id to "metal" for other projects and having Ignition not fail.
(cherry picked from commit a060f2a867ae741a9d27506c0565cf581cf0dc95)
> [spec2x] oem: add metal oem

- config/shared/errors/errors.go
- config/v3_0/types/storage.go
- config/v3_0/types/storage_test.go
- config/v3_1_experimental/types/storage.go
- config/v3_1_experimental/types/storage_test.go
- tests/positive/files/link.go
- tests/validator.go
Hardlinks to directories are disallowed, so fail to validate if we know
that we're going to. We could even take this a step further and
blacklist /usr, /etc, /tmp etc but those might be symlinks, which would
be ok, so lets not.
Fixes https://github.com/coreos/ignition/issues/799
> config/*/types/storage: fail on hardlinked dirs

- doc/configuration-v3_0.md
- doc/configuration-v3_1.md
- internal/exec/stages/files/filesystemEntries.go
- internal/exec/util/file.go
- tests/filesystem.go
- tests/negative/files/link.go
- tests/positive/files/link.go
If a link already exists that matches the specified link, do not fail.
WIP needs tests, docs
> stages/files: do not fail if links are correct

- internal/exec/util/device_alias.go
This is useful while running on immutable host system like
Silverblue where root ('/') directory is immutable
Signed-off-by: Sinny Kumari <sinny@redhat.com>
> internal: create dev aliases in /run/ignition/ instead of /

- build
- build_releases
git describe --dirty can fail in some cases without --always. This can
cause travis to fail.
> build*: use --always with git describe

- build
- build_releases
git describe --dirty can fail in some cases without --always. This can
cause travis to fail.
> [spec2x] backport: build*: use --always with git describe

- internal/exec/util/device_alias.go
This is useful while running on immutable host system like
Silverblue where root ('/') directory is immutable
Backported fix in spec2x from master commit 3566041
Signed-off-by: Sinny Kumari <sinny@redhat.com>
> [spec2x] internal: create dev aliases in /run/ignition/ instead of /

- internal/providers/vmware/vmware_amd64.go
Fix a regression where not specifying a config causes ignition to panic
instead of returning a empty config.
> providers/vmware: return nil config if none exists

- doc/getting-started.md
The online validator only validates 2.x config. Remove it.
> doc/getting-started: rm online validator section

- config/v3_0/types/directory.go
- config/v3_0/types/file.go
- config/v3_1_experimental/types/directory.go
- config/v3_1_experimental/types/file.go
Run the node validation as well as the file/directory validation.
Without this the Validate() defined on File and Directory shadow the
definition on Node. It doesn't appear that you can easily isolate them
using reflection either, which is why it should be changed here and not
in vcontext.
> config/v*: run Node.Validate() as well

- .github/ISSUE_TEMPLATE/release-checklist.md
At step to submit the new build(s) to bodhi for 2.x/spec3.x releases.
> release-checklist: add step to submit to bodhi

- internal/exec/stages/mount/mount.go
BUGFIX 
Fixed a logical error- we can't check *fs.Path != "" if it's nil.
> fix check path mount

- internal/resource/url.go
This updates the HTTP "Accept" header to prefer v3.0.0 schema configs.
This is already covered by an explicit step in the development guide,
but it looks like we forgot to update the value when stabilizing
latest schema version.
Ref: https://github.com/coreos/ignition/blob/v2.0.1/doc/development.md#marking-an-experimental-spec-as-stable
> resource/url: update schema version in Accept header

- build_blackbox_tests
If a file to be sourced by a shell script does not contain a slash it will be
searched in PATH first. This is not intended here, the build file in the
local directory is always supposed to used.
Discovered on an openSUSE installation, where `build` is an actual command
used by the Open Build Service - resulting in obscure error messages after
that file was sourced.
> Source build file correctly

- internal/exec/stages/disks/filesystems.go
The message contains nothing useful for users.
> stages/filesystems: drop stray debug print

- doc/supported-platforms.md
Ignition on QEMU uses `fw_cfg`, and the first release supporting
that is 2.4.0.
Ref: https://github.com/qemu/qemu/commit/81b2b81062612e
> doc/supported-platforms: mention qemu version requirements

- go.mod
- go.sum
- internal/exec/engine.go
- vendor/github.com/google/renameio/.travis.yml
- vendor/github.com/google/renameio/CONTRIBUTING.md
- vendor/github.com/google/renameio/LICENSE
- vendor/github.com/google/renameio/README.md
- vendor/github.com/google/renameio/doc.go
- vendor/github.com/google/renameio/go.mod
- vendor/github.com/google/renameio/tempfile.go
- vendor/github.com/google/renameio/writefile.go
- vendor/modules.txt
I just noticed this while reading the code; in practice, the write
should never fail, but we really want to write files atomically
as a general rule.  Particularly in this case as the code may
come back and try to read it again, and if we only did a partial
write we'd just continually fail to read it.
>  engine: Write `/run/ignition.json` atomically

- internal/exec/stages/fetch/fetch.go
- internal/main.go
This stage just triggers the internal code which fetches the
config and writes `/run/ignition.json`; from there it'd be picked
up by later stages the way it was implicitly before.
This is prep for adding support for redeploying the rootfs for
Fedora CoreOS; we need to have a separate process determine
whether the rootfs is being replaced, and if so do a save/restore
across `ignition-disks.service`.
See: https://github.com/coreos/ignition-dracut/pull/107
> Add a `fetch` stage

- internal/exec/stages/files/files.go
- internal/exec/stages/files/passwd.go
- internal/exec/stages/files/units.go
- internal/exec/util/unit.go
Change util to return the path of the symlink it wrote when masking
units. Relabel that symlink.
Fixes https://github.com/coreos/ignition/issues/836
Untested, will mark ready when tested.
Will backport to spec2x after merge
> stages/files: relabel masking symlinks for systemd

- internal/resource/url.go
Found that Ignition was using tmpfiles when fetching to a buffer while starting in on the multipart work. Minor refactoring to clean that up as prep for the multipart stuff.
> Clean up url handling

- Makefile
Following https://github.com/coreos/ignition-dracut/pull/106
add a default `make install` rule that honors `DESTDIR`.  Main
motivation is hacking on ignition in a unified way with ostree,
ignition-dracut and other projects using coreos-assembler.
> build: Add `make install`

- internal/exec/stages/fetch/fetch.go
- internal/main.go
This stage just triggers the internal code which fetches the
config and writes `/run/ignition.json`; from there it'd be picked
up by later stages the way it was implicitly before.
This is prep for adding support for redeploying the rootfs for
Fedora CoreOS; we need to have a separate process determine
whether the rootfs is being replaced, and if so do a save/restore
across `ignition-disks.service`.
See: https://github.com/coreos/ignition-dracut/pull/107
(cherry picked from commit 8926f0f2b2b4397fa18913cde5b7784318f26df8)
> [spec2x] Add a `fetch` stage

- config/v3_0/types/file.go
- config/v3_1_experimental/types/file.go
Don't warn if a file's mode is unset if there are entries in the append
lists. The user is most likely writing to an existing file and does not
want to change mode.
Fixes https://github.com/coreos/ignition/issues/843
> config/v3*: don't warn on unset mode if appending

- .github/ISSUE_TEMPLATE/release-checklist.md
Mantle has now branched and new releases of 0.x.y will need to be
additionally backported to the `cl` branch
> release-checklist: mention mantle cl branch for 0.x.y releases

- internal/platform/platform.go
- internal/providers/aliyun/aliyun.go
Not 100% sure if this would be enough, but it's a start :smile:
See:
- https://www.alibabacloud.com/help/doc-detail/49122.htm
- https://github.com/coreos/ignition/issues/589
> providers/aliyun: Add aliyun

- internal/distro/distro.go
- internal/exec/util/passwd.go
- internal/exec/util/user_group_lookup.c
- internal/exec/util/user_group_lookup.go
There's a few places where we work around not having a convenient chroot helper. Add one and use it in one place as an example.
> Clean up user/group handling

- config/shared/errors/errors.go
- config/v3_1_experimental/types/proxy.go
- config/v3_1_experimental/types/proxy_test.go
Validate that the specified http(s) proxies are in fact valid http(s)
urls.
Closes: https://github.com/coreos/ignition/issues/873
> config/v3_1_exp/types: validate http(s) proxies

- doc/supported-platforms.md
- internal/distro/distro.go
- internal/platform/platform.go
- internal/providers/zvm/zvm.go
Support extracting an Ignition config from the reader device on z/VM platform. It doesn't require network setup in the initramfs, nor waiting for a config-drive that may not show up.
Fixes #810
> providers: add initial zVM hypervisor support

- config/v3_1_experimental/schema/ignition.json
- config/v3_1_experimental/translate/translate.go
- config/v3_1_experimental/types/filesystem.go
- config/v3_1_experimental/types/schema.go
- doc/configuration-v3_1-experimental.md
- internal/exec/stages/mount/mount.go
- tests/negative/filesystems/mount_filesystem.go
- tests/positive/filesystems/mount_filesystem.go
Implements #872, using the _mkfs_ option implementation as a reference.
With this new `mountOptions` entry it is possible to add mount options for each file system, used during the `mount` stage.
> Implement mount option support

- internal/platform/platform.go
- internal/providers/ibmcloud/ibmcloud.go
Add ibmcloud support. Right now this only supports vpc gen 2, but leaves
in place the mechanisms to add classic/gen 1 support which look like
openstack.
Tested, confirmed it works.
> providers: add ibmcloud

- internal/exec/engine.go
- internal/providers/aliyun/aliyun.go
- internal/providers/aws/aws.go
- internal/providers/cloudstack/cloudstack.go
- internal/providers/cmdline/cmdline.go
- internal/providers/digitalocean/digitalocean.go
- internal/providers/gcp/gcp.go
- internal/providers/openstack/openstack.go
- internal/providers/packet/packet.go
- internal/resource/url.go
Rather than having each platform provider pass down `resource.ConfigHeaders`,
automatically inject it.  Then each platform only needs to pass
additional headers, which in most cases is none.
Unexport `configHeaders` then.
This also avoids mutating a global variable (!).  Queue obligatory
crying for 3 seconds that this code isn't Rust.
Prep for further work around headers.
> Rework fetch/resource to automatically append required headers

- doc/examples.md
On OSTree systems, `/` is immutable; let's use a file path
that can be written to as an example so this fragment can
be simply copy/pasted as a test.
> doc/examples: Make example file path valid

- doc/operator-notes.md
- internal/distro/distro.go
- internal/exec/stages/files/files.go
- internal/exec/stages/files/filesystemEntries.go
- internal/exec/stages/mount/mount.go
- internal/exec/util/file.go
- internal/exec/util/selinux.go
Now that we can relabel from the initrd, we should be able to
categorically resolve all SELinux and Ignition issues.
Here, we drop the hacky `ignition-relabel.service` and relabel all the
files we need to on the spot!
Requires: https://lore.kernel.org/selinux/20190819193032.848-1-jlebon@redhat.com/
Closes: #635
> selinux: perform relabeling from initrd

- .travis.yml
- internal/log/log.go
- tests/blackbox_test.go
- tests/filesystem.go
- tests/validator.go
The casts to `unix.WaitStatus` fail. Replace them with the new (1.12) os.ProcessState.ExitCode. Also clean up some error handling
> Fix error handling with processes

- internal/exec/stages/files/passwd.go
On OSTree systems, those are just symlinks in the deployment root. If
they're not labeled correctly already, it signals an issue with the disk
creation process itself (and might also signal that the next time a
deployment root is created, it'll also be mislabeled).
Anyway, even on non-OSTree systems, it seems reasonable to expect that
`/home` and `/root` at least already exist and don't need to be created
(and thus don't need to be relabeld).
It's possible that [fixing `getxattr` without a policy
loaded](https://github.com/coreos/fedora-coreos-config/pull/245#issuecomment-560578750)
would also fix this, since `setfiles` would see that the symlinks were
already correctly labeled.
In effect, this is completing what #632 started.
Closes: …
> stages/files: don't relabel /home and /root symlinks

- internal/exec/util/passwd.go
Currently errors while setting the SSH key (e.g. when trying to write onto a read-only file system) are silently ignored; report and abort if setting the key fails like Ignition does for any other unsuccessful operation.
> Throw error if SSH keys could not be written

- config/shared/errors/errors.go
- config/v2_4_experimental/append_test.go
- config/v2_4_experimental/types/headers.go
- config/v2_4_experimental/types/headers_test.go
- config/v2_4_experimental/types/schema.go
- doc/configuration-v2_4-experimental.md
- internal/config/translate.go
- internal/config/types/headers.go
- internal/config/types/headers_test.go
- internal/config/types/schema.go
- schema/ignition.json
- tests/negative/files/missing_file.go
- tests/negative/general/config.go
- tests/negative/security/tls.go
- tests/positive/files/hash.go
- tests/positive/files/remote.go
- tests/positive/general/general.go
- tests/positive/security/tls.go
In the future, we might want to add options, such as the ability to preserve certain headers across HTTP redirects.  That's much cleaner with a struct than an array.
While we're here:
- Have config validation report duplicate headers by name.
- Have unit tests try empty header values.
> Convert httpHeaders from arrays of strings to structs

- internal/platform/platform.go
- internal/providers/vultr/vultr.go
* Add Vultr as a provider, user-data can be an Ignition config
* Metadata endpoint is http://169.254.169.254/user-data/user-data
Background:
Hi! :wave:  I've been using Fedora CoreOS on Vultr for some time. Using the installer ISO crashing to an emergency shell to supply a shim Ignition config that points to Vultr metadata server's user-data to create an image that will boot with Ignition on Vultr. Recently the Fedora CoreOS installer ISO seems to have been removed, so I'd like to add proper support.
> providers/vultr: Add Vultr provider

- .cci.jenkinsfile
This is a basic CI job that builds Ignition, shoves it into FCOS, and
then runs the kola testsuite.
This is a pattern we'll dedupe more in the future with other OS
components like rpm-ostree, ostree, afterburn, etc...
> ci: hook up to CoreOS CI

- doc/supported-platforms.md
This fixes a few outdated names and missing links on the "Supported
Platforms" doc page.
> docs: minor fixes to platforms page

- internal/exec/util/blkid.go
This was an issue I encountered while testing partition creation on s390x, where the
number of partitions returned by numParts was a bogus number. At first I thought it was
an endianness issue with blkid, but turned out that the C compiler's int variable size and
the Go compiler's int variable sizes are different (on s390x at least) which caused this bug.
The fix is to make numParts a C int variable to be consistent with what is returned by blkid
> blkid: Explicitly use C int variable for numParts

- internal/providers/qemu/qemu_blockdev.go
- internal/providers/qemu/qemu_fwcfg.go
Add experimental support for fetching Ignition configs via a virtio
block device with serial/ID `ignition`.
The main advantage of this is that it is cross-platform. But for now, we
only use it on platforms which don't support the QEMU firmware config
approach, which are (of those we care about) s390x and ppc64le. We may
end up using it across the remaining platforms.
See related discussions in:
#928
> providers/qemu: support Ignition block device on s390x and ppc64le 

- tests/filesystem.go
This commit adds a check for errors other than ExitError
before trying to dereference a nil pointer.
Signed-off-by: Kamil Domański <kamil@domanski.co>
> tests: don't panic after failing to run Ignition

- Makefile
- internal/providers/qemu/qemu_blockdev.go
- internal/providers/qemu/qemu_fwcfg.go
Add experimental support for fetching Ignition configs via a virtio
block device with serial `ignition`.
The main advantage of this is that it is cross-platform. But for now, we
only use it on platforms which don't support the QEMU firmware config
approach, which are (of those we care about) s390x and ppc64le. We may
end up using it across the remaining platforms.
See related discussions in:
https://github.com/coreos/ignition/issues/928
(Backport of #905).
> providers/qemu: support Ignition block device on s390x and ppc64le

- config/shared/errors/errors.go
- internal/exec/stages/files/units.go
- internal/exec/stages/files/units_test.go
- internal/exec/util/unit.go
- internal/systemd/systemd.go
- tests/positive/files/units.go
> Fix for systemd instantiated services when enabled via ignition

- tests/positive/files/units.go
This fixes a blackbox test for the instantiated units which is failing due to the bad config: https://jenkins-container-linux.apps.ci.centos.org/job/os/job/Ignition%20BB%20tests/201/console
> Fix ignition config for the instantiated unit blackbox_test

- doc/development.md
- internal/resource/url.go
- tests/servers.go
We haven't done that since 2.2.0.  Also update spec bump instructions.
> resource: update Accept header to spec 2.4.0

- internal/providers/qemu/qemu_fwcfg.go
Commit 3b930b made it impossible to build Ignition on any other arch then s390x, ppc64le, amd64 or arm64 by explicitly stating the allowed platforms. This made it impossible to build e.g. for 386.
Continue to use the fw_cfg interface as default instead.
> providers/qemu: fix default to fwcfg

- internal/exec/util/blkid.go
This was an issue I encountered while testing partition creation on s390x, where the
number of partitions returned by numParts was a bogus number.This is because the int
variable is 64 bit in golang and 32 bit in C. This was further exposed because s390x is
big endian.
The fix is to make numParts a C int variable to be consistent with what is returned by blkid
Backport of: https://github.com/coreos/ignition/commit/76a71f08d3c1e27b2c4a3451c2d98ce5e054c7fd
> blkid: Backport: Explicitly use C int variable for numParts

- doc/configuration-v3_0.md
- doc/configuration-v3_1-experimental.md
Fix copy-paste error referring to "config" rather than "contents".
Improves documentation of #961.
> doc: clarify wording of files.*.verification.hash

- internal/exec/engine.go
- internal/exec/util/util.go
- vendor/github.com/coreos/go-systemd/v22/journal/journal.go
- vendor/modules.txt
> Enable logging to the systemd journal if a user config is provided

- .cci.jenkinsfile
- tests/kola/blackbox.sh
Right now, the blackbox test is running in a job on the CL Jenkins
instance. We want to migrate this to CoreOS CI where we have the right
perms set up for everyone to see.
Use the new external host tests support in kola to just run it directly
in the just-built FCOS where it'll have all the privs it needs to e.g.
set up loopback devices.
Aside: I'm thinking we should be able to migrate all of those blackbox
tests to external host tests if we gained the ability to specify the
Ignition config. Booting VMs would be more expensive of course, but way
closer to how Ignition is actually run and it would allow cleaning up
the blackbox testing-specific code. We could also do tricks like not
actually switch root to make each test less expensive.
> ci: run blackbox tests in CoreOS CI

- internal/resource/url.go
- internal/resource/url_test.go
- tests/positive/files/file.go
There's no reason not to support this, and we were only failing to do so because of an explicit check forbidding it.
Supersedes https://github.com/coreos/ignition/pull/938.
> resource/url: allow compression in data URLs

- NEWS
Trying something new here: changes that only affect the 3.1.0 spec are marked `(3.1.0)`.
> news: add notes for 2.3.0

- .cci.jenkinsfile
It seems like there's a regression in the 5.6.8 kernel causing our
blackbox tests to fail with e.g.:
```
blackbox_test.go:114: failed: "mkfs.vfat": exit status 1
mkfs.vfat: unable to open /dev/loop0p1: No such file or directory
mkfs.fat 4.1 (2017-01-24)
```
And looking at dmesg, one can see the partition rescan is failing with
`-EBUSY`:
```
__loop_clr_fd: partition scan of loop3 failed (rc=-16)
loop_reread_partitions: partition scan of loop0 (/var/tmp/ignition-blackbox-570148150/hd0) failed (rc=-16)
loop_reread_partitions: partition scan of loop1 (/var/tmp/ignition-blackbox-134124829/hd0) failed (rc=-16)
loop_reread_partitions: partition scan of loop2 (/var/tmp/ignition-blackbox-492917208/hd0) failed (rc=-16)
loop_reread_partitions: partition scan of loop3 …
```
> ci: Freeze kernel at 5.6.7 due to loop regression breaking blackbox test

- config/shared/errors/errors.go
- config/v3_0/types/directory.go
- config/v3_0/types/file.go
- config/v3_1/types/directory.go
- config/v3_1/types/file.go
- config/v3_2_experimental/types/directory.go
- config/v3_2_experimental/types/file.go
The warning was originally added in https://github.com/coreos/ignition/pull/493 because Ignition spec 2 defaulted to mode 0000, which was certainly not what the user wanted.  However, spec 3 defaults to 0755 for dirs and 0644 for files, and is documented as such.  It's therefore reasonable for the user to omit those fields, and by issuing the warnings we're encouraging the user to write unnecessarily verbose Ignition configs (or FCCs).
> config/*: drop warning on unset file/dir mode

- doc/configuration-v3_0.md
- doc/configuration-v3_1.md
- doc/configuration-v3_2_experimental.md
- internal/resource/http.go
- tests/fixtures/tls_fixtures.go
- tests/negative/security/tls.go
- tests/positive/security/tls.go
- tests/servers/servers.go
> Add support for CA bundles for fetching the ignition config

- doc/configuration-v3_0.md
- doc/configuration-v3_1.md
- doc/configuration-v3_2_experimental.md
Fix a couple places in `files` that refer to `source` without mentioning whether they mean the one in `contents` or `append`.
> doc/configuration-*: clarify references to `source`

- internal/exec/engine.go
- internal/exec/stages/fetch_offline/fetch-offline.go
- internal/exec/stages/fetch_offline/fetch_offline_test.go
- internal/main.go
- internal/resource/url.go
- internal/util/url.go
Add a new `fetch-offline` stage which can optionally be run before the
`fetch` stage. The major difference between the two is that the former
tries to operate in offline mode: if it encounters any resource which
requires network access, it quietly exits, creating a stamp file on the
way out.
This allows OS integrators to make use of this to only bring up
networking if Ignition actually requires it. It does not solve the
harder problem of "partially" up networking, where some fetches might
succeed and some others might fail. However, it provides an incremental
step to get there by reusing the same signalling mechanism.
> fetch-offline: new stage for conditional networking

- .cci.jenkinsfile
```
$ git log upstream/master..
commit cdcac7ea8ed9706686abd1f3fd85c3fc1df7cf0c
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Tue Jun 9 17:17:38 2020 -0400
ci: also run gofmt and unit tests
Part of the work to replace the CL Jenkins and Travis in favour of
CoreOS CI.
commit 8267bcf13662b6589ab065920a5030b369f1a28b
Author: Jonathan Lebon <jonathan@jlebon.com>
Date:   Tue Jun 9 17:16:48 2020 -0400
ci: move comment about kernel closer to `curl`
So that it's clearer what it's referring to.
```
> Various CI tweaks

- internal/exec/stages/fetch_offline/fetch_offline_test.go
- internal/resource/url_test.go
- internal/util/url.go
Right now Ignition will incorrectly report that it needs networking when
an empty scheme is given. Modify the `UrlNeedsNet` function to allow
both `data` & empty schemes.
A common case that could hit this is a config that writes a file with
empty contents.
> internal/util/url: don't require networking for empty schemes

- internal/exec/stages/files/passwd.go
- internal/exec/util/passwd.go
- internal/exec/util/selinux.go
- internal/exec/util/user_group_lookup.go
- internal/exec/util/util.go
We shouldn't need to run `setfiles` with `-i`, which causes `setfiles`
to ignore files that do not exist. All the files which we pass to
`setfiles` should exist, and it should be a hard error if `setfiles`
fails to find and relabel the file we wrote.
This dates from #632, where we
added `/var/home` and `/var/roothome` for OSTree-based systems. We
actually don't need to special-case OSTree systems at all anymore.
The `/var/home` and `/var/roothome` directories themselves are now
handled by `ignition-ostree-populate-var.service`. All we need to take
care of here is to relabel the homedir files we created or modified for
each user.
Because `setfiles` by default doesn't follow the final symlink, we also
add a check here to relabel the target if the homedir is a link.
(Ideally, we'd change the …
> files: don't run `setfiles` with `-i`

- CONTRIBUTING.md
- MAINTAINERS
The MAINTAINERS file doesn't seem to serve much of a purpose, and tends to get out of date.
> MAINTAINERS: drop file

- internal/exec/stages/files/units.go
On Fedora CoreOS, the `/etc/systemd/system-preset` directory doesn't
exist, which means that we need to make sure we label it when we create
it.
> files: relabel the systemd preset directory

- internal/platform/platform.go
- internal/providers/azure/azure.go
- internal/providers/azurestack/azurestack.go
This moves the iso9660 support out of Azure's provider and introduces a
new provider for AzureStack. Per [1], we found that AzureStack should be
treated as its own platform. The Azure provider now is configurable for
the filesystem types.
[1] https://github.com/coreos/fedora-coreos-tracker/issues/476
Signed-off-by: Ben Howard <ben.howard@redhat.com>
> AzureStack: introduce new provider

- internal/exec/engine.go
- internal/resource/http.go
- tests/blackbox_test.go
- tests/filesystem.go
When the user-provided config is empty write an empty cache config to
prevent re-fetching it in every stage.
Closes #950
> internal/exec/engine: write empty cache config when not provided

- internal/exec/stages/files/units.go
- tests/positive/files/units.go
Fixes https://github.com/coreos/ignition/issues/975
> units: empty dropins should be written to disk

- internal/exec/stages/fetch_offline/fetch-offline.go
- internal/exec/stages/fetch_offline/fetch_offline_test.go
If there is a Tang-pinned LUKS device, mark the config as requiring
networking.
Closes: #1017
> fetch-offline: signal networking for Tang-pinned LUKS devices

- internal/exec/util/user_group_lookup.c
Both `getpwnam_r(3)` and `getgrnam_r(3)` can return `ENOENT` or `ESRCH`
if the record is not found. Handle these.
The manpages also list `EBADF` and `EPERM` (and implies others via
`...`) as other possible codes, which is not great. Digging into this a
bit, I think it may be due to different conventions in different NSS
providers? Let's just handle `ENOENT` and `ESRCH` for now and leave the
less obvious ones until we actually hit something that returns it.
This fixes the error CI is hitting in #1014 where it gets `ESRCH` when
looking up a non-existent group.
Tested-by: Sohan Kunkerkar <sohank2602@gmail.com>
> util/user_group_lookup: handle more error codes

- internal/exec/stages/files/passwd.go
Regression from #996. If the home directory is a symlink, then just
relabel the referent, not the symlink itself. Since the symlink already
existed, we assume that it's properly labeled.
This causes an error on the FCOS live ISO, where `/sysroot` is mounted
from the squashfs, and so is read-only. But even on non-live, we should
just assume that whatever created the `/root -> /var/roothome` symlink
labeled it correctly.
This would normally be a no-op because `setfiles` would see that it's
properly labeled and not even attempt a `setxattr`. But because we can't
yet read SELinux labels from the initrd, it thinks it's unlabeled. (That
will be fixed by https://bugzilla.redhat.com/show_bug.cgi?id=1845210).
> files: don't relabel homedir symlinks themselves

- .cci.jenkinsfile
- internal/exec/engine.go
Regression from #958. We switched the list of providers from an array to
a map. But iteration order through a map is undefined, so we lost the
precedence of providers.
I think this is the cause behind a lot of the FCOS installer test
timeouts, such as:
coreos/coreos-assembler#1597
There, we pass the Ignition config for the PXE boot via
`ignition.config.url`, but if the metal (no-op) fetcher appears earlier
than the `cmdline` fetcher, we get no config. And similarly for the
installed system when the no-op fetcher appears before the `system`
fetcher (which coreos-installer's `--ignition-file` leverages).
The likelihood of this happening increased in the v2.4.0 release due to
#1002, which only gave us one try
to iterate over the correct provider first (at the `fetch` stage),
rather than …
> engine: fix provider config precedence

- .cci.jenkinsfile
It's required as of https://github.com/coreos/coreos-assembler/pull/1612.
> ci: build metal4k image before live image

- internal/exec/stages/disks/filesystems.go
We forgot to use the device alias when querying filesystem info, leading to potential races with udev deleting and recreating symlinks if the device node is specified via a `/dev/disk` link.
https://bugzilla.redhat.com/show_bug.cgi?id=1812233
> stages/disks: get filesystem info via device alias

- .cci.jenkinsfile
With https://github.com/coreos/coreos-assembler/pull/1620, this is no longer more efficient for running `kola testiso`.  We're not testing with the legacy installer, so no compression is needed at all.
> ci: drop cosa compress call

- .cci.jenkinsfile
This reverts commit 12edd76e0df3686e470505a70bae15a8bf5e7c4b and can be merged after https://github.com/coreos/fedora-coreos-config/pull/526 lands.
> ci: stop skipping rootfs.uuid kola test

- build_blackbox_tests
- config/v3_2_experimental/schema/ignition.json
- config/v3_2_experimental/translate/translate.go
- config/v3_2_experimental/types/schema.go
- dracut/30ignition/module-setup.sh
- internal/distro/distro.go
- internal/exec/stages/files/passwd.go
- internal/exec/util/passwd.go
- tests/positive/passwd/users.go
- tests/stubs/groupdel-stub/main.go
- tests/stubs/userdel-stub/main.go
Fixes #738 
We need to wait until https://github.com/coreos/ignition-dracut/pull/197 gets merged. Not ready for review yet.
> passwd: Add a way to delete users/groups

- config/shared/errors/errors.go
- config/v3_2_experimental/types/luks.go
- internal/exec/stages/disks/luks.go
Allows Ignition to generate the key-file in all cases (instead of just
for clevis based devices).
Closes #1021
> internal/config: allow Ignition generated key-files for all devices

- internal/providers/cloudstack/cloudstack.go
- internal/providers/openstack/openstack.go
On CloudStack/OpenStack, we fetch from three different sources
simultaneously: two config drives, and the metadata service.
Error-handling for these goroutines was causing `ErrNeedNet` from the
latter to be ignored and so we weren't correctly propagating it back to
the caller (which keys off of it to signal to the OS that networking is
needed).
Do a simple hack where we check if `ErrNeedNet` was hit and if none of
the fetchers succeed, then we return that instead. (The better fix of
course is to not try to parallel guess the metadata source like this,
but that's a much bigger issue.)
Fixes: #956
Fixes: #1056
> cloudstack|openstack: propagate ErrNeedNet

- internal/exec/stages/disks/partitions.go
- internal/exec/util/blkid.go
- internal/sgdisk/sgdisk.go
- tests/positive/partitions/zeros.go
We were reusing `StartMiB` and `SizeMiB` from `types.Partition` to hold sector counts, which is confusing.  Create a wrapper type with distinct fields for sector counts.  Then make all sector counts `int64`, which matters on 32-bit systems.
Also fix type confusion producing an invalid sector size from `DumpDisk()` on big-endian systems.
Alternative to #1015.
> Fix integer type issues with sector values

- Makefile
This pull request tries to fix two Makefile bugs of the `install` target:
1. On 32 Bit x86 machines the ignition binaries were searched in the wrong directory due to a missing Go architectures <-> Linux hardware name; another mapping was introduced, handling various machine strings such as _i486_ or _i686_.
2. Dracut and systemd are all installed with the default permissions of _755_. Separate the files by extension and assign the matching permissions so the executable bit is only set for scripts. This will also avoid warning by systemd due to the incorrect permissions.
> Makefile install fixes

- internal/exec/stages/disks/luks.go
- internal/exec/stages/files/filesystemEntries.go
Wait on devices & use device aliases to help avoid udev races.
> internal: use device aliases for LUKS

- config/v3_0/types/node.go
- config/v3_0/types/storage.go
- config/v3_1/types/node.go
- config/v3_1/types/storage.go
- config/v3_2_experimental/types/node.go
- config/v3_2_experimental/types/storage.go
The functions from the "path" package are idempotent while the
implementations of functions in "path/filepath" differ between unix and
windows systems.
This is so the Link validation as well as the Node.Depth() function work
correctly when run on windows systems.
> types: Use "path" instead of "path/filepath"

- config/v3_2_experimental/schema/ignition.json
- config/v3_2_experimental/types/schema.go
- doc/configuration-v3_2_experimental.md
- internal/exec/stages/disks/luks.go
Allows for re-use of both key-file & clevis based devices when key-files
are provided. The device will be re-used provided the UUID & Label match
(if they're provided) and it can be opened with the provided key-file.
Closes #1016
> internal/stages/disks: allow LUKS device re-use

- internal/providers/azurestack/azurestack.go
Fixes an error on AzureStack:
`failed to fetch config: filesystem "iso9660" is not a supported ovf device`
> AzureStack: fix unfortunate typo of iso9660

- doc/configuration-v3_2_experimental.md
This addition to the docs was missed in the original PR
https://github.com/coreos/ignition/pull/1014
> doc: Add shouldExist for users

- dracut/30ignition/ignition-fetch.service
- internal/exec/engine.go
Right now, even if `fetch-offline` gets `ErrNeedNet`, it might've still
logged info about configs which it did fetch before hitting the error.
This then results in double-logging of e.g. the base config and at least
the first layer of user configs when `fetch` re-fetches them.
But it's also misleading, because anything which runs between
`fetch-offline` and `fetch` and sees the journal messages will think
that Ignition did successfully fetch and cache the merged user config,
when it did not.
And sadly, we still have code which peek at the cached config for
`$reasons` (legacy-style RHCOS LUKS is one of them, RHCOS FIPS support
is another), and those bits get thrown off by seeing the logging
messages yet not seeing a cached Ignition config.
Let's tweak things so that we buffer those …
> engine: fix logging interactions with fetch-offline

- internal/exec/engine.go
- internal/platform/platform.go
- internal/providers/aws/aws.go
- internal/providers/providers.go
Fetch the S3RegionHint on all stages rather than just after fetching the
config. Doing this allows for authenticated fetches to work when running
in any partition (when fetching objects from S3 in the same partition).
> internal: fix S3 region detection

- .cci.jenkinsfile
The loopback issue should be fixed now and we need a newer kernel for
the rootfs reprovisioning tests to work.
Closes: https://github.com/coreos/fedora-coreos-tracker/issues/619
> ci: unfreeze kernel

- config/v3_2_experimental/schema/ignition.json
- config/v3_2_experimental/translate/translate.go
- config/v3_2_experimental/types/schema.go
- docs/configuration-v3_2_experimental.md
- docs/operator-notes.md
- internal/exec/stages/disks/partitions.go
- tests/negative/partitions/simple.go
- tests/positive/partitions/creation-mb.go
> stages/disks: support resizing an existing partition

- internal/providers/cloudstack/cloudstack.go
- internal/providers/openstack/openstack.go
This is a follow up to (and revert of) #1057.
On OpenStack, we don't actually know if we're fetching from the
config-drive or from the metadata server.
In theory, if it's from the config-drive, we don't strictly need
networking, and so `fetch-offline` would work. The issue is that in the
more common case of the metadata server, `fetch-offline` will still wait
the full 30s for the config-drive to also time out only to then have to
bring up networking and run the `fetch` stage.
Instead, let's just accept the brokenness of the OpenStack provider and
declare it as always requiring networking.
For more information, see:
https://github.com/coreos/ignition/issues/1081#issuecomment-693022160
> fetch-offline: immediately return ErrNeedNet on OpenStack

- internal/providers/cloudstack/cloudstack.go
- internal/providers/openstack/openstack.go
See individual commit messages.
> internal/providers/openstack: multiple fixes

- internal/providers/cloudstack/cloudstack.go
- internal/providers/openstack/openstack.go
Drop the timer for the config fetch on the *stack platforms. In the no
config case one of the config drive or metadata service should appear
and either not contain the file or return a 404.
Closes #1081
> interal/providers/*stack: drop timeout for config fetch

- NEWS
We don't support `file` URLs at all; we added compression support for `data` URIs.
> news: fix error in 2.3.0 changelog

- docs/development.md
External tests may be consuming the experimental spec version causing
failed CI runs when stabilizing a spec.
> docs: add section to spec stabilization for failing external tests

- .github/ISSUE_TEMPLATE/release-checklist.md
`spectool` already has tooling for downloading source files.
> release-checklist: drop download_ignition.sh

- docs/development.md
Rather than forcibly merging on red and breaking CI, add any tests
targeting the experimental spec version to the denylist until after
everything has merged in external repos.
> docs/development: update spec stabilization to avoid CI breakage

- .github/ISSUE_TEMPLATE/release-checklist.md
This will update the release instructions to provide some information around the `master` branch reference and clarify the step while publishing a release.
Based on the feedback, I will update the release checklist for https://github.com/coreos/fcct/blob/master/.github/ISSUE_TEMPLATE/release-checklist.md
> release-checklist: minor updates to the release instructions

- config/v3_0/config_test.go
- config/v3_1/config_test.go
- config/v3_2/config_test.go
- config/v3_3_experimental/config_test.go
This seems to have transitioned into being unused in
https://github.com/coreos/ignition/commit/9910ed2530f43fa9e4926e45c947cc1cfbba5646
and then it was cargo culted forward into parser tests thereafter.
Prep for further cleanup.
> tests: Remove unused checkOnStrings

- config/merge/merge.go
- internal/exec/stages/disks/disks.go
- internal/exec/stages/disks/partitions.go
- internal/exec/util/file.go
- internal/resource/url.go
- internal/util/tools/docs/docs.go
- tests/filesystem.go
Fixes part of https://github.com/coreos/ignition/issues/1121
Addresses the following warnings:
```
tests/filesystem.go:159:6: SA5011: possible nil pointer dereference (staticcheck)
cmd.Dir = cwd
^
tests/filesystem.go:160:6: SA5011: possible nil pointer dereference (staticcheck)
cmd.Env = append(os.Environ(), appendEnv...)
^
config/merge/merge.go:296:13: SA9003: empty branch (staticcheck)
} else {
^
internal/exec/stages/disks/partitions.go:96:45: SA6005: should use strings.EqualFold instead (staticcheck)
if spec.GUID != nil && *spec.GUID != "" && strings.ToLower(*spec.GUID) != strings.ToLower(existing.GUID) {
^
internal/exec/stages/disks/partitions.go:99:53: SA6005: should use strings.EqualFold instead (staticcheck)
if spec.TypeGUID != nil && *spec.TypeGUID != "" && …
```
> *: fix staticcheck warnings

- internal/exec/util/file.go
- internal/exec/util/util.go
- tests/filesystem.go
Fixes part of https://github.com/coreos/ignition/issues/1121
Addresses the following warnings:
```
internal/exec/util/file.go:51:6: `newHashedReader` is unused (deadcode)
func newHashedReader(reader io.ReadCloser, hasher hash.Hash) io.ReadCloser {
^
internal/exec/util/util.go:27:2: `errEscapedMountpoint` is unused (deadcode)
errEscapedMountpoint = errors.New("Symlink traversal resulted in path outside of filesystem")
^
internal/exec/util/util.go:49:6: `wantsToEscape` is unused (deadcode)
func wantsToEscape(p string) bool {
tests/filesystem.go:408:6: `removeEmpty` is unused (deadcode)
func removeEmpty(strings []string) []string {
```
> *: fix deadcode warnings

- config/validate/validate_test.go
- internal/exec/stages/disks/partitions.go
- tests/negative/proxy/http.go
- tests/types/types.go
Fixes part of https://github.com/coreos/ignition/issues/1121
Addresses the following warnings:
```
internal/exec/stages/disks/partitions.go:223:16: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
startRegex := regexp.MustCompile("^First sector: (\\d*) \\(.*\\)$")
^
internal/exec/stages/disks/partitions.go:224:14: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
endRegex := regexp.MustCompile("^Last sector: (\\d*) \\(.*\\)$")
^
tests/types/types.go:250:13: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
pattern := regexp.MustCompile("\\$uuid([0-9]+)")
^
tests/negative/proxy/http.go:29:3: S1023: redundant `return` statement …
```
> *: fix gosimple warnings

- config/config_test.go
- config/v3_0/types/partition.go
- config/v3_1/types/partition.go
- config/v3_2/types/partition.go
- config/v3_3_experimental/types/partition.go
- docs/development.md
`TestConfigStructure()` was testing only spec 3.0 because the spec bump instructions don't mention it.  Add newer specs and update the instructions.  Also allowlist the struct pointers in 3.2 and 3.3-exp (#1132) that would have been caught if the test had been run on those versions; there's nothing we can do about 3.2 at least.
Extend `TestConfigStructure()` to call `Key()` on a zero value to check for nil dereference, since duplicate key detection will call `Key()` on structs that fail validation.  Then fix `Partition.Key()` nil dereference.
> config/*: reinstate config structure checks; fix nil deref on invalid partitions

- docs/configuration-v3_0.md
- docs/configuration-v3_1.md
- docs/configuration-v3_2.md
- docs/configuration-v3_3_experimental.md
It's not required unless files are being written into the filesystem.
Closes #1150.
> docs: make storage.filesystems.path field optional

- config/shared/errors/errors.go
- config/v3_0/types/filesystem.go
- config/v3_0/types/filesystem_test.go
- config/v3_1/types/filesystem.go
- config/v3_1/types/filesystem_test.go
- config/v3_2/types/filesystem.go
- config/v3_2/types/filesystem_test.go
- config/v3_3_experimental/types/filesystem.go
- config/v3_3_experimental/types/filesystem_test.go
Filesystem creation and mounting both ignore filesystems with `format` unset, but if the user specified `wipeFilesystem` or `mountOptions` that's clearly not their intent.  Fail validation in this case.
> config/*: require filesystems.format with wipeFilesystem or mountOptions

- internal/providers/aws/aws.go
See https://bugzilla.redhat.com/show_bug.cgi?id=1902996
where I think we might be hitting this.  It'd be good to log
when this happens because I believe we always want it to work.
> aws: Log if we fail to determine the EC2 region

- internal/exec/stages/disks/luks.go
- internal/exec/stages/disks/partitions.go
- internal/exec/stages/files/files_test.go
- internal/exec/stages/files/units.go
- internal/exec/util/passwd.go
- internal/exec/util/user_group_lookup_test.go
- internal/log/log.go
- internal/providers/azure/azure.go
- internal/providers/cloudstack/cloudstack.go
- internal/providers/ibmcloud/ibmcloud.go
- internal/providers/openstack/openstack.go
- internal/providers/packet/packet.go
- tests/filesystem.go
- tests/negative/security/tls.go
- tests/negative/timeouts/timeouts.go
- tests/positive/proxy/http.go
- tests/positive/security/tls.go
- tests/servers/servers.go
Fixes part of #1121 
Addresses the following warnings:
https://gist.github.com/sohankunkerkar/e7a8a97be039283d841db527acd7d360
And a few more `errcheck` warnings which are not covered in this gist, but appeared in an ad-hoc manner while trying to fix these warnings.
> *: fix golangci-lint warnings

- internal/providers/aws/aws.go
- internal/resource/http.go
- internal/resource/url.go
Fixes: https://github.com/coreos/ignition/issues/1117
Fix Ignition userdata fetch failure when IMDSv2 service is set to required on AWS. By default, use IMDSv2 by making a PUT request to the endpoint to fetch the session token. If the request fails on a 404, fall back to IMDSv1.
> internal: support IMDSv2 for AWS metadata service

- internal/providers/aws/aws.go
We are passing an empty `FetchOptions` object to the
`fetchFromAWSMetadata` function as we have yet to fetch the actual
config. This function attempts to append the IMDSv2 token to the HTTP
headers if it is fetched which panics assigning to a nil map.
> internal/providers/aws: fix panic when an IMDSv2 token is present

- docs/getting-started.md
The text `first boot` currently links to the top of the systemd documentation on condition directives by looking to `ConditionArchitecture`, which is confusing. I think it would be clearer to link to `ConditionFirstBoot` directly given the text and context of the link.
> docs/getting-started.md: modify first boot link

- .cci.jenkinsfile
- tests/kola/blackbox/run.sh
- tests/kola/blackbox/test.sh
We're moving away from a buildroot image based on cosa, so we need to do
our build in a separate pod. This is more complex, but the upside is
that it guarantees that we're always building in the same buildroot that
was used to build all of FCOS' components.
> ci: adapt to new buildroot image

- config/util/reflection.go
- config/v3_1/translate/translate_test.go
- config/v3_2/translate/translate_test.go
- config/v3_3_experimental/translate/translate_test.go
Somehow, neither unit tests nor blackbox tests were exercising translation code at all.  If a PR introduced an undefined-translator panic, kola would be the first thing to notice.
Synthesize a config struct hierarchy with entirely non-zero fields, to ensure translation touches every type, and try to translate it.  This doesn't validate the contents of the translated structs, but at least it'll flush out any panics.
> config/*: test translation, actually

- config/config_test.go
Add tests for the first part of #1132.  Check that:
1. For "keyed structs" (those that have a key function and are in a slice),
1. all non-pointer primitive fields affect the key,
1. there is at least one non-pointer primitive field, and
1. all fields that affect the key are primitives or pointers to primitives, and are at the top level of the struct or reachable from a chain of anonymous embedded structs.
1. For structs other than keyed structs and structs anonymously embedded in them,
1. there are no non-pointer primitive fields.
Hardcode exceptions for every struct that breaks these rules.  We can fix the experimental spec as a followup.
> config: test that struct fields are properly pointered

- .github/ISSUE_TEMPLATE/release-checklist.md
> templates: drop git commit hash from package Release

- config/merge/merge_test.go
- config/v3_3_experimental/schema/ignition.json
- config/v3_3_experimental/translate/translate.go
- config/v3_3_experimental/types/kargs.go
- config/v3_3_experimental/types/kargs_test.go
- config/v3_3_experimental/types/schema.go
- docs/configuration-v3_3_experimental.md
- docs/development.md
- docs/distributor-notes.md
- dracut/30ignition/ignition-disks.service
- dracut/30ignition/ignition-fetch-offline.service
- dracut/30ignition/ignition-fetch.service
- dracut/30ignition/ignition-files.service
- dracut/30ignition/ignition-kargs-helper.sh
- dracut/30ignition/ignition-kargs.service
- dracut/30ignition/ignition-mount.service
- dracut/30ignition/ignition-setup-user.service
- dracut/30ignition/module-setup.sh
- examples/ignition-kargs-helper
- internal/distro/distro.go
- internal/exec/stages/kargs/kargs.go
- internal/main.go
Add a new top-level field `kernelArgument` to the configuration specification, a new Ignition stage `kargs`, and distributor documentation.
Closes #1168
> *: add kernel argument support

- .github/ISSUE_TEMPLATE/release-checklist.md
We removed commit hashes from the specfile in 2.9.0-4
> release-checklist: drop mention of commit hash variable

- config/config.go
- config/util/config.go
- config/v3_0/config.go
- config/v3_0/config_test.go
- config/v3_1/config.go
- config/v3_1/config_test.go
- config/v3_2/config.go
- config/v3_2/config_test.go
- config/v3_3_experimental/config.go
- config/v3_3_experimental/config_test.go
Closes https://github.com/coreos/ignition/issues/1190
This change helps external callers to import the package for the most recent version that they support and returns the desired config by calling a function that accepts any config version up to and including that version.
> config/*: add export functions for parsing any config version less than N

- config/v3_3_experimental/types/filesystem.go
- docs/configuration-v3_3_experimental.md
- docs/operator-notes.md
- internal/exec/stages/disks/filesystems.go
- internal/exec/stages/mount/mount.go
- internal/exec/stages/umount/umount.go
- tests/filesystem.go
- tests/negative/filesystems/creation.go
- tests/positive/filesystems/creation.go
Fixes: #1172
This PR tries to address the problem of erasing a block device with Ignition without creating a filesystem on it.
Also, related to https://bugzilla.redhat.com/show_bug.cgi?id=1926221
> Add a way to erase a block device without creating a filesystem

- Dockerfile.validate
Avoid build failures due to Docker Hub rate limits.
> Dockerfile: build ignition-validate container using Fedora

- dracut/30ignition/ignition-setup-user.service
We don't officially support multipath enabled on first boot yet. That's
what I'm working on, but this gets in the way because we actually need
to do the *opposite* (i.e. ensure that any I/O going to multipathed
devices is done through the multipath device node).
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1954025
> ignition-setup-user.service: drop Before=multipathd.service

- docs/rationale.md
Butane is meant to be distro-independent.  Reword the paragraph describing it to decouple it from FCOS.
> docs/rationale: recommend Butane for all distros

- internal/providers/cloudstack/cloudstack.go
- internal/providers/openstack/openstack.go
As of #1098, we no longer apply a timeout to config fetch.  Drop logging for the timeout case, since it makes the code more confusing.
> internal/providers/*stack: drop dead timeout code

- internal/platform/platform.go
- internal/providers/powervs/powervs.go
Add powervs platform support (https://github.com/coreos/fedora-coreos-tracker/issues/817). PowerVS is based on the IBMcloud vpc gen 1 which is similar to openstack.
> platform: add powervs platform

- docs/development.md
- go.mod
We've required it since at least f946e0df.
> *: formally bump Go to 1.13

- config/config_test.go
- config/shared/errors/errors.go
- config/v3_3_experimental/schema/ignition.json
- config/v3_3_experimental/translate/translate.go
- config/v3_3_experimental/types/clevis.go
- config/v3_3_experimental/types/clevis_test.go
- config/v3_3_experimental/types/luks.go
- config/v3_3_experimental/types/raid.go
- config/v3_3_experimental/types/raid_test.go
- config/v3_3_experimental/types/schema.go
- config/v3_3_experimental/types/storage.go
- config/v3_3_experimental/types/storage_test.go
- internal/exec/stages/disks/luks.go
- internal/exec/stages/disks/raid.go
- internal/exec/stages/files/filesystemEntries.go
- internal/exec/util/file.go
- internal/exec/util/unit.go
Primitive fields other than keys should be pointers, so they can be overridden by child configs during config merging.
Fixes the first half of #1132, and thus fixes #1132.
> config/v3_3_exp: pointerify primitive non-key spec fields

- config/v3_0/config_test.go
- config/v3_1/config_test.go
- config/v3_2/config.go
- config/v3_2/config_test.go
- config/v3_3/config.go
- config/v3_3/config_test.go
- config/v3_4_experimental/config.go
- config/v3_4_experimental/config_test.go
When we chain into the previous parser and it fails, return its report rather than an empty one.  3.1 was doing this correctly and 3.0 doesn't have this code, but newer specs were affected.
Add tests checking that both parse functions return a report on invalid configs.
Fixes #1193.
> config/*: return report from previous parser when chaining

- docs/migrating-configs.md
- internal/util/tools/docs/docs.go
In Ignition 2.x, the `Parse()` function from an individual config package doesn't chain to earlier specs, but this code still assumed it does.  As a result, all configs with stable spec versions would fail on `ErrUnknownVersion`, but we wouldn't notice because we were only looking at the report and not the error return.
Switch to the high-level chaining parse function.  Also, check for parse errors that aren't included in the report.
> tools/docs: notice invalid configs with stable specs

- .github/ISSUE_TEMPLATE/release-checklist.md
The rebuilt specfile no longer has them.
> templates: don't update `%gotest` lines

- .github/ISSUE_TEMPLATE/release-checklist.md
The new ticket includes a couple bugfixes in the script and sample output, ported from the corresponding Butane tickets.
> templates: update example releng signing ticket

- docs/development.md
- docs/specs.md
This helps to find which Ignition release first introduced support for a
given stable Ignition spec version.
> docs: Add Ignition release / Spec version table

- .cci.jenkinsfile
External tests have been updated.
Drop the `rm -rf` command, since kola now knows to avoid parsing the next stable config.
> ci: disable spec bump external test workaround

- internal/providers/gcp/gcp.go
There have been two hostname poisoning attacks against `metadata.google.internal`.  As a precaution, access it by IP address
instead, since the IP is documented anyway.
Addresses https://github.com/coreos/fedora-coreos-tracker/issues/891.
> providers/gcp: access GCP metadata service by IP address

- internal/exec/engine.go
- internal/exec/stages/fetch_offline/fetch-offline.go
- internal/main.go
- tests/filesystem.go
Traditionally we expose paths in `/run` as command-line options, which helps with testing.
> engine: don't hardcode neednet path

- internal/distro/distro.go
- internal/exec/engine.go
- internal/exec/stages/disks/disks.go
- internal/exec/stages/disks/luks.go
- internal/exec/stages/fetch/fetch.go
- internal/exec/stages/fetch_offline/fetch-offline.go
- internal/exec/stages/files/files.go
- internal/exec/stages/files/filesystemEntries.go
- internal/exec/stages/kargs/kargs.go
- internal/exec/stages/mount/mount.go
- internal/exec/stages/stages.go
- internal/exec/stages/umount/umount.go
- internal/exec/util/util.go
- internal/main.go
- internal/state/state.go
- tests/filesystem.go
Increasingly, we need to persist small bits of state between stages.  Add a general mechanism for this, which serializes a struct to a JSON file in `/run` at the end of each stage and loads it at the beginning of the next stage.  For now, use the mechanism to record the fetched-config summaries that are reported to the journal, plus LUKS keyfiles for the files stage.
Additionally, use this functionality to write a JSON file to `/var/lib/ignition/result.json` that contains the provisioning timestamp and a flag indicating whether a user config was used.  The idea is to move [this functionality](https://github.com/coreos/fedora-coreos-config/blob/29f74c49793798a86e54bb4fadafc85275b3f871/overlay.d/05core/usr/libexec/coreos-ignition-firstboot-complete#L28-L47) upstream, allowing distros to …
> Add persistence mechanism between stages; write result report to provisioned system

- internal/main.go
It was added in 0dcf378e2b7c, at a time when any stage would refetch the config if the cache was unavailable (see also 9b2913044a05).  The cache is now populated by dedicated fetch stages and later stages will fail if it's missing, so we can no longer clear it at will.
I'm not aware of any code using this flag.  Anything that needs it is running Ignition more than once per boot (i.e. test code), and should specify `-config-cache` directly (either with a distinct file for each run, or a file in a known path that it can remove between runs).
> main: drop `-clear-cache` flag

- examples/ignition-kargs-helper
Without `--force`, the boot process races with service shutdown, leaving enough time for the disks stage to start.  With `--force`, systemd immediately kills processes, unmounts filesystems, and reboots.
> examples: reboot with `--force`

- internal/exec/stages/files/passwd.go
- internal/exec/stages/mount/mount.go
- internal/exec/util/file.go
- internal/exec/util/passwd.go
- internal/exec/util/util.go
- internal/state/state.go
- tests/positive/files/directory.go
- tests/positive/passwd/users.go
- tests/validator.go
If Ignition creates a directory within a user's home directory as a result of creating a mountpoint, fix its permissions once the user exists.
Also fix SELinux labeling of a freshly-created ext4 filesystem.
Fixes #1220.
> exec: fix permissions for mountpoints in home dirs

- internal/distro/distro.go
- internal/exec/util/blkid.c
- internal/exec/util/blkid.go
- internal/exec/util/blkid.h
- internal/providers/azure/azure.go
Fixes #1194 
This patch adds support for Azure gen2 VMs in Ignition. For the safer side, this PR also handles a case where a bunch of block devices has the `FSTYPE` set to `udf`, and accordingly, pick the right device that has an ignition config.
With gen2 settings:
```
[    5.661976] systemd[1]: Finished Ignition (setup user config).
[    5.665860] systemd[1]: Starting Ignition (fetch-offline)...
[    5.672347] ignition[570]: Ignition v2.10.1-51-g3679fd11
[    5.676259] ignition[570]: Stage: fetch-offline
[    5.679908] ignition[570]: reading system config file "/usr/lib/ignition/base.d/00-core.ign"
[    5.684961] ignition[570]: reading system config file "/usr/lib/ignition/base.d/30-afterburn-sshkeys-core.ign"
[    5.690933] ignition[570]: reading system config file …
```
> Add support for Azure gen2 VMs

- .github/workflows/go.yml
- docs/development.md
- go.mod
- go.sum
- tests/filesystem.go
- vendor/modules.txt
F33, F34, and OCP 4.9 have Go 1.15 or higher.
> Drop EOL Go versions, bump linter, restrict workflow access to repo

- internal/exec/stages/files/filesystemEntries.go
This change notices if a report already exists and accordingly nest the report in `previousReport`.
related to https://github.com/coreos/ignition/issues/1214
Based on this change, the `fedora-coreos-config` code would check if `previousReport` exists and could throw a fat warning saying `Ignition was previously run at xx.  Unexpected behavior may occur.  Ignition is not designed to run more than once per system.`
> stages/files: add previousReport to the result report if Ignition is run more than once

- .cci.jenkinsfile
As a side effect, this enables 4Kn, UEFI, and multipath tests.
> ci: use coreos-ci-lib helper for kola testiso

- internal/providers/qemu/qemu_fwcfg.go
The kernel returns a maximum of 4096 bytes at a time, and firmware reads [take](https://github.com/torvalds/linux/blob/0ee7c3e25d8c28845fceb4dd1c3cb5f50b9c45a9/drivers/firmware/qemu_fw_cfg.c#L150-L151) O(offset) time, so we should try to optimize our read syscalls.  `ioutil.ReadFile()` eventually converges to an I/O size &ge; 4096 bytes but we can do it immediately and without repeatedly reallocating the buffer.  This saves 8 read operations at the beginning of the config (where it doesn't affect performance very much).
In addition, if reading the config takes more than 10 seconds, tell the user what is happening and start providing regular progress reports.
Closes https://github.com/coreos/ignition/issues/1259.
> providers/qemu: optimize fw_cfg read size and add progress reporting

- docs/supported-platforms.md
- internal/distro/distro.go
- internal/providers/virtualbox/virtualbox.c
- internal/providers/virtualbox/virtualbox.go
- internal/providers/virtualbox/virtualbox.h
- test
VirtualBox supports "guest properties", which are persistent UTF-8 key-value pairs accessible from both the host and guest.  Property values were originally limited to 128 bytes, and the VirtualBox codebase still contains vestiges of that limit, such as fixed-size buffers in some client code.  The limit is no longer enforced by the VirtualBox core; it seems to have been removed in [r21629](https://www.virtualbox.org/changeset?reponame=vbox&new=21629%40trunk%2Fsrc&old=21628%40trunk%2Fsrc) in 2009.
Read Ignition configs from an `/Ignition/Config` guest property by talking directly to the upstream vboxguest kernel module via `/dev/vboxguest`.  Ignition configs can be attached to a VM with something like this command:
VBoxManage guestproperty set vm-name /Ignition/Config "$(cat config.ign)" …
> providers/virtualbox: read config from `/Ignition/Config` guest property

- .github/ISSUE_TEMPLATE/release-checklist.md
No need to vendor the new Ignition version in mantle after [this](https://github.com/coreos/coreos-assembler/pull/2529) PR
> templates: skip vendoring the new version in favor of dependabot

- go.mod
- go.sum
- vendor/github.com/vincent-petithory/dataurl/dataurl.go
- vendor/modules.txt
There's a tagged release now; let's use it.
> go.mod: update dataurl to 1.0.0

- tests/positive/files/file.go
The data URLs which are used are all in URL encoding, while users can
also use base64 encoded data URLs.
Add a test to make sure base64 decoding works as expected.
> tests: Add base64 decoding test

- docs/supported-platforms.md
- internal/platform/platform.go
- internal/providers/cloudstack/cloudstack.go
- internal/providers/ibmcloud/ibmcloud.go
- internal/providers/nutanix/nutanix.go
- internal/providers/openstack/openstack.go
- internal/providers/powervs/powervs.go
- internal/util/umount.go
- tests/filesystem.go
xref: https://github.com/coreos/fedora-coreos-tracker/issues/1007
Tested this change on Nutanix AHV and it seems to be working fine.
```sh
$  ssh core@192.168.2.156
The authenticity of host '192.168.2.156 (192.168.2.156)' can't be established.
ED25519 key fingerprint is SHA256:xxxxxxxx.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.2.156' (ED25519) to the list of known hosts.
Fedora CoreOS 35.20211116.dev.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/
[core@fcos-ignition-f35-minimal ~]$ 
[core@fcos-ignition-f35-minimal ~]$ cat /proc/cmdline 
BOOT_IMAGE=(hd0,gpt3)/ostree/fedora-coreos-b14045b72b16211ba96b27fd2a0231 …
```
> providers/nutanix: Add Nutanix platform

- config/v3_4_experimental/schema/ignition.json
- config/v3_4_experimental/types/schema.go
Fix some schema nits that shouldn't affect Ignition, but might affect other language generators that want to read the schema (such as schemafy for [ignition-config-rs](https://github.com/coreos/ignition-config-rs)).
> config/v3_4_exp: minor schema fixes

- docs/getting-started.md
`index.md` and `rationale.md` both mention this, but `getting-started.md` currently doesn't, except when discussing systemd services in the troubleshooting section.  Add a mention and reference for anyone who starts with the getting-started guide.
Alternative to https://github.com/coreos/ignition/pull/1206.
> docs/getting-started: mention Ignition running on the first boot

- internal/exec/engine.go
Otherwise the next message merges with the last close-brace.
> internal/exec: print newline after Ignition config on failure

- internal/exec/stages/disks/luks.go
We need to persist a volume's keyfile to the real root even if we take the early `continue` when reusing the volume.  Rather than copying code, enable persistence up front and then disable it afterward if we decide not to persist the key.
Fixes error:
CRITICAL : Ignition failed: creating crypttab entries: missing persisted keyfile for [...]
Fixes: https://github.com/coreos/ignition/issues/1305
Fixes: 65e9c1611128 ("stages/disks: use State to persist keyfiles for files stage")
> disks: fix reuse of statically keyed LUKS volume

- .github/workflows/container.yml
- .github/workflows/go.yml
The container build doesn't care about the selected version of Go in the host, so there's no point in running it three times.  Move the container build to a separate job, matching Butane CI.
Also switch from docker to podman.
> workflows: move container build to dedicated job

- .github/workflows/go.yml
We ship ignition-validate for macOS and Windows, so let's test that in CI.  Ignition contains a lot of Linux-specific code, so it's not practical to run through the entire `./build` and `./test` flow.  Instead, create a parallel job that builds ignition-validate and runs only those tests that are pertinent to it.
> workflows: build and test ignition-validate on macOS and Windows

- .github/ISSUE_TEMPLATE/release-checklist.md
This will need another update after the next release, but for now, make sure we don't forget the new script.
Fixes #1311.
> templates/release-checklist: update for static Linux binaries

- .copr/Makefile
I'd like to enable auto-builds of this repo to
https://copr.fedorainfracloud.org/coprs/g/CoreOS/continuous/ so it could
eventually feed into
https://github.com/coreos/fedora-coreos-tracker/issues/910.
> Add COPR integration Makefile

- internal/exec/stages/files/units.go
The `relabelPath()` in `createUnits()` is the correct call, since it also handles the parent directory.  Move it into `createSystemdPresetFile()` for clarity and delete the other one.
Reported by @nemric.
Fixes #1006.
> files: fix duplicate relabeling of preset file

- internal/exec/stages/files/files.go
This PR handle relabelling by preventing multiple relabels ...
The goal is to avoid managing it in the code allowing contributors to call relabelling func without having to check if the path is already included in the "torelabel" slice
>  files: track relabeling using set instead of slice

- .github/workflows/go.yml
Old package versions can be removed from the mirror, which could cause job failures.
> workflows: `apt-get update` before installing packages

- .github/workflows/go.yml
- config/v3_1/types/headers_test.go
- config/v3_2/types/headers_test.go
- config/v3_3/types/headers_test.go
- config/v3_4_experimental/types/headers_test.go
Update `golangci-lint` to version v1.45.0 which has support for go 1.18
> ci: add testing with Go 1.18

- .github/workflows/container.yml
- Dockerfile.validate
- build_for_container
Quay builds are amd64-only and haven't been especially reliable.  Use GitHub Actions to build both amd64 and arm64 containers for the main branch and for tags, and push them to Quay.  Continue building but not pushing containers on PR.  Requires the `QUAY_AUTH` repo secret to be set to a Docker credential.
Ideally we would cross-build the arm64 container by having the Dockerfile specify `FROM --platform=$BUILDPLATFORM` for the builder container and set `GOARCH=$TARGETARCH`.  However, Buildah < 1.24.1 doesn't support `--platform` in FROM.  Build in emulation for now, and skip arm64 in PRs to speed up CI.
Fixes #1321.
> workflows: build and push `ignition-validate` container from GH Actions

- .github/workflows/container.yml
Fetch Git tags so the output of `--version` for the ignition-validate container isn't just a commit hash.
> workflows: include Git tag in container `--version`

- docs/supported-platforms.md
- internal/platform/platform.go
- internal/providers/kubevirt/kubevirt.go
KubeVirt is openstack config-drive compatible and uses the `config-2` label (lower case).
xref https://github.com/coreos/fedora-coreos-tracker/issues/1126
Testing ignition on a fcos machine where kubevirt injected the user-data shows this:
```bash
[core@vmi-fedora ~]$ sudo  /home/core/ignition --platform kubevirt --config-cache ignition.json --state-file state --stage fetch --log-to-stdout
INFO     : Ignition v2.13.0-58-g45429023
INFO     : Stage: fetch
INFO     : no config dir at "/usr/lib/ignition/base.d"
INFO     : no config dir at "/usr/lib/ignition/base.platform.d/kubevirt"
DEBUG    : parsed url from cmdline: ""
INFO     : no config URL provided
INFO     : reading system config file "/usr/lib/ignition/user.ign"
INFO     : no config at "/usr/lib/ignition/user.ign"
DEBUG    : creating …
```
> Add KubeVirt support

- internal/exec/engine.go
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/1159
> internal/exec: switch log level for failed to fetch the config

- internal/exec/util/passwd.go
We're hitting an error in that area but the error message isn't very
descriptive. Let's add more error prefixing.
> internal/exec/util/passwd: add more error-prefixing

- internal/providers/azure/azure.go
Azure userdata fetching is now divided into two parts:
* try to fetch userdata from IMDS
* in case of failure: try to fetch custom data from CDROM
Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>
<hr>
* Originally opened and reviewed here: https://github.com/flatcar-linux/ignition/pull/39
* Closes: https://github.com/coreos/ignition/issues/1347
> provider/azure: try to fetch userdata from IMDS

- internal/providers/virtualbox/virtualbox.go
`VBoxManage guestproperty set <instance> <key> <value> --flags <flags>` causes data to be inserted between the two `NUL` bytes we were expecting to be consecutive, causing config parsing to fail on the first `NUL` byte.  A cautious user might want to set some of these flags, such as `TRANSIENT`.  Fix by truncating off everything starting from the first `NUL`.
> providers/virtualbox: fix reading properties with flags

- config/shared/errors/errors.go
- config/v3_4_experimental/types/url.go
- config/v3_4_experimental/types/url_test.go
- docs/configuration-v3_4_experimental.md
- docs/supported-platforms.md
- internal/resource/url.go
- internal/resource/url_test.go
Support S3 access point URLs in ARN format as a source.
This allows valid, opaque S3 URLs such as
`s3:arn:aws:s3:us-west-2:123456789012:accesspoint/test/object`
Being able to use this format will allow S3 URLs on different
partitions and lays the foundation to potentially support
multi-region access points in the future.
Fixes https://github.com/coreos/ignition/issues/1091
Signed-off-by: Zeleena Kearney <zeleenak@lyft.com>
> internal/resource: support S3 access point URLs

- internal/resource/url.go
- internal/resource/url_test.go
For S3 access point ARNs, we derive the access point region from the region field in the ARN, allowing us to query the correct AWS partition.  For regular S3 object ARNs, the region field is not used, so we assume the same partition Ignition is running in, or `aws` if running outside AWS.
However, object ARNs include a valid partition field.  Compute a region hint from that, and use it to ask the partition for the correct bucket region.  That allows object ARNs to reference objects outside the current partition (when running in AWS) or outside the `aws` partition (when running outside AWS).
Followup to #1264.
cc @zeleena
> internal/resource: derive AWS region hint from ARN partition field

- internal/resource/url.go
- internal/resource/url_test.go
ARNs have a static `/object/` path component between the access point name and the object path.  Remove it when parsing ARNs.
See: https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-access-points.html
cc @zeleena
> internal/resource: fix S3 access point object ARNs

- internal/distro/distro.go
- internal/exec/util/unit.go
- tests/positive/files/units.go
We need to delete any enablement symlinks for a unit before sending it to a preset directive. This will help to disable that unit completely. This is a short-term solution until the upstream systemd PR (https://github.com/systemd/systemd/pull/15205) gets accepted.
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/392
> internal/exec: delete enablement symlinks when disabling unit

- docs/operator-notes.md
For https://github.com/coreos/ignition/issues/1322.  Followup to https://github.com/coreos/ignition/pull/1264.
> docs/operator-notes: document supported S3 URL formats

- internal/exec/util/path_sort.go
If the `-root` command-line argument isn't an absolute path, and the files stage tries to write a file, we get stuck in an infinite loop in `Depth()`.  Ignition shouldn't normally be invoked this way, but it might occur during manual debugging.  Avoid the infinite loop.
> exec/util: fix infinite loop in `Depth()` if `-root` is relative

- docs/operator-notes.md
Recommend against putting secrets in Ignition configs, document some mitigations if doing so, and document automatic userdata deletion.
See also https://github.com/coreos/fedora-coreos-docs/issues/306.
> docs/operator-notes: add section on provisioning secrets

- NEWS
Working through version bumping ignition [1353](https://github.com/coreos/ignition/issues/1353)
> NEWS: update v2.14.0

- .github/dependabot.yml
We have a lot of vendored dependencies, which we currently don't update.  Let's fix that.  Hopefully we have enough CI to pick up substantial regressions.
Hold until after release.
> github: enable Dependabot

- .github/dependabot.yml
Allow 10 outstanding PRs, matching most of our other projects.
> dependabot: configure PR label; increase maximum PR count

- Makefile
Don't put `ignition-apply` in `/usr/bin` because it's still fairly experimental, but do avoid requiring callers to create the symlink themselves.
cc @prestist
> Makefile: install `/usr/libexec/ignition-apply`

- internal/exec/stages/files/units.go
- tests/positive/files/units.go
The 20-ignition.preset file is used in CoreOS layering. The contents of the file will be sorted in alphabetical order by unit name to ensure the file is written in a consistent order across multiple runs. 
Fixes https://github.com/coreos/ignition/issues/1339
> units: Sort systemd presets in alphabetical order in 20-ignition.preset file

- docs/release-notes.md
We're going to try maintaining these incrementally as we work toward the next release, rather than building them from scratch at release time.
Also, backfill notes of historical signing key changes (xref https://github.com/coreos/repo-templates/pull/10).
> Add draft release notes for next release

- dracut/30ignition/module-setup.sh
ln_r expects an absolute path as first argument, passing a relative path
instead behaves as if it was relative to /. That behaviour lead to dangling
symlinks in the .target.requires directory.
Use the same method as dracut's own modules.
> dracut: Fix invalid use of ln_r

- dracut/30ignition/module-setup.sh
When creating luks devices with custom tpm2 policies, clevis-encrypt-tpm2
expects a symlink "tpm2_createpolicy" in the ramdisk. As Clevis dracut module
only embeds the decryption related tools, we need to add tpm2_createpolicy
ourselves.
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/1255
> dracut: include tpm2_createpolicy

- dracut/30ignition/ignition-disks.service
- dracut/30ignition/ignition-fetch-offline.service
- dracut/30ignition/ignition-fetch.service
- dracut/30ignition/ignition-files.service
- dracut/30ignition/ignition-kargs.service
- dracut/30ignition/ignition-mount.service
- internal/resource/url.go
We were inconsistent about which stages logged to syslog and which ones logged to stdout.  Always log to syslog, but add an env var allowing distros to override this via a drop-in.  Also back out some code in `resource` that overrode the global logger.
> Omit `-log-to-stdout` by default, but allow distros to enable it; avoid overriding logger in `resource`

- README.md
With latest Flatcar release, `main` branch of Ignition has landed on
`stable` channel.
Some patches are used on top of it to ensure
backward compatibility between with v1 and v2 spec with `ign-converter`.
Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>
> readme: move Flatcar to `main` branch

- README.md
All versions of RHCOS that use `spec2x` are EOL.
> README: drop reference to RHCOS using `spec2x`

- config/shared/errors/errors.go
- config/v3_0/types/storage.go
- config/v3_0/types/storage_test.go
- config/v3_1/types/storage.go
- config/v3_1/types/storage_test.go
- config/v3_2/types/storage.go
- config/v3_2/types/storage_test.go
- config/v3_3/types/storage.go
- config/v3_3/types/storage_test.go
- config/v3_4_experimental/types/storage.go
- config/v3_4_experimental/types/storage_test.go
- docs/configuration-v3_0.md
- docs/configuration-v3_1.md
- docs/configuration-v3_2.md
- docs/configuration-v3_3.md
- docs/configuration-v3_4_experimental.md
- docs/release-notes.md
They specify the group that should be applied to the inode, not the primary group of the inode's owner.
> docs: clarify group fields in config specs

- .github/dependabot.yml
This should fix the missing `skip-notes` labels on Dependabot PRs.
> dependabot: permute the label order to flush Dependabot's config cache

- config/shared/errors/errors.go
- config/v3_0/types/storage.go
- config/v3_0/types/storage_test.go
- config/v3_1/types/storage.go
- config/v3_1/types/storage_test.go
- config/v3_2/types/storage.go
- config/v3_2/types/storage_test.go
- config/v3_3/types/storage.go
- config/v3_3/types/storage_test.go
- config/v3_4_experimental/types/storage.go
- config/v3_4_experimental/types/storage_test.go
- docs/release-notes.md
https://github.com/coreos/ignition/issues/1397
Added simple check at filesystem validation to ensure that we warn when the Path matches the Device. 
Naming is hard, could use some input around Err name, and function naming. "ValidatePath" was taken so I tried to make do.
> filesystem.go: add warning when path matches device

- config/shared/errors/errors.go
- config/v3_0/types/config.go
- config/v3_0/types/config_test.go
- config/v3_1/types/config.go
- config/v3_1/types/config_test.go
- config/v3_2/types/config.go
- config/v3_2/types/config_test.go
- config/v3_3/types/config.go
- config/v3_3/types/config_test.go
- config/v3_4_experimental/types/config.go
- config/v3_4_experimental/types/config_test.go
- docs/release-notes.md
Fixes [Ignition#881](https://github.com/coreos/ignition/issues/881).
Users can specify files/links/dirs within `/etc/systemd/system` that would conflict with systemd units or dropin files at the same location. Add validation to prevent this configuration conflict. 
See [machine-config-operator#1203](https://github.com/openshift/machine-config-operator/pull/1203#issuecomment-545653433) for the decision to add this validation to Ignition.
> config/types: prevent files/links/dirs from conflicting with systemd units or dropins

- docs/release-notes.md
- internal/exec/stages/fetch_offline/fetch-offline.go
- internal/exec/stages/fetch_offline/fetch_offline_test.go
Resolves #1473, add a check for attributes that trigger networking to be inclusive of `ClevisCustom`'s `NeedNetwork` field.
> fetch-offline: add reconition for `ClevisCustom`'s `NeedsNetwork` field.

- README.md
spec2x was officially deprecated in August 2020 and has no remaining users.  Continue to reference it in the migration guide and spec list, but drop it from the README.
The ignition-dracut merge was released in July 2020.  Drop it from the README.
> README: drop references to ignition-dracut and spec2x branch

- config/v3_4_experimental/schema/ignition.json
- config/v3_4_experimental/translate/translate.go
- config/v3_4_experimental/types/schema.go
- docs/configuration-v3_2.md
- docs/configuration-v3_3.md
- docs/configuration-v3_4_experimental.md
- docs/operator-notes.md
- docs/release-notes.md
- internal/exec/stages/disks/luks.go
Discard improves performance and longevity on SSDs and space utilization on thinly-provisioned SAN devices, but also leaks information from LUKS.  It's a LUKS open-time option, not a create-time one, so it can't be enabled via the `options` field.  Add a spec field to enable it.
While we're here, add an `openOptions` spec field to allow configuring other options that can be persisted to the LUKS header.  Notably, `--perf-no_read_workqueue` and `--perf-no_write_workqueue` can improve performance.
Since `openOptions` is an escape hatch feature, unlike `discard`, we don't try to implement full option matching in the volume reuse semantics; we just update any reused volume to use the currently specified options.
For https://github.com/coreos/fedora-coreos-tracker/issues/1392.
> config/v3_4_exp: support persisting LUKS open-time options, especially discard

- docs/release-notes.md
- internal/exec/stages/disks/luks.go
Ignition has never supported LUKS1, so we can't ever try to reuse a LUKS1 volume created by Ignition.  However, a LUKS1 volume may have been created outside of Ignition, in which case we would conclude that the volume was not LUKS and clobber it, causing data loss.  Detect this case and fail instead.
Also, if the partition wasn't previously formatted as a LUKS volume, cryptsetup is supposed to exit non-zero; that's why we're calling it.  The resulting log message was always spurious, but is now more visible since Ignition errors are shown by c-l-h-m.
> disks: don't clobber LUKS1 volumes; fix spurious logs during LUKS volume reuse

- docs/configuration-v3_0.md
- docs/configuration-v3_1.md
- docs/configuration-v3_2.md
- docs/configuration-v3_3.md
- docs/configuration-v3_4.md
- docs/configuration-v3_5_experimental.md
- docs/release-notes.md
A followup to the butane PR https://github.com/coreos/butane/pull/387
> docs: clarify `hash` describes decompressed contents/config

- .github/workflows/go.yml
We don't want to add this directly to `./test` because that would create a schematyper dependency.
Based on the Rust Docs job from coreos-installer.
> workflows: add job to check whether generated schema is current

- .github/ISSUE_TEMPLATE/stabilize-checklist.md
- .github/workflows/go.yml
- docs/configuration-v3_0.md
- docs/configuration-v3_1.md
- docs/configuration-v3_2.md
- docs/configuration-v3_3.md
- docs/configuration-v3_4.md
- docs/configuration-v3_5_experimental.md
- docs/release-notes.md
- generate
- go.mod
- internal/doc/generate/generate.go
- internal/doc/generate/ignition.yaml
- internal/doc/generate/schema.go
- internal/doc/header.md
- internal/doc/main.go
Move all field descriptions to a single YAML file and generate version-specific spec docs from that.  Use reflection to walk the config structs for each version and omit fields which don't exist in a particular spec version.  Also allow the YAML file to include transformation rules for each field, consisting of a spec version range, a regex, and replacement string.
We don't do this at a JSON Schema level because e.g. `Resource` is referenced in multiple places with different semantics and different doc strings.
For now, keep the code out of the external API.  The plan is to add functionality to support Butane docs generation (https://github.com/coreos/butane/issues/390), at which point `internal/doc/generate` will move to` config/doc`.
Fixes https://github.com/coreos/ignition/issues/1469 …
> Generate spec docs from a YAML source file

- .github/ISSUE_TEMPLATE/stabilize-checklist.md
It's not enough to snooze tests using the experimental Butane config during the coreos-assembler ratchet, because kola parses the config even when the test is snoozed.  Disable the tests instead.
> templates/stabilize-checklist: disable tests using exp Butane config

- docs/_sass/custom/custom.scss
- docs/configuration-v3_0.md
- docs/configuration-v3_1.md
- docs/configuration-v3_2.md
- docs/configuration-v3_3.md
- docs/configuration-v3_4.md
- docs/configuration-v3_5_experimental.md
- docs/release-notes.md
- internal/doc/header.md
As discussed in coreos/butane#183 the rendering changes for the specification files also apply to Ignition.
> docs: improve rendering of specification files on GH pages

- internal/exec/engine.go
- internal/exec/stages/files/files.go
- internal/exec/stages/files/filesystemEntries.go
- internal/platform/platform.go
- internal/providers/util/file.go
- internal/state/state.go
The Hyper-V provider will need to write out state for `hv_kvp_daemon`.  Add a way for provider fetch functions to return `[]types.File` which will be saved in `State` and written out during files stage.  Also add a utility function a provider can use to create a `types.File`.
Since this functionality should not be used by most providers, avoid adding an extra argument or return value to every fetch function.  Instead, define an alternative fetch function that will be used if declared in the registration.
Tested synthetically by modifying the `qemu` provider.
> platform: allow provider fetch to save files to write from files stage

- docs/release-notes.md
- internal/exec/util/unit.go
Ignition depends on `systemctl disable` for disabling units. Currently
if the unit does not exist `systemctl disable` exits 1; however, before
systemd 252 `systemctl disable` exits 0 if `--root` is specified. Since
Ignition depends on systemctl's exit code the new behavior caused a
regression, causing the unit.remove.symlinks blackbox test to fail with:
removing enablement symlink(s) for "enoent.service": cannot remove symlink(s) for enoent.service: exit status 1: "Failed to disable unit, unit enoent.service does not exist.\n"
Before disabling a unit, use `systemctl is-enabled` to verify that the
unit exists and is enabled.
Fixes coreos#1614.
> internal/exec/util: check if unit exists before disabling

- config/doc/generate.go
- config/doc/schema.go
- internal/doc/main.go
Allow the `Generate()` caller to specify a callback that receives a slice of path components and returns true if the subtree should be ignored.  This will allow Butane to integrate its field filtering logic into doc generation, rather than separately hardcoding `unless:` directives into the doc YAML.
This is an API change but not a breaking one, since `config/doc` hasn't shipped in a release.
> config/doc: replace `unless:` with `Generate()` callback function

- docs/release-notes.md
- internal/exec/stages/mount/mount.go
> internal/exec: don't relabel a mountpoint that already exists

- docs/release-notes.md
- docs/supported-platforms.md
- dracut/30ignition/module-setup.sh
- go.mod
- go.sum
- internal/providers/hyperv/kvp.go
- internal/register/providers.go
- vendor/github.com/containers/libhvee/LICENSE
- vendor/github.com/containers/libhvee/pkg/kvp/config.go
- vendor/github.com/containers/libhvee/pkg/kvp/kvp.go
- vendor/modules.txt
Read the Ignition config from the Hyper-V Data Exchange Service ("KVP"), which can be configured on the host via WMI.
KVP on Linux is normally handled by a combination of a kernel module (`hv_utils`) and a daemon shipped with the kernel source (`hv_kvp_daemon`).  The latter writes world-readable files to `/var/lib/hyperv`; these contain an array of binary structs.  The host-guest protocol has the guest OS as the passive peer; `hv_kvp_daemon` connects and is sent all the host's key-value pairs.
We don't want to require `hv_kvp_daemon` as a dependency, so we use a pure Go reimplementation (libhvee) that supports just enough of the protocol to receive the KVPs.  However, if we disconnect and then `hv_kvp_daemon` reconnects later, the host won't re-send the KVPs, so we also need to save them …
> Add support for Hyper-V platform

- docs/release-notes.md
- dracut/30ignition/module-setup.sh
It only exists on x86 and aarch64.  The conventional way to handle this is to omit the `-c` flag, silently ignoring installation failures.
Fixes https://github.com/coreos/ignition/issues/1671.  Fixes #1555.
> dracut: make `hv_utils` module optional

- docs/release-notes.md
- docs/supported-platforms.md
- internal/providers/hetzner/hetzner.go
- internal/register/providers.go
* Add Hetzner Cloud as a provider
* Userdata endpoint is http://169.254.169.254/hetzner/v1/userdata
---
Figured out this is actually trivial, so here's a PR.
Supersedes #667 and #1262 which I cannot push commits to.
Relates: https://github.com/coreos/fedora-coreos-tracker/issues/1324
> providers/hetzner: add support for Hetzner Cloud

- docs/release-notes.md
- internal/exec/stages/disks/disks.go
- internal/exec/stages/disks/filesystems.go
- internal/exec/stages/disks/luks.go
- internal/exec/stages/disks/partitions.go
- internal/exec/stages/disks/raid.go
The "udevadm settle" command used to wait for udev to process the disk
changes and recreate the entries under /dev was still prone to races
where udev didn't get notified yet of the final event to wait for.
This caused the boot with a btrfs root filesystem created by Ignition
to fail almost every time on certain hardware.
Issue tagged events and wait for them to be processed by udev. This is
actually meanigful in all stages not only for the other parts of the
initramfs which may be surprised by sudden device nodes disappearing
shortly like the case was with systemd's fsck service but also for the
inter-stage dependencies which currently are using the waiter for
systemd device units but that doesn't really prevent from races with
udev device node recreation. Thus, these changes are …
> internal/exec/stages/disks: prevent races with udev

- Makefile
- docs/release-notes.md
- grub2/ignition.cfg
This pairs with https://github.com/coreos/bootupd/pull/543 Basically we want bootupd to take care of installing this.  Add the config here (where it more closely arguably belongs) so that it can be optionally installed.
My proposal for at least the Fedora packaging of Ignition is that we unconditionally depend on bootupd and install this, because there's no one there using Ignition who doesn't want bootupd.
> Add optionally-installed grub2 code

- docs/release-notes.md
- internal/exec/stages/disks/partitions.go
- tests/blackbox_test.go
- tests/filesystem.go
- tests/positive/partitions/wipe.go
- tests/types/types.go
When `wipeTable` is enabled, we run `sgdisk --zap-all`. But if the table
was corrupted in the first place, `sgdisk` will exit with code 2 which
then breaks boot.
As a workaround, Ignition used to retry the invocation but the context
around it was lost in #544 and #1149 and the retry was removed and
the error-checking was added.
So this patch effectively re-applies 94c98bc ("sgdisk: retry zap-all
operation on failure"), but now with a comment and a test to make sure
we don't regress again.
Closes: coreos/fedora-coreos-tracker#1596
> stages/disks: retry `sgdisk --zap-all` invocation

- dracut/30ignition/module-setup.sh
A review comment to #1696 suggested I see if I could eliminate a pair of modules needed in the ramdisk to consume an ignition file over vsock. In doing the testing, I experienced a false positive; unfortunately, I have determined they are in fact needed and this PR asks to add them again.
> Add vsock modules into ramdisk

- docs/development.md
- docs/release-notes.md
- go.mod
With go 1.19 being EOL bump to 1.20
> Bump minimum Go version to 1.20

- docs/release-notes.md
- internal/exec/stages/files/files.go
The code that handles systemd unit enablement via preset will no op if
disabling a systemd unit that is already disabled, which means that we
wouldn't create a preset file in that case. But we did mark the preset
file as needing relabeling unconditionally. Since `setfiles` errors out
if you pass it a path that doesn't exist, this would break boot.
Fix this by filtering out all entries that don't exist right before we
call `setfiles`. Another approach would've been to only mark the file
for relabeling if we actually did write the file, but this is more
complex than it seems because the relabeling logic needs to know what
is the first component in the path that had to be created. So we'd need
logic both before and after file creation.
This isn't user-reported; we hit this in a CI test.
> stages/files: filter out non-existent paths before relabeling

- docs/release-notes.md
- docs/supported-platforms.md
- internal/providers/scaleway/scaleway.go
- internal/register/providers.go
- internal/resource/url.go
Hi,
In this PR we add the support for Scaleway cloud provider. Locally tested on Flatcar + Scaleway:
```
./ignition --platform scaleway --stage fetch --config-cache ./config.json
```
While it's a regular IMDS endpoint, it has a small difference with other providers:
```
$ curl http://169.254.42.42/user_data/cloud-init
```
I decided to go with a new `FetchOption` called `LocalPort` and to override the default `DialContext`.
Related to: https://github.com/coreos/fedora-coreos-tracker/issues/866
> providers: add scaleway

- docs/release-notes.md
- internal/providers/azure/azure.go
- internal/resource/http.go
- internal/resource/url.go
For some reason, the Azure IMDS server expects clients to retry their HTTP requests even on codes that usually would be considered final. The documented one is 410[[1]], but let's just match the set from cloud-init, which also includes 404 and 429[[2]].
Closes: #1806
[1]: https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=linux#errors-and-debugging
[2]: https://github.com/canonical/cloud-init/commit/c1a2047cf291
> azure: retry HTTP requests on codes 404, 410, and 429

- docs/release-notes.md
- docs/supported-platforms.md
- internal/providers/akamai/akamai.go
- internal/register/providers.go
The "akamai" provider adds support for retrieving an ignition configuration from Akamai Connected Cloud's (a.k.a. Linode) [Metadata Service][1].
See https://github.com/flatcar/Flatcar/issues/1404
See https://github.com/coreos/fedora-coreos-tracker/issues/1701
[1]: https://www.linode.com/docs/products/compute/compute-instances/guides/metadata/
> providers: add "akamai" provider

- README.md
- docs/index.md
Flatcar is using Ignition since the beginning and we are more than happy with it.
--
Let's make it official? And I would like to mention this again: https://github.com/coreos/afterburn/issues/1076#issuecomment-2163353183
> as Flatcar is a good user of Ignition / Afterburn maybe we can help in the maintenance/release process of those software
> docs: mention known users

- docs/release-notes.md
- internal/providers/akamai/akamai.go
trailing \x00 character was making Ignition to fail parsing the config. It is not always the case, that is why we did not catch it earlier: when there is no padding in the base64 payload, everything was working.
https://pkg.go.dev/encoding/base64#Encoding.Decode
---
cc @nesv 
(sorry for the screenshot but it's not easy to copy-paste logs from emergency shell) 
EDIT: Successfully tested on Flatcar test build with previously failing configuration.
> akamai: fix base64 decoding

- docs/supported-platforms.md
Dropped the word 'only' from sentence
Ignition is currently only supported for the following platforms:
> Widely supported platforms

- docs/release-notes.md
- dracut/30ignition/module-setup.sh
- internal/distro/distro.go
- internal/exec/stages/disks/partitions.go
- disks: Refuse to modify disks/partitions in use
When a partition or the whole disk is in use, sgdisk should not execute
the destructive operation.
Add a check that errors out when a disk in use or a partition in use is
to be destroyed.
- sgdisk: Run partx after partition changes
The sgdisk tool does not update the kernel partition table with BLKPG in
contrast to other similar tools but only uses BLKRRPART which fails as
soon as one partition of the disk is mounted.
Update the kernel partition table with partx when we know that a
partition of the disk is in use.
> sgdisk: Run partx after partition changes

- docs/release-notes.md
- docs/supported-platforms.md
- internal/providers/proxmoxve/proxmoxve.go
- internal/register/providers.go
Hello, this PR is a continuation of #1790. The original PR is doing good, but we cannot push to it and we would like things to go faster so we decided to make another one to finish it.
This PR includes the commit from @b-, and a fix for https://github.com/coreos/ignition/pull/1790#discussion_r1674311256. I also added release note.
I think this is good to go. Feel free to tell me otherwise.
> providers: support for Proxmox VE (continuation)

- docs/operator-notes.md
I learned this the hard way (see https://github.com/flatcar/Flatcar/discussions/1152), and thought it would be useful to have in the documentation.
Feedback and edits welcome!
> docs/operator-notes: Note paths that should not be used b/c of switch_root

- build
I dont see mention of this change in the 1.23 changelog, however it is mentioned in the commit https://github.com/golang/go/commit/c22865fcfa1ec434e5655c652c6376fa2d0eb821
fixes: #1931
> build: drop package name when used with 'go clean' argument(s)

- docs/release-notes.md
- dracut/30ignition/ignition-mount.service
On some providers (like Equinix Metal), there is a network dependency for the umount stage, network must be still around when ExecStop is executed.
Thanks @dustymabe for the suggestion on the fix. :muscle: 
---
Tested on Flatcar CI with Equinix Metal tests:
* working: http://bincache.flatcar-linux.net/testing/9999.0.1+tormath1-ignition/amd64/equinix_metal/_kola_temp/equinixmetal-2024-09-12-1117-222/kubeadm.v1.28.7.calico.base/5c53442c-d350-41dd-9fe3-eeaf1c726cd4/console.txt
```
[   17.117250] ignition[1066]: INFO     : Stage: umount
[   17.134237] ignition[1066]: INFO     : no configs at "/usr/lib/ignition/base.d"
[   17.144233] ignition[1066]: INFO     : no config dir at "/usr/lib/ignition/base.platform.d/packet"
[   17.155231] ignition[1066]: INFO     : umount: umount passed
[ …
```
> dracut: add dependency network to ignition-mount.service

- config/doc/ignition.yaml
- docs/configuration-v3_5_experimental.md
This PR is raised to correct the sentence in `desc:` for CEX feature in ignition as well as butane. 
Ref: https://github.com/coreos/butane/pull/536#discussion_r1678449662
> config/doc/ignition.yaml: correction in description

- .github/workflows/go.yml
- .github/workflows/ignition-validate.yml
- internal/exec/config_fetcher.go
- internal/exec/engine.go
- internal/exec/stages/files/files.go
- internal/exec/util/file.go
- internal/main.go
- internal/resource/http.go
- test
Created by [GitHub workflow](https://github.com/coreos/repo-templates/actions/workflows/sync.yml) ([source](https://github.com/coreos/repo-templates/blob/main/.github/workflows/sync.yml)).
Sync with coreos/repo-templates@91391bc86328adbabb729407cd098a1930c5ade1.
> Sync repo templates ⚙

- docs/release-notes.md
- internal/providers/akamai/akamai.go
- internal/providers/util/unzip.go
- internal/providers/util/unzip_test.go
This pull request introduces functionality to handle compressed userdata in the Linode Metadata Service and includes the implementation of a utility function to decompress gzip data if needed. The most important changes include modifications to the `fetchConfig` function and the addition of a new utility function for gzip decompression.
Enhancements to userdata handling:
* [`internal/providers/akamai/akamai.go`](diffhunk://#diff-be714034d6f150da34c73bffef8c0abe1f40bb1120133acacc667da90b09678bL94-R101): Updated the `fetchConfig` function to decompress gzip data if needed before parsing the configuration.
New utility function:
* [`internal/providers/util/unzip.go`](diffhunk://#diff-6bfa7cb53910fd35effb0a56e78ac477cc39aec9b1d624c2992ae8a616ec0429R1-R43): Added a new utility function …
> feat(akamai): unzip user content

- docs/release-notes.md
- internal/exec/engine.go
There is no systemd and journal in our distribution, and when using ignition, many warning logs are printed. The changes in this PR will check if there is a journal in the current distribution, and if not, it will not pass the logs to the journal.
Notes: The distro Alpine has no journal. Add conditional to avoid failure due to logging method not being available.
> refactor(log): ingore error log when journal is disable

- dracut/30ignition/module-setup.sh
The tpm2_getcap is required for Clevis TPM2 operations but was missing from the initrd.
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1836
> Add tpm2_getcap to the initrd for Clevis TPM2 functionality

- dracut/30ignition/module-setup.sh
We are reverting the addition of `tpm2_cap` binary that was done as part of the kola test failure `ext.config.var-mount.luks` caused by clevis pkg upgrade from `clevis-21-6.fc42 -> 21-7.fc42`, as the issue is now fixed in with clevis pkg update `clevis-21-8.fc42.x86_64`
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1836#issuecomment-2513303989
> Reverting tpm2_getcap change

- docs/release-notes.md
- dracut/30ignition/module-setup.sh
While doing  testing hardware disk encryption using cex on `4.19 rhel 9.6 `failed to detect cex domain for luks encryption. 
```
[   23.293503] ignition[970]: Ignition failed: failed to create luks: generating secure key: generating secure key: exit status 1: Cmd: "zkey" "generate" "--name" "ignition-luks-root" "--key-type" "CCA-AESCIPHER" "--xts" "--description" "Secure Key for root Volume" "--apqns" "00.0047" Stdout: "" Stderr: "zkey: No APQN is available that can generate a secure key of type CCA-AESCIPHER\n"
[   23.294715] systemd[1]: ignition-disks.service: Main process exited, code=exited, status=1/FAILURE
[FAILED] Failed to start Ignition (disks).
[   23.295000] systemd[1]: Failed to start Ignition (disks).
```
when run the command in verbose mode folllowing logs found.
``` …
```
> dracut: Correctly add pkey_cca kernel mod for cex card

- docs/operator-notes.md
- internal/providers/azure/azure.go
- internal/resource/url.go
This is a followup to the PR #1923
Add fallback logic, and add documentation.
cc: https://github.com/coreos/ignition/issues/2008
> Update azure priv fetch

- docs/release-notes.md
- docs/supported-platforms.md
- internal/providers/proxmoxve/proxmoxve.go
This PR adds support for reading Ignition data out of the vendor-data file so we can leave the cloud-config in the user-data file. It will always use the user-data file if it has an ignition config over using the vendor-data file.
This works as expected:
```bash
INFO     : Ignition v2.10.1-1315-gaf19b7d7-dirty
INFO     : Stage: fetch
INFO     : no config dir at "/usr/lib/ignition/base.d"
INFO     : no config dir at "/usr/lib/ignition/base.platform.d/proxmoxve"
DEBUG    : parsed url from cmdline: ""
INFO     : no config URL provided
INFO     : reading system config file "/usr/lib/ignition/user.ign"
INFO     : no config at "/usr/lib/ignition/user.ign"
DEBUG    : creating temporary mount point
INFO     : op(1): [started]  mounting config drive
DEBUG    : op(1): executing: "mount" "-o" "ro" …
```
> providers: support for vendor-data in proxmoxve

- .github/ISSUE_TEMPLATE/stabilize-checklist.md
With the latest github changes, issue templates are now required to have a yaml matter header to function.
> issue_template/stablize-checklist: add yaml matter header

- .cci.jenkinsfile
These can now be built in a single invocation so let's do that.
> .cci.jenkinsfile: switch to `cosa osbuild`

- Dockerfile.validate
Switch the builder stage from `registry.fedoraproject.org` to `quay.io/fedora/fedora:42` to align with common usage in container build workflows.
Ref : https://github.com/coreos/fedora-coreos-tracker/issues/1851
> Dockerfile: use quay.io as source for Fedora base image

- config/doc/ignition.yaml
- config/shared/errors/errors.go
- config/v3_4/translate/translate.go
- config/v3_4/types/directory.go
- config/v3_4/types/file.go
- config/v3_4/types/mode.go
- config/v3_4/types/mode_test.go
- config/v3_5/types/directory.go
- config/v3_5/types/file.go
- config/v3_5/types/mode.go
- config/v3_5/types/mode_test.go
- config/v3_6_experimental/translate/translate.go
- docs/configuration-v3_4.md
- docs/configuration-v3_5.md
- docs/migrating-configs.md
- docs/release-notes.md
- internal/exec/util/file.go
- tests/positive/files/file.go
- tests/register/register.go
- tests/types/types.go
- tests/validator.go
Support for setuid/setgid/sticky bit got added in [1] but we did not add tests and it's unclear when support for it broke.
[1]: https://github.com/coreos/ignition/pull/1325
See: https://github.com/coreos/ignition/issues/2042
> Fix setting setuid/gid bits with uid/gid and add a test

- docs/release-notes.md
- internal/providers/oraclecloud/oraclecloud.go
Ignition internal machinery relies on being able to match against an error directly, in this case, `ErrNeedNet`. By wrapping errors from `FetchToBuffer`, ignition would not be able to detect the lack of networking during `fetch-offline` phase and fail to run.
> oraclecloud: do not wrap errors from FetchToBuffer

- docs/release-notes.md
- docs/supported-platforms.md
- internal/providers/upcloud/upcloud.go
- internal/register/providers.go
This PR adds support for fetching the ignition config from UpCloud metadata service.
Successfully tested with a custom-built flatcar image.
> providers: add UpCloud provider
