Makefile

Appending V=1 to the make argv shows the commands being executed.

make: support kernel-style V=1 verbose build switch

---

exec/stages/prepivot/prepivot.go

Also s/pre-pivot/prepivot/ for consistency.

exec/stages/prepivot: put in prepivot package (was stages)

---

config/config.go
config/file.go
config/file_test.go
config/filesystem.go
config/filesystem_test.go
config/storage.go
config/systemd.go
config/systemd_test.go

This needs some more tests, but I want to get some feedback.

config: parse config as JSON instead of YAML

---

config/config.go
config/networkd.go
config/systemd.go
config/systemd_test.go
config/unit.go
exec/stages/prepivot/prepivot.go

Go is such an impossible language to work with that I cannot accomplish
this without an incredible amount of duplicated code. I'd rather burn it
all to the ground instead.

config: add networkd units

---

README.md
ROADMAP.md

/cc @vcaputo how does that timeline look?

doc: add README and ROADMAP

---

Makefile
src/exec/stages/prepivot/prepivot.go
src/exec/util/path.go
src/exec/util/unit.go

I was also able to simplify the Makefile; a nice side effect of the directory move.

network: fix the location to which network units are written

---

src/main.go

Clear cache

---

src/main.go
src/providers/file/file.go

File provider

---

src/exec/stages/storage/storage.go

Last commit is the interesting one.

Write files

---

src/config/raid.go

- Ensure Level is valid
- Disallow setting Spares with incompatible levels

config/storage: add some sanity checks for Raid

---

src/config/unit.go

config: rename "dropIns" to "dropins"

---

doc/config.md
doc/ignition.md
src/config/config.go
src/config/config_test.go
src/config/disk.go
src/config/partition.go

This will make it easier to recognize this as an Ignition configuration
file.

config: change 'version' to 'ignitionVersion'

---

Makefile
src/exec/engine.go
src/exec/engine_test.go
src/exec/stages/name.go
src/exec/stages/prepivot/prepivot.go
src/exec/stages/stages.go
src/exec/stages/storage/storage.go
src/main.go

I got a little trigger happy before. We do actually need these in seperate stages with multiple invocations.

exec: reintroduce stages

---

Makefile
src/exec/stages/disks/disks.go
src/exec/stages/files/files.go
src/main.go

storage -> disks
prepivot -> files

exec/stages: rename storage and prepivot

---

src/main.go
src/oem/oem.go

Depends on https://github.com/coreos/ignition/pull/89.

oem: add all of the OEMS supported by CoreOS

---

NEWS

Adds necessary ssh keys support to the ec2 provider.

Add v0.1.3 NEWS

---

src/providers/cmdline/cmdline.go

Looks for the supplied path in /mnt/oem and /sysroot/usr/share/oem
when oem:// is used as the scheme instead of http://.
Fixes #110

providers/cmdline: support oem:// url scheme

---

src/providers/cmdline/cmdline.go

If the path specified in oem:// doesn't exist at
/sysroot/usr/share/oem/... then we will wait for /dev/disk/by-label/OEM
and mount it before retrying the path there.
This change is necessary because the ignition service no longer requires
the OEM mount in systemd, previously we could assume it would be there.

providers/cmdline: mount oem partition for oem:// if needed

---

src/systemd/systemd.go

A few systemd.conf attendees pointed out that device units could be
started directly. We'll use that approach instead of the transient
units.

systemd: start device units directly

---

doc/getting-started.md
doc/supported-platforms.md

split https://github.com/coreos/ignition/pull/159 into two parts.

Added some extra links and PXE boot note

---

src/config/filesystem.go
src/config/filesystem_test.go

I'm not sure what I was thinking the first time around...

config: clean up filesystem assertion

---

doc/supported-platforms.md

docs: add vmware to supported platforms

---

doc/configuration.md
src/config/types/file.go
src/exec/util/file.go
src/exec/util/unit.go

This will allow the ability to reference a user or group my name in the future.

*: move file ownership into separate section

---

src/providers/vmware/vmware_unsupported.go

Fixes https://github.com/coreos/bugs/issues/1175.

providers/vmware: fix build for arm

---

doc/getting-started.md

Clean up the markdown source acc to STYLE.md rules.
Supersedes #195 .

docs/getting-started: Add intro to Ignition

---

doc/examples.md
doc/migrating-configs.md

docs: add migration guide for 1 -> 2.0.0.

---

doc/examples.md
doc/getting-started.md

Fixes https://github.com/coreos/bugs/issues/1030.

docs: fix disk examples and add note about journal

---

.travis.yml
build
gimme.local

This finishes the work started by @crawford in https://github.com/coreos/ignition/pull/194.
This PR includes the gimme script submitted upstream https://github.com/travis-ci/gimme/pull/45.  If that is merged we can remove the gimme.local here.

build: add ARM64 to test matrix

---

internal/log/log.go

log: capture stdout from subcommands

---

config/config.go

Once we introduce point releases for the v2 spec, we will need to pay
attention to more than just the major version.

config: switch parsing based on full version

---

config/types/filesystem.go
config/types/filesystem_test.go
config/types/url.go
config/types/url_test.go

Cleanup old AssertValid's
Update tests
Add AssertValid for URL

types: assertvalid cleanup

---

config/validate/validate.go

Treat members of embedded structs as you own when validating.

validate: fix bug with embedded structs

---

internal/sgdisk/sgdisk.go

I'm guessing nobody has really tried to use this feature...

sgdisk: use correct flag for setting the typecode

---

config/config.go
config/validate/astjson/node.go
config/validate/validate.go
config/validate/validate_test.go

Make validate more general so it can be used by fuze as well.

validation: make validate function more general

---

config/v2_0/types/unit.go
config/v2_0/types/unit_test.go
config/v2_0/types/url.go
config/v2_0/types/url_test.go

Supersedes https://github.com/coreos/ignition/pull/330.

config/v2_0/types: backport improvements

---

config/types/directory.go
config/types/unit.go
config/v1/types/path.go
config/v1/types/unit.go
config/v2_0/types/path.go
config/v2_0/types/unit.go

follow up to #348
There are still uses of "path/filepath" in ignition, but those all deal with reading files.
cc @crawford

config: more changes from path/filepath to path

---

doc/getting-started.md

Current configspec points not outdated location.

doc: update configspec location to correct file

---

internal/exec/stages/disks/disks.go

The disks stage could complete with udev events still in flight. When running `mkfs.btrfs` to overwrite an existing filesystem, this could cause `by-label` symlinks to be temporarily deleted while other systemd units were expecting them to exist.
Fixes https://github.com/coreos/bugs/issues/1964.

stages/disks: Wait for uevents triggered by mkfs to settle

---

doc/examples.md
doc/getting-started.md
doc/migrating-configs.md

This will allow us to render these properly on coreos.com.

docs: add ignition to the code fence info string

---

doc/production-users.md

Revert "docs: remove adobe from production users"

---

doc/production-users.md

- Add Azure and datacenter environments
- Add detail around cloud-specific tools used to load Ignition templates

Additional detail around Adobe production use case

---

README.md

Clean checkout and build failed :(
```
$ ./build
Building ignition...
gopath/src/github.com/coreos/ignition/internal/exec/util/blkid.c:15:25: fatal error: blkid/blkid.h: No such file or directory
#include <blkid/blkid.h>
^
compilation terminated.
```

README: List required devel packages for header files

---

internal/oem/oem.go

etcd v0 has been removed from Container Linux.

oem: Drop etcd.service drop-in

---

doc/operator-notes.md

Fixes https://github.com/coreos/bugs/issues/1995

doc/operator-notes.md: document the http retry and backoff logic

---

internal/oem/oem.go
internal/providers/virtualbox/virtualbox.go

*: add support for virtualbox

---

NEWS

dependent on https://github.com/coreos/ignition/pull/396

news: add news for v0.16.0

---

config/types/schema.go
doc/configuration-v2_1-experimental.md
internal/exec/stages/files/files.go
internal/exec/util/unit.go
internal/util/util.go
schema/ignition.json

Partially fixes https://github.com/coreos/bugs/issues/1287. This still won't work on Container Linux.

*: add support for disabling services

---

config/config.go

The version function in config/config.go can be generally useful to
other users (like mantle), so this commit makes the function exported.
Additionally, the function is modified to return an error when the
version is undeterminable instead of an empty semver and no error.
cc @bgilbert

config/config.go: export Version, return error if undeterminable version

---

doc/configuration-v2_1.md
doc/configuration-v2_2-experimental.md

Touches on https://github.com/coreos/bugs/issues/2067

doc/configuration: add s3 to schemes for config relacing/appending

---

doc/configuration-v2_2-experimental.md

Per https://github.com/coreos/ignition/pull/426#discussion_r133817777.

doc/configuration: clarify experimental spec version

---

doc/supported-platforms.md
internal/oem/oem.go
internal/providers/oracleoci/oracleoci.go

Adds an initial implementation for the oracle provider in Ignition.
Testing this in the oracle cloud on a bare metal server, here's logs of it running:
```
Aug 29 19:50:36 localhost ignition[756]: Ignition v0.17.2-21-gad44e48-dirty
Aug 29 19:50:36 localhost ignition[756]: parsed url from cmdline: ""
Aug 29 19:50:36 localhost ignition[756]: no config URL provided
Aug 29 19:50:36 localhost ignition[756]: GET http://169.254.169.254/opc/v1/instance/metadata/user_data: attempt #1
Aug 29 19:50:36 localhost ignition[756]: GET error: Get http://169.254.169.254/opc/v1/instance/metadata/user_data: dial tcp 169.254.169.254:80: connect: network is unreachable
Aug 29 19:50:36 localhost ignition[756]: GET http://169.254.169.254/opc/v1/instance/metadata/user_data: attempt #2
Aug 29 19:50:36 localhost …
```

internal/providers/oracleoci: add initial implementation

---

internal/exec/stages/disks/disks.go
internal/exec/util/device_alias.go

This addresses two races:
1) We create symlink aliases for devices as soon as they become available, since udevd will frequently delete them moments later. Unfortunately, sometimes the device is deleted before we even get a chance to do that. This PR let Ignition retry the alias creation.
2) The same deletion behavior can affect other systemd units that depend on the created `/dev/*` symlinks and Ignition. Running `udevadm settle` greatly reduces the size of the race. This PR ensures we always settle if we mess with disks, even if we do not create filesystems.

Fix races with udev

---

.github/tailor.yaml
CONTRIBUTING.md

Tailor is a tool for validating pull requests comply with a set of
rules. Initially, this will help ensure that commits are properly
formatted.

test: add tailor configuration

---

internal/oem/oem.go

oem: delete google/cloud-sdk containers on exit

---

doc/configuration-v2_0.md
doc/configuration-v2_1.md
doc/configuration-v2_2-experimental.md
tests/positive/general/general.go

Fixes https://github.com/coreos/bugs/issues/2251

doc: add data as supported type for append/replace

---

NEWS

@bgilbert: does this describe the oem config changes sufficiently, or am I missing something?

news: add news for v0.20.0

---

tests/positive/storage/creation.go

Fix compilation error introduced in c8299bd66df31dd06a53ca280628667625c6a8a7.

tests: fix compilation

---

doc/examples.md
doc/getting-started.md
doc/migrating-configs.md
internal/util/tools/docs/docs.go
test

Use CLCT's docs validation to ensure we have correct docs.

Add docs validation

---

internal/exec/stages/files/files_test.go
internal/exec/util/user_group_lookup_test.go
internal/log/log.go
internal/main.go
tests/blackbox_test.go
tests/filesystem.go
tests/validator.go

This contains a set of changes/improvements to the blackbox tests I wrote in service of getting Jenkins to work with Ignition.

Blackbox test improvements for Jenkins

---

NEWS

This PR includes two commits: the news updates for v0.20.1 which have yet to make it into master, and the news updates for v0.21.0.
This PR represents release v0.21.0.

news: add news for v0.21.0

---

README.md

Ignition should be up to the standard of our other open source projects outlining how to get involved and where to find and file bugs. Follow the template of etcd.

README: add contribution and links

---

doc/rationale.md

There's nowhere in Ignition's docs that explain the particulars of how
and why it works the way it does (e.g. running on first boot). Add a
document to start explaining that.

doc: detail Ignition's design and the rationale behind it

---

doc/operator-notes.md

This adds a section to the operator's notes on using Ignition on distributions with selinux. I figure this is a stop-gap for users for the time period between when we've published a working Ignition implementation on Fedora/RHEL (which we already have internally) and when we create tooling to generate Ignition configs for those distributions.

doc: document how to use Ignition on selinux enforcing distributions

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-systemd/dbus/methods.go
vendor/github.com/coreos/go-systemd/dbus/set.go
vendor/github.com/coreos/go-systemd/dbus/subscription.go
vendor/github.com/coreos/go-systemd/unit/deserialize.go
vendor/github.com/coreos/go-systemd/unit/option.go

Vendor update with minor go-systemd bugfixes, see https://github.com/coreos/go-systemd/releases/tag/v17.

vendor: update go-systemd to v17

---

glide.lock
glide.yaml
vendor/github.com/jmespath/go-jmespath/functions.go
vendor/github.com/jmespath/go-jmespath/parser.go

It is not clear why this was initially pinned. Unpin it so it can be
updated.

vendor: unpin transient dependency jmespath

---

doc/configuration-v2_3-experimental.md
doc/operator-notes.md

with feedback from https://github.com/coreos/ignition/pull/544#pullrequestreview-125013424

docs: improve partitioning docs clarity

---

tests/blackbox_test.go
tests/filesystem.go
tests/positive/timeouts/timeouts.go
tests/validator.go

Fix a few blackbox test bugs and do some cleanup and refactoring to make future work easier.

cleanup blackbox tests

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-systemd/dbus/dbus.go
vendor/github.com/coreos/go-systemd/dbus/methods.go
vendor/github.com/coreos/go-systemd/unit/deserialize.go
vendor/github.com/go-ini/ini/ini.go
vendor/github.com/go-ini/ini/key.go
vendor/github.com/go-ini/ini/parser.go
vendor/github.com/go-ini/ini/section.go
vendor/github.com/go-ini/ini/struct.go
vendor/github.com/godbus/dbus/auth.go
vendor/github.com/godbus/dbus/auth_anonymous.go
vendor/github.com/godbus/dbus/call.go
vendor/github.com/godbus/dbus/conn.go
vendor/github.com/godbus/dbus/conn_other.go
vendor/github.com/godbus/dbus/conn_unix.go
vendor/github.com/godbus/dbus/conn_windows.go
vendor/github.com/godbus/dbus/decoder.go
vendor/github.com/godbus/dbus/default_handler.go
vendor/github.com/godbus/dbus/export.go
vendor/github.com/godbus/dbus/object.go
vendor/github.com/godbus/dbus/server_interfaces.go
vendor/github.com/godbus/dbus/transport_generic.go
vendor/github.com/godbus/dbus/transport_nonce_tcp.go
vendor/github.com/godbus/dbus/transport_unix.go
vendor/github.com/jmespath/go-jmespath/functions.go
vendor/github.com/jmespath/go-jmespath/parser.go

This updates go-systemd to latest release, and massages glade manifests to avoid floating versions on transitive dependencies.

glide: update go-systemd to v18 

---

config/v2_3_experimental/types/schema.go
internal/config/types/schema.go
schema/ignition.json
tests/positive/partitions/complex-mb.go
tests/positive/partitions/creation-mb.go

Change size-mb and start-mb to sizeMB and startMB to be consistent with
the rest of the spec.

schema: fix incorrect case

---

internal/exec/util/file.go
internal/exec/util/util.go
tests/negative/files/link.go
tests/positive/files/link.go

cc @darkmuggle
Still need to run this through kola, but it passes the tests I added.

Fix symlinks again

---

tests/blackbox_test.go

Add a flag to list the tests that would be run without actually running
them.

tests: add -list flag to blackbox tests

---

README.md

Will wait for Ignition 0.30.0 NEWS changes to merge before merging

readme: add note about branching

---

doc/development.md

Minor note, which I found useful.

doc/development: add note to run individual blackbox tests

---

internal/exec/stages/files/files.go
internal/exec/stages/files/filesystemEntries.go
internal/exec/util/user_group_lookup.go
internal/exec/util/util.go
tests/blackbox_test.go
tests/positive/files/file.go

Fixes https://github.com/coreos/ignition/issues/722

Fix user lookup

---

internal/exec/engine.go
internal/providers/util/config.go

backport of https://github.com/coreos/ignition/pull/726

[backport] Dont leak configs to journal

---

config/v3_0_experimental/types/url.go
config/v3_0_experimental/types/url_test.go
doc/supported-platforms.md
internal/distro/distro.go
internal/resource/url.go
tests/blackbox_test.go
tests/negative/files/missing_file.go
tests/negative/general/config.go
tests/positive/files/remote.go

*: drop OEM URI support

---

MAINTAINERS

MAINTAINERS: update for spec2x

---

internal/exec/stages/files/units.go

Non-runtime units and dropins need to be relabeled relative to `DestDir`, since relabeling happens in the real root.
#771 addressed this for files.

stages/files: fix unit relabeling to exclude DestDir

---

config/shared/errors/errors.go

Remove all errors that are not used anywhere.

config/shared/errors: drop unused errors

---

config/v2_0/append.go
config/v2_0/append_test.go
config/v2_1/append.go
config/v2_1/append_test.go
config/v2_2/append.go
config/v2_2/append_test.go
config/v2_3/append.go
config/v2_3/append_test.go
config/v2_4_experimental/append.go
config/v2_4_experimental/append_test.go

config/*/append: add append function back

---

NEWS

Depends on https://github.com/coreos/ignition/pull/796

news: add news for v0.32.0

---

doc/configuration-v3_0.md
doc/configuration-v3_1.md

Add notes specifying which fields must be unique.
Will add another commit for 3.1.0-experimental once this one looks good.

doc/config-v3_0: Add notes about uniqueness

---

build_releases

Drop gopath bits. Add -mod=vendor bits. Change package to v2.

build_releases: update for using go mod

---

NEWS

Looking to release on Monday (hence future date), give myself the weekend to make sure there's nothing else that should go in this.

news: update for v2.0.0

---

internal/exec/engine.go
internal/providers/aws/aws.go
internal/providers/azure/azure.go
internal/providers/cloudstack/cloudstack.go
internal/providers/cmdline/cmdline.go
internal/providers/digitalocean/digitalocean.go
internal/providers/file/file.go
internal/providers/gcp/gcp.go
internal/providers/noop/noop.go
internal/providers/openstack/openstack.go
internal/providers/packet/packet.go
internal/providers/providers.go
internal/providers/qemu/qemu.go
internal/providers/system/system.go
internal/providers/virtualbox/virtualbox.go
internal/providers/vmware/vmware_amd64.go
internal/providers/vmware/vmware_unsupported.go

Should fix https://github.com/coreos/ignition/issues/826
should be backported to spec2x once merged

aws: get region after getting config

---

internal/exec/engine.go
internal/providers/azure/azure.go
internal/providers/cloudstack/cloudstack.go
internal/providers/cmdline/cmdline.go
internal/providers/digitalocean/digitalocean.go
internal/providers/ec2/ec2.go
internal/providers/file/file.go
internal/providers/gce/gce.go
internal/providers/noop/noop.go
internal/providers/openstack/openstack.go
internal/providers/packet/packet.go
internal/providers/providers.go
internal/providers/qemu/qemu.go
internal/providers/system/system.go
internal/providers/virtualbox/virtualbox.go
internal/providers/vmware/vmware_amd64.go
internal/providers/vmware/vmware_unsupported.go

Backport https://github.com/coreos/ignition/pull/828
Fixes https://github.com/coreos/ignition/issues/826

Backport aws fix

---

NEWS

Depends on https://github.com/coreos/ignition/pull/832

news: add news for v2.0.1

---

internal/exec/util/blkid.c
tests/negative/partitions/zeroes.go

In case no GPT partition label is set don't abort execution.

Continue on empty GPT partition label

---

internal/exec/util/blkid.c
tests/negative/partitions/zeroes.go

Backport of https://github.com/coreos/ignition/pull/847

Backport GPT fixes

---

internal/oem/oem.go
internal/providers/aliyun/aliyun.go

Backport of https://github.com/coreos/ignition/pull/869
See:
- https://www.alibabacloud.com/help/doc-detail/49122.htm
- https://github.com/coreos/ignition/issues/589
(cherry picked from commit 19d0d6caa7800379cca5a98291ebe90ced58a1a9)

providers/aliyun: Add aliyun

---

README.md

Make it easier to understand how this repo relates to ignition-dracut,
and how the branches relate to FCOS/RHCOS.

README.md: add details about dracut and branches here

---

NEWS

Depends on 
https://github.com/coreos/ignition/pull/901
https://github.com/coreos/ignition/pull/900

news: add notes for 2.1.1

---

OWNERS

Add OWNER file. I'd like to enable Prow here too.
/cc @jlebon @jlebon

OWNERS: add OWNERS file

---

internal/platform/platform.go
internal/providers/exoscale/exoscale.go

Add Exoscale provider to ignition
Fetch directly user-data server to retrieve ignition user configuration

Add Exoscale provider

---

internal/platform/platform.go

This sorts the list of providers by platform ID.

platform: sort providers

---

internal/providers/packet/packet.go
internal/resource/url.go

Fix userdata/metadata fetching on Packet

---

internal/exec/stages/fetch/fetch.go
internal/exec/stages/mount/mount.go
internal/exec/stages/umount/umount.go

Random cleanup, broken out of #952.

stages: fix package names

---

internal/exec/util/passwd.go

https://github.com/coreos/fedora-coreos-config/pull/344#issue-403264267
As @cgwalters  suggested, this PR is trying to address the problem (https://github.com/coreos/fedora-coreos-config/pull/344#pullrequestreview-393234733) by sending ssh_authorized keys info directly into the journald log to avoid poking into the user's `home` directory.

Send ssh_authorized keys info into the journald log

---

config/v3_1_experimental/types/verification.go
config/v3_1_experimental/types/verification_test.go
doc/configuration-v3_1-experimental.md
doc/examples.md
internal/util/verification.go
internal/util/verification_test.go
tests/negative/files/invalid_hash.go
tests/positive/files/hash.go
tests/servers/servers.go

Add SHA-256 support for file verification

---

doc/configuration-v2_2.md
doc/configuration-v2_3.md
doc/configuration-v2_4.md
doc/configuration-v2_5-experimental.md
internal/resource/http.go
tests/fixtures/tls_fixture.go
tests/negative/security/tls.go
tests/positive/security/tls.go
tests/servers.go

[spec2x] Backporting the CA bundles support

---

internal/providers/aws/aws.go

Fixes https://github.com/coreos/ignition/issues/989

providers/aws: update metadata version

---

internal/exec/stages/files/filesystemEntries.go
tests/positive/files/link.go

filesystemEntries: create hard links to files that are deeper than the hard link

---

.cci.jenkinsfile

For https://github.com/coreos/coreos-assembler/pull/1530.

ci: change --blacklist-test to --denylist-test

---

internal/providers/azure/azure.go

Azure: allow for either udf or iso9660 config volume
Azure and it's varients use a cdrom for delivering the configuration
data. On Azure proper, the volume type is a udf. On Azure varient the
device may be either an iso9660 or a udf volume.
The previous behavior of the Azure provider was to attempt to mount a udf
volume. In order to support the variant Azures (e.g. Azure Stack),
Ignition will check the filesystem found on the cdrom to make sure its a
known valid type.
Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/476
Signed-off-by: Ben Howard <ben.howard@redhat.com>

Azure: support both udf and iso9660 filesystems types for custom-data

---

.github/ISSUE_TEMPLATE/release-checklist.md
.travis.yml
Dockerfile.validate
README.md
build_for_container
build_releases

For https://github.com/coreos/ignition/issues/1059.

Fix validate container build; add Quay release tag pointing to latest release

---

doc/examples.md
doc/operator-notes.md

doc: add LUKS examples & operator notes

---

README.md
doc/development.md
doc/operator-notes.md
doc/rationale.md

doc: drop references to Container Linux

---

config/merge/merge.go
config/merge/merge_test.go

Spec 3.2.0 added some, which was probably a mistake.  https://github.com/coreos/ignition/issues/1132 contemplates removing them again in a future spec, but for now, let's properly descend into the pointed-to struct during a merge.
Fixes failure to merge in parent fields when both parent and child struct pointers are specified, which is part of https://github.com/coreos/ignition/issues/1132.

config/merge: support struct pointers

---

internal/providers/aws/aws.go

Probing the `/latest` path causes a 401 Unauthorized when running with
IMDSv2 only. Instead ping the token URL.

internal/providers/aws: probe the IMDS token URL

---

docs/configuration-v3_0.md
docs/configuration-v3_1.md
docs/configuration-v3_2.md
docs/configuration-v3_3_experimental.md

Fixes https://github.com/coreos/ignition/issues/1167.

docs/configuration-*: document wipeFilesystem default

---

go.mod
go.sum
vendor/github.com/coreos/vcontext/path/path.go
vendor/github.com/coreos/vcontext/report/report.go
vendor/github.com/coreos/vcontext/validate/validate.go
vendor/modules.txt

https://github.com/coreos/vcontext/pull/14

go.mod: update vcontext for report path fix

---

internal/exec/stages/disks/luks.go

We cannot guarantee that networking is up before we've hit the LUKS
section of the disks stage. If we're creating a tang backed LUKS device
fetch the tang server advertisement before we call clevis.
Closes #1163

stages/disks: ensure networking is up before creating tang devices

---

.cci.jenkinsfile
.github/ISSUE_TEMPLATE/release-checklist.md
.github/workflows/go.yml
CONTRIBUTING.md
README.md
docs/_config.yml
docs/development.md
docs/distributor-notes.md
docs/index.md

*: rename master branch to main

---

internal/exec/stages/disks/luks.go

Report the specific reason that we declined to reuse a device.  Propagate reuse errors earlier so we don't have to guess why reuse failed.
Fixes https://github.com/coreos/ignition/issues/1209.

stages/disks: improve error reporting for LUKS device reuse

---

.github/ISSUE_TEMPLATE/release-checklist.md
README.md
docs/index.md

The Fedora project as a whole is [moving](https://lists.fedoraproject.org/archives/list/announce@lists.fedoraproject.org/message/GGGSZ6NAASOQ3R5XYQ5KLG63HMMXY7GH/).

*: move to libera.chat

---

docs/development.md
docs/migrating-configs.md

docs: updates to migrating-configs and stabilization instructions

---

internal/exec/util/blkid.go

We won't always necessarily be operating on a specific device.  The caller should wrap the error with any additional context it has.
Also clean up some error strings a bit.

internal/exec/util: drop device argument from `cResultToErr()`

---

Dockerfile.validate

xref https://github.com/coreos/fedora-coreos-tracker/issues/884

Dockerfile.validate: build with Fedora 35

---

docs/supported-platforms.md

Fixes: https://github.com/coreos/ignition/commit/50f30547bc0212024c807aeb137e8bc87cc42efb

docs: Add link for Nutanix

---

build
internal/exec/config_fetcher.go
internal/exec/engine.go
internal/exec/stages/disks/disks.go
internal/exec/stages/kargs/kargs.go
internal/log/log.go
validate/main.go

Split out of https://github.com/coreos/ignition/pull/1285. See individual commits.

Prep patches for ignition-liveapply

---

docs/configuration-v3_0.md
docs/configuration-v3_1.md
docs/configuration-v3_2.md
docs/configuration-v3_3.md
docs/configuration-v3_4_experimental.md

Pointed out by @okeanos in https://github.com/coreos/butane/pull/311.

docs/configuration-*: fix its

---

docs/development.md

As requested by @bgilbert during a [similar PR](https://github.com/coreos/butane/pull/298) for butane.

docs: add information about the build system

---

internal/resource/url.go
internal/resource/url_test.go

Followup to https://github.com/coreos/ignition/pull/1264.

internal/resource: fix minor nits

---

.github/ISSUE_TEMPLATE/release-checklist.md

Going through the steps for releasing ignition v2.14.0  https://github.com/coreos/ignition/issues/1353

release-checklist.md: small improvements and updates

---

internal/providers/qemu/qemu_blockdev.go

providers/qemu: Remove unused io import, fix build on ppc64le and s390x

---

.github/workflows/container-rebuild.yml
.github/workflows/container.yml
docs/release-notes.md

Created by [GitHub workflow](https://github.com/coreos/repo-templates/actions/workflows/sync.yml) ([source](https://github.com/coreos/repo-templates/blob/main/.github/workflows/sync.yml)).
Sync with coreos/repo-templates@30f9d7fc373a10994edd7dc3e44bfe54e72f0719.

Sync repo templates ⚙

---

Dockerfile.validate

Update the basefile from f36 to f37.
https://github.com/coreos/fedora-coreos-tracker/issues/1223

Dockerfile.validate: rebase to f37

---

config/shared/errors/errors.go
config/v3_4_experimental/schema/ignition.json
config/v3_4_experimental/translate/translate.go
config/v3_4_experimental/types/schema.go
config/v3_4_experimental/types/tang.go
config/v3_4_experimental/types/tang_test.go
docs/configuration-v3_4_experimental.md
docs/release-notes.md
internal/exec/stages/disks/luks.go
internal/exec/stages/fetch_offline/fetch-offline.go
internal/exec/stages/fetch_offline/fetch_offline_test.go

https://github.com/coreos/ignition/issues/1474

Tang offline provisoning

---

test

Fix ShellCheck errors to prepare for enforcing it in CI.

test: ShellCheck fixes

---

.cci.jenkinsfile
.github/ISSUE_TEMPLATE/stabilize-checklist.md

Use the new kola support in https://github.com/coreos/coreos-assembler/pull/3422.

templates: update CI ratchet procedure for Butane spec stabilization

---

docs/release-notes.md
go.mod
go.sum
vendor/github.com/containers/libhvee/pkg/kvp/config.go
vendor/github.com/containers/libhvee/pkg/kvp/kvp.go
vendor/modules.txt

Fixes https://github.com/coreos/ignition/issues/1664.

Fix build on 32-bit systems; update docs for release

---

docs/development.md
docs/rationale.md

Rendered version [here](https://bgilbert.github.io/ignition/).

Expand development docs and rationale

---

docs/release-notes.md

Updating the Ignition documentation for the v2.17.0 release on November 24th.
This step is part of the release checklist. You can refer to the current checklist this issue #1751

NEWS: update 2.17.0

---

docs/supported-platforms.md

Follow-up of #1794. Sorry for missing this!

docs: add missing scaleway link

---

Dockerfile.validate

https://github.com/coreos/fedora-coreos-tracker/issues/1490

Dockerfile.validate: update to Fedora 39

---

docs/release-notes.md

Updating the Ignition documentation for the v2.18.0 release.
This step is part of the release checklist. You can take a look at the [current checklist](https://github.com/coreos/ignition) for this issue.

NEWS: update 2.18.0

---

docs/release-notes.md

https://github.com/coreos/ignition/issues/1876

docs/release-notes: update for 2.19.0

---

Dockerfile.validate
docs/release-notes.md

https://github.com/coreos/fedora-coreos-tracker/issues/1674

Dockerfile.validate: update to Fedora 40

---

docs/release-notes.md

https://github.com/coreos/ignition/issues/1960

docs/release-notes: update for 2.20.0

---

Dockerfile.validate
docs/release-notes.md

see: https://github.com/coreos/fedora-coreos-tracker/issues/1695

Dockerfile.validate: update to `fedora:41`

---

docs/release-notes.md

Update release notes for release.

docs/release-notes: update for 2.21.0

---

Dockerfile.validate
docs/release-notes.md

Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1851

Dockerfile.validate: update to Fedora 42

---

docs/release-notes.md

Update release notes for release
https://github.com/coreos/ignition/issues/2126

docs/release-notes: update for 2.23.0
